### ISSUE TITLE
Unlock advanced developer option doesnt unlock anything

### ISSUE THREAD

**Issue by ceebi** [GravityBox/GravityBox#1012]
Unlock advanced developer option doesnt unlock anything .After reboot i cant see any change .Only usb debugging mode option is visible in setting .I want all other options .please help

**Comment by C3C0** [comment]
This works on ROMs where developer options were hidden from the users. If manufacturer decided to remove them completely that's something GB can't do anything about.

**Comment by ceebi** [comment]
Is there any way to unlock them?

**Comment by C3C0** [comment]
How to unlock something that was completely removed?

**Comment by ceebi** [comment]
It means there's no way to access animation options?

**Comment by C3C0** [comment]
Added to the KitKat version

**Comment by ceebi** [comment]
Please add to JB version also

**Comment by bgcngm** [comment]
JB version already includes it, since a long time.
