### ISSUE TITLE
"Gravitybox system framework not responding. Exiting"

### ISSUE THREAD

**Issue by shadilol** [GravityBox/GravityBox#1022]
Gravitybox fails to start with the message: "Gravitybox system framework not responding. Exiting".

I uninstalled the framework and re-installed , but made no difference. I also uninstalled Gravitybox and re-installed it but made no difference.

I checked "https://github.com/GravityBox/GravityBox/issues/1002", the solution to that problem was to install Gravitybox(KK) so i tried doing that but the KK apk would not work nor install.

![2014-08-20 15 56 00](https://cloud.githubusercontent.com/assets/8504698/3984201/02dc3a8e-2886-11e4-9583-c09006c64a89.png)
![2014-08-20 15 56 08](https://cloud.githubusercontent.com/assets/8504698/3984202/02dc718e-2886-11e4-8b31-2d3a8afc8403.png)

Model number: SAMSUNG-SGH-I727
Android version: 4.3.1
Root version: CyanogenMod 10.2.0 Andriod 4.3.1

**Comment by shadilol** [comment]
if you need any more information please just tell, i do not know how to get the error log if you need that just tell me how to get it.

**Comment by C3C0** [comment]
GB should not be run on custom ROMs.
Please, refer to the support thread at http://forum.xda-developers.com/showthread.php?t=2316070 for compatibility info.

**Comment by shadilol** [comment]
But i do not understand how it worked before on the same phone. And it is currently working on my friends phone who also uses the same CM rom.

**Comment by krishhna9999** [comment]
i have a solution for it but plz dont scold me if it wont works for u, it worked for me, the thing u have to do is just go to xposed installer>in that framework> in that just press soft reboot after reboot it may work, it worked for me many times
