### ISSUE TITLE
QS Tile Auto-Switch behavior buggy on MotoX

### ISSUE THREAD

**Issue by Nxt3** [GravityBox/GravityBox#1037]
I've brought this up before, and I'm sorry for being so naggy about it. I took the time to get all relevant commits to SlimKat's implementation of the behavior.

https://gerrit.slimroms.net/#/c/7236/
https://gerrit.slimroms.net/#/c/7230/
https://gerrit.slimroms.net/#/c/7231/
https://gerrit.slimroms.net/#/c/2245/
https://gerrit.slimroms.net/#/c/2275/
https://gerrit.slimroms.net/#/c/2246/
https://gerrit.slimroms.net/#/c/4301/
https://gerrit.slimroms.net/#/c/4304/
https://gerrit.slimroms.net/#/c/4582/

Having said that, do you think that it would be beneficial for you to have a Motorola RAZR M on Verizon? I have a spare one, its on v4.4 and it has it's bootloader unlocked. If you think that's something that would help further development of GravityBox on Motorola devices--let me know.

**Comment by C3C0** [comment]
Hi. I'll go through those commits as soon as I have time. Having that device would certainly help to make some compatibility adjustments but I can't give you any guarantees, though.

**Comment by Nxt3** [comment]
Well, I don't think I'll be getting the new MotoX, but I will still be sure to PM you when it comes time for me to send it to you. Should be sometime by the end of the year. I plan on switching carriers, and this phone will be useless to me.

**Comment by C3C0** [comment]
Just FYI.
https://github.com/SlimRoms/frameworks_base/commit/332afde5c805c130b27e076eeb5173ee3fad3e74#commitcomment-7831748

**Comment by Nxt3** [comment]
How are you doing it differently?
