### ISSUE TITLE
[Feature] GB action for clearing all notifications

### ISSUE THREAD

**Issue by pylerSM** [GravityBox/GravityBox#1066]
Add option (intent) to clear all notifications @C3C0 

`XposedHelpers.callMethod(mNotificationManagerService, "onClearAll");`

**Comment by C3C0** [comment]
https://github.com/GravityBox/GravityBox/commit/2de9e17fe9b7c83453e13cf33cb2017fce095cf7

**Comment by pylerSM** [comment]
Thanks
