### ISSUE TITLE
Make 'Media tweaks > Volume keys skip track' work with stock FM radio

### ISSUE THREAD

**Issue by Drugoy** [GravityBox/GravityBox#1117]
Please, make the 'Media tweaks > Volume keys skip track' feature work with stock FM radio application.
I miss this function there a lot :(

**Comment by C3C0** [comment]
This feature is for controlling media playback only and at system level. No app-specific solution can be provided.

**Comment by Drugoy** [comment]
Couldn't you make an exclusion for 'FM Radio' for it being a standard app of AOSP system?
