### ISSUE TITLE
Move setting 'Leave stock battery icon intact'

### ISSUE THREAD

**Issue by Drugoy** [GravityBox/GravityBox#1118]
I don't know what this setting does (didn't notice any difference) but it obviously relates to battery settings and thus should be moved from it's current place 'Statusbar tweaks > Statusbar colors' to 'Statusbar tweaks > Battery settings'

**Comment by C3C0** [comment]
This option is related to icon coloring and is designed to keep stock battery unaffected by coloring which means it's placed right.
