### ISSUE TITLE
Selecting CRT effect causes fade effect and vice versa.

### ISSUE THREAD

**Issue by Freedos** [GravityBox/GravityBox#1139]
It doesn't seem to be a translation issue since the string names are correctly tranlated.

**Comment by C3C0** [comment]
Tested on N5 as well as ThL 5000. Behavior is OK on these.

**Comment by mo-504** [comment]
Confirmed that behavior is working normal on N4 and N5. Using en-US for both devices.
What locale are you using @Freedos ?

**Comment by Freedos** [comment]
I'm using german translation on LG stock rom
