### ISSUE TITLE
'Signal Cluster Settings > Use Lollipop icons' incompatibility (Moto X 2013)

### ISSUE THREAD

**Issue by SocraticBliss** [GravityBox/GravityBox#1185]
I tried enabling the Lollipop icons and I rebooted a few times, but I am still seeing the stock icons

I'll try figuring out how the SystemUI configures the icons for the Moto X 2013 and see if I can provide a solution (unless you already know what the problem is)

**Comment by C3C0** [comment]
https://github.com/GravityBox/GravityBox/commit/e5845fbe9afe0634168bcbdc96000c110d00d85e
