### ISSUE TITLE
[Feature request] Change rotation lock to portrait lock

### ISSUE THREAD

**Issue by sexyunicorn** [GravityBox/GravityBox#1193]
When my phone is rotated I have to rotate back to portrait then lock which is annoying.

Tasker is able to lock in portrait so it should be possible?

**Comment by sexyunicorn** [comment]
Also on long press it goes to accessibility not display in the settings

**Comment by C3C0** [comment]
Not sure. This feature is not implemented in GB. GB only unhides native rotation lock tile that's already in Android but hidden on phone devices.
