### ISSUE TITLE
Gravity Box crashes whenever setting a cutsom lockscreen background

### ISSUE THREAD

**Issue by metp** [GravityBox/GravityBox#1220]
Gravity Box crashes if I want to set a custom lookscreen background. I've also used different images with different sizes.
Moto G Stock

**Comment by C3C0** [comment]
Logcat of crash is needed to identify the issue

**Comment by metp** [comment]
Sorry I tried it after 5 minutes again and it worked, so I can't send a Logcat

**Comment by C3C0** [comment]
OK, please, capture a logcat if it ever starts crashing again.
