### ISSUE TITLE
Alcatel onetouch Idol X 6040D (MTK6589)

### ISSUE THREAD

**Issue by MilesTeg81** [GravityBox/GravityBox#1226]
Hi 

I tried to install gravitybox on my 6040D, but I always run into bootloop.
Like mentioned in this thread: 
http://forum.xda-developers.com/android/development/rom-t2904511
my Alcatel 6040D starts into bootloop after activating the gravitybox module.
- xposed framework installed on rooted stock firmware (bootloader: rua1 CWMv5.5.0.4 for Alcatel OneTouch)
- installed version 3.5.0, reboot, activated, reboot
- everything else worked fine (e.g. xprivacy module)

Bootloops seem to be a common problem when modifying this device 
(e.g. KitKat custom rom for 6040: forum.xda-developers.com/android/development/rom-t2904511 
this also mentions how to get out of the loop)

I can't pull the log file from /data because it is not/can't be mounted.

last_log:
Starting recovery on Fri Dec 26 19:50:12 2014
can't open /dev/tty0: No such file or directory
framebuffer: fd 3 (1080 x 1920)
ioctl(): blank: Invalid argument
ioctl(): blank: Invalid argument
CWM automade 19.10.2014 17:46:37       
# recovery filesystem table

  0 /tmp ramdisk (null) (null) 0
  1 /misc emmc /dev/misc (null) 0
  2 /data ext4 /dev/block/mmcblk0p9 (null) 0
  3 /system ext4 /dev/block/mmcblk0p7 (null) 0
  4 /cache ext4 /dev/block/mmcblk0p8 (null) 0
  5 /boot emmc /dev/bootimg (null) 0
  6 /recovery emmc /dev/recovery (null) 0
  7 /sdcard vfat /dev/block/mmcblk1p1 /dev/block/mmcblk1 0
  8 /sd-ext auto /dev/block/mmcblk1p2 (null) 0

W:Unable to get recovery.fstab info for /datadata during fstab generation!
W:Unable to get recovery.fstab info for /emmc during fstab generation!
I:Completed outputting fstab.
I:Processing arguments.
I:Checking arguments.
I:device_recovery_start()
Command: "/sbin/recovery"

ro.secure=0
ro.allow.mock.location=1
ro.debuggable=1
persist.sys.usb.config=mass_storage,adb
ro.build.id=IMM76L
ro.build.display.id=full_MTK-eng 4.0.4 IMM76L eng.rua1.20130129.114933 test-keys
ro.build.version.incremental=eng.rua1.20130129.114933
ro.build.version.sdk=15
ro.build.version.codename=REL
ro.build.version.release=4.0.4
ro.build.date=Вто Янв 29 11:51:46 MSK 2013
ro.build.date.utc=0
ro.build.type=eng
ro.build.user=rua1
ro.build.host=rua1-desktop
ro.build.tags=test-keys
ro.product.model=Full Android on Emulator
ro.product.brand=Android
ro.product.name=full_MTK
ro.product.device=MTK
ro.product.board=MTK
ro.product.cpu.abi=armeabi
ro.product.manufacturer=unknown
ro.product.locale.language=en
ro.product.locale.region=US
ro.wifi.channels=
ro.board.platform=unknown
ro.build.product=MTK
ro.build.description=full_MTK-eng 4.0.4 IMM76L eng.rua1.20130129.114933 test-keys
ro.build.fingerprint=Android/full_MTK/MTK:4.0.4/IMM76L/eng.rua1.20130129.114933:eng/test-keys
ro.build.characteristics=default
ro.cm.device=MTK
keyguard.no_require_sim=true
ro.com.android.dateformat=MM-dd-yyyy
ro.ril.hsxpa=1
ro.ril.gprsclass=10
ro.adb.qemud=1
ro.kernel.android.checkjni=1
ro.setupwizard.mode=OPTIONAL
net.bt.name=Android
net.change=net.bt.name
dalvik.vm.stack-trace-file=/data/anr/traces.txt
ro.factorytest=0
ro.serialno=
ro.bootmode=unknown
ro.baseband=unknown
ro.carrier=unknown
ro.bootloader=unknown
ro.hardware=mt6589
ro.revision=0
ro.emmc=0
sys.usb.vid=0BB4
init.svc.recovery=running
sys.usb.config=mass_storage,adb
service.adb.root=1
init.svc.adbd=restarting
sys.usb.state=mass_storage,adb

I:Checking for extendedcommand...
I:Skipping execution of extendedcommand, file not found...
W:failed to mount /dev/block/mmcblk1p1 (No such file or directory)
W:failed to mount /dev/block/mmcblk1 (No such file or directory)
Can't mount backup path.

Would be nice if someone adds this incompatibility in the xda posting.

**Comment by C3C0** [comment]
Logcat taken during bootloop (using ADB) is needed to assess what's causing it. Anyway, most common issue is related to xposed resource hooks. Some ROMs are not compatible with xposed framework resource replacement system. That's why there's "Disable resource hooks" option in xposed installer app. Unfotunately, GB requires resource hooks to be enabled - it won't work with them being disabled.

**Comment by Mattek519** [comment]
I'm stuck in bootloop with the 6040A

Please help

**Comment by C3C0** [comment]
No additional info provided.
