### ISSUE TITLE
[KK] hidden battery indicator appears again on status bar after rebooting

### ISSUE THREAD

**Issue by mingtsay** [GravityBox/GravityBox#1257]
Reproduce:
1. Goto `Statusbar tweaks` > `Battery settings`
2. Set `Battery indicator style` to `None`
3. Reboot
4. The battery indicator appears again

Solution without bugfix:
1. Goto `Statusbar tweaks` > `Battery settings`
2. Set `Battery indicator style` to any but `None`
3. Set `Battery indicator style` to `None`
4. The battery indicator is hide

Device information:
OS: Android 4.4.4 (23.0.1.A.3.12 Taiwan Version)
Model: Sony Xperia Z2 (D6503)
GravityBox: v3.5.4

I don't know wether this bug is only on Sony devices or not.

Best regards,
Ming Tsay.

**Comment by Drugoy** [comment]
I can confirm this on JiaYu G4S (Andorid 4.4.2, ~AOSP shell). This really pisses me off, since I have to either have 2-3 battery indicators or disable GrBox.
