### ISSUE TITLE
[LP] Battery icon does not overwrite stock icon in 5.0.0alpha

### ISSUE THREAD

**Issue by SanderGit** [GravityBox/GravityBox#1271]
Status bar: when choosing a circle/dashed circle battery (with percent), it is placed next to the stock battery icon instead of overwriting it. Android 5.0.1.

**Comment by C3C0** [comment]
Running GB on unsupported device?

**Comment by SanderGit** [comment]
If the HTC M7 GPE is called unsupported, then yes.

**Comment by C3C0** [comment]
Can you manage to decompile SystemUI package and share it?

**Comment by C3C0** [comment]
No response. Closing for now.
