### ISSUE TITLE
[feature request] Quick setting : add a third big tile (like wifi and bluetooth one)

### ISSUE THREAD

**Issue by Bokoblin** [GravityBox/GravityBox#1279]
First, thank you for this great new update which has added quick settings. I have a request about them. Because there is enough space, can you make possible to add a third big quick setting for mobile data (for example) with touching icon do same thing (open a quick view) and touching label do nothing. It's a more logical feature because,unlike the others, wifi, bluetooth and mobile data works in the same way (on Android 5.1 : icon/arrows = quick view, label = setting app).

PS:  It's not QS but is it possible to add an icon next to brightness bar to toggle on/off adaptative brightness.

update May 6th : 

Image (better than words to explain) :
![screenshot_2014-11-26-19-49-26 - copie](https://cloud.githubusercontent.com/assets/8015512/7497936/b33bd0ca-f41d-11e4-9766-522cfd7e329b.png)

**Comment by Bokoblin** [comment]
Thank you very much for the "third big tile" that you call "dual mode". But why there is a single line with 2 darker colors instead of 3 little lines ?

**Comment by C3C0** [comment]
I didn't change anything about line scaling, yet. It's just how it's designed in AOSP right now. Change tiles per row to 4 if you want to avoid overlapping effect.

**Comment by C3C0** [comment]
Should be fixed by https://github.com/GravityBox/GravityBox/commit/dccb03b98f5e1b2edf1c76df31d2dcbd24e88d0b
