### ISSUE TITLE
Navigation bar cursor control not working with Swype

### ISSUE THREAD

**Issue by Wikiwix** [GravityBox/GravityBox#1286]
When using Swype, the curser control has not the intended behavior:
the curser switches through the word suggestions and the rest of the keyboard disappears (I guess Swype thinks a physical keyboard is connected)

Any chance of a fix?

**Comment by C3C0** [comment]
Cursor control keys use KEYCODE_DPAD_LEFT and KEYCODE_DPAD_RIGHT which are standard codes for left/right keys. It's Swype's fault intepreting them incorrectly.
https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModNavigationBar.java#L458

**Comment by C3C0** [comment]
It's the same on other Roms. E.g. http://forum.xda-developers.com/showthread.php?p=59190438

**Comment by Wikiwix** [comment]
I see. I don't remind the Xposed documentation good enough:
Any way to make the calls as Swype? So Swype thinks the command was given by itself and not from another keyboard?
I guess Swype won't change anything in its behaviour since it's actually a feature (works quite nice with a physical keyboard (just tried it))

**Comment by Wikiwix** [comment]
@C3C0 :
I have a very interesting behavior spotted:
Using the volume buttons for cursor control DOES work as intended.
So there should be a way.

**Comment by C3C0** [comment]
Which version of GB would you be willing to test? LP, KK, JB?

**Comment by Wikiwix** [comment]
LP and of course

**Comment by C3C0** [comment]
Hmm... In the meanwhile I installed Swype and tested myself. Doesn't work. Strange is that I tried the exact combination of key event flags that are used when cursor is controlled with volume keys. Still behavior is different. Seems like Swype has problems when event comes from touchscreen area...

**Comment by Wikiwix** [comment]
Actually I am not sure who sets these flags, but perhabs one of these flags is set: FLAG_SOFT_KEYBOARD, FLAG_VIRTUAL_HARD_KEY
Another difference could be the context/process in which the key is sent? (thought of this because of this flag: FLAG_FROM_SYSTEM )

**Comment by C3C0** [comment]
Already tried all possible combinations. Including the one that's used for volume keys (can be seen at line 1995 here: https://android.googlesource.com/platform/frameworks/base/+/android-5.0.1_r1/core/java/android/inputmethodservice/InputMethodService.java )
To no avail.

**Comment by Wikiwix** [comment]
How do you set the flags?

I guess the way it's done with the Volume keys (by hooking the system's imeservice) Swype doesn't even register there was an event (I just guess, don't know about the actual architecture of this/input)

**Comment by C3C0** [comment]
I found combination that works but unfortunatelly, Swype minimizes itself and shows only suggestion bar anyway... It restores itself after cursor reaches start or end of line. Really weird behavior. Also checked CM sources. They are doing it the same way.

**Comment by Wikiwix** [comment]
I am confused: what do you mean by it works, if it still has the weird behavior?
Any way to let Swype not know about the event? Or simply using the same imeservice as used for the Volumekeys?

**Comment by C3C0** [comment]
It works in such way that cursor moving works which didn't previously. But keyboard gets still minimized and shows only suggestion bar. The problem is Swype has probably some touch focus logic that hides it whenever outside touch is registered.

**Comment by Wikiwix** [comment]
The way it was, the cursor changed the suggestion (in case you did not notice)
I don't think it actually is the touch focus: Any other touch input, that does not leave the app or anything, does not change the keyboard. I think it is about a registered keyevent from another app.

**Comment by C3C0** [comment]
Previously, cursor key changed suggestion. Now it moves cursor in text field.
That's the difference in previous and current behavior.

**Comment by Wikiwix** [comment]
Yeah, I got that.
What do you think about my second part (as answer to your theory about touch focus) :

> I don't think it actually is the touch focus: Any other touch input, that does not leave the app or anything, does not change the keyboard. I think it is about a registered keyevent from another app.

**Comment by C3C0** [comment]
I don't know. Definitely looks to be related to some Swype's internal logic.

**Comment by Wikiwix** [comment]
Definitely, as it is intended for use with a hardware keyboard:
I tried it via OTG: it is actually quite nice to use the suggestions made by Swype

Could you get the imeservice used here: https://github.com/GravityBox/GravityBox/blob/lollipop/src/com/ceco/lollipop/gravitybox/ModInputMethod.java#L61
and make the corresponding calls imeService.sendDownUpKeyEvents(newKeyCode) on button press?
Perhaps a bit hacky but at least we would get more information about Swype's behaviour.

**Comment by C3C0** [comment]
I can't. I don't have a way to directly retrieve IME service from where I need it.
Another attempt would be to send some special key codes instead of DPAD ones and try to capture and handle them within IME service (similar way as capturing VOL UP/DOWN is done) but it would be too hacky, especilly when I don't know which key codes would be safe to use to not break some third party apps that might be using them.

**Comment by Wikiwix** [comment]
I thought of this workaround as well.
If you use a keycode like -13572 the chance of double usage is very unlikely (all the defined codes are positiive and smaller then 1000) and as it is still no nice option:
make this implementation an option marked as hacky

**Comment by LorneCash** [comment]
I have a Nexus 5X and I'm on GB MM v6.0.7-rev1 I'm also using the latest version of the Paid Swype app (I've also paid for the GB play store app) and I've noticed that the volume keys work fine when I use the Google Keyboard but when using Swype they just change the volume and don't move the cursor.
