### ISSUE TITLE
[LP] Expandable Volume

### ISSUE THREAD

**Issue by KeithBronstrup** [GravityBox/GravityBox#1295]
Is it possible to get the expandable volume panel back in LP? I've tired both GravityBox, which I see now lacks the option, and another Xposed module that supposedly ripped that code from an earlier version of GB, which also didn't work.

I'm assuming this was removed because it simply doesn't work under LP; is it something you're working on, or has Google made it impossible in LP?

**Comment by C3C0** [comment]
VolumePanel is changed completely in LP due to new notification priority features (a.k.a. Zen mode).
I will be probably looking into it as soon as stage of ironing out existing features for LP is over, but I am not very optimistic about it.

**Comment by KeithBronstrup** [comment]
It's not super important, more a point of curiosity as to why it disappeared from the LP version of GB. If you're able to get it working again, awesome; if not, it's completely understood why that is the case. Thanks!

**Comment by C3C0** [comment]
https://github.com/GravityBox/GravityBox/commit/efdc995ee3da6be58fd51c7675a2d42cf1ed48cb
