### ISSUE TITLE
[4.3] Put Quick Settings text on same line 

### ISSUE THREAD

**Issue by ghost** [GravityBox/GravityBox#1298]
The text below the icons in GravityBox's quick settings is not always on the same line, see the below screenshot for an illustration (look at the items with the red lines between them):  
![Screenshot (See red lines)](https://cloud.githubusercontent.com/assets/8436246/6593442/2bc91dca-c7d9-11e4-993c-bf091949d7d7.png)

This is visually jarring. Although you can try to work around this by putting items that have their on the same baseline in a row, that's not really ideal (I did already but the USB hotspot item hides when not connected, as in the screenshot).

(I am using GravityBox together with Sony's stock Android 4.3)

**Comment by C3C0** [comment]
GravityBox doesn't officially support Sony devices running Xperia system. This means some features may work, some can't and some can get unexpected results (like in the picture). It is unmanageable for me to adjust GB for every OEM system available out there. Please, refer to the support thread at XDA for more info about compatibility.
