### ISSUE TITLE
[Feature request] Enable LED in Priority/None modes

### ISSUE THREAD

**Issue by eirinnm** [GravityBox/GravityBox#1336]
One of the major complaints about Lollipop's new sound modes is there's no way to have your phone sitting on your desk at work, in silent mode (no vibrations), and have the flashing LED for notifications. 

I think the option to "enable LED in priority and silent modes" would be a nice addition to GB.

**Comment by C3C0** [comment]
https://github.com/GravityBox/GravityBox/commit/d581036579c11239eb300dff76c55424cd6d7a8a
