### ISSUE TITLE
[Feature request] Network traffic, volume, battery saver, heads up + [issues]

### ISSUE THREAD

**Issue by Bokoblin** [GravityBox/GravityBox#1337]
Features: 
- Network Traffic : Please add an option to display it in bits/s because it's currently only displayed in Bytes [updated]
- Battery Saver : option to just color status or navigation bar
- Heads Up : option to force heads up to stay x secondes because some stay during half a second (I don't know why)
- issue #1279 : I've added a screenshot of what would be awesome if implemented, but I don't know if it's possible.

update 8/05
Thanks for having implemented them in 5.0.10 : 
- Media volume by pressing expanded button like in the NXROM (image 1)
- replace icon of delete screenshot by the new materialised one (image 2)    (but not the good icon)

![screenshot_2015-05-03-11-19-51](https://cloud.githubusercontent.com/assets/8015512/7444714/724fa2aa-f191-11e4-87ba-0bb8a98b541d.png)
![screenshot_2015-05-03-11-31-08](https://cloud.githubusercontent.com/assets/8015512/7444716/772c7cc6-f191-11e4-8de0-2841c0bdd154.png)

**Comment by C3C0** [comment]
Regarding traffic meter. It uses B/s ; KB/s ; MB/s units (bytes, not bits). If you are seeing different units then it's most likely an error in localization for language you use. What language do you use?

**Comment by Bokoblin** [comment]
It show me for instance, 760Ko/s while downloading a game on Play Store but it's in reality ~7MBytes/s so I would like it to display that in MB.
In France bits = bits and Bytes = octet .but I just want this to be displayed in Mega instead of Kilo

**Comment by BokoblinXDA** [comment]
It's the same thing because in France bits = bits and Bytes = octet .but I just want this to be displayed in Mega instead of Kilo

**Comment by C3C0** [comment]
760Ko/s == 760KB/s ? it's 760 kilo byte per second, not 7 mega byte per second. Are you sure you are actually downloading in that speed?
Also did you try comparing if both traffic meters (standard/omni) are giving you the same results? I checked the formatting function which formats speed+unit and it seems fine to me.
- B/s for speed less than 1 KB/s
- KB/s for speed less than 1 MB/s
- MB/s for speed less than 1 GB/s

**Comment by C3C0** [comment]
This is how it looks like whem I'm downloading with speed more than 1 megabyte per second:
![network_traffic](https://cloud.githubusercontent.com/assets/1543473/7493199/ea681d02-f3fe-11e4-9606-46c128b58cd2.png)

**Comment by Bokoblin** [comment]
I checked. So I never noticed that my ISP give me until 8 Mbits/s  and not 8MBytes/s like I thought . It's probably because sometimes they put a B instead of b (not different in France because we say octet for bytes like I said before). Sorry for the mistake.
OK, so can we have an option to choose too bits/s instead of Bytes/s (it will be more relevant) ?

**Comment by tonyp** [comment]
@BokoblinXDA Bytes are more relevant than Bits in the real world when displaying file transfer speeds.
ISPs just use Mbit (rather than MB) for marketing purposes to create exactly that misconception you fall for -  but usually download and upload speed is measured in MB/s or KB/s. 
You can verify this with downloads in Chrome and Firefox for example.

As this issue already got hijacked for some more ideas I'll follow suit (the issue number is just awesome btw!): 
I think an option to hide the alarm volume from the expandable panel might be a good addition, as it's rarely ever needed.

**Comment by Bokoblin** [comment]
@tonyp Thanks, but I haven't really understood the sentence "As this issue already got hijacked for some more ideas I'll follow suit (the issue number is just awesome btw!): "

**Comment by tonyp** [comment]
Oh, sorry. That was just a way of saying that I'll add another suggestion to this issue rather than creating a new one. And #1337 is leet, not as nice as 42 but still (just some computer science jokes).

**Comment by Bokoblin** [comment]
Oh okay. (+ Understood too for 42 ^^)
