### ISSUE TITLE
[GB 5.1.0] Battery percentage indicator is misplaced

### ISSUE THREAD

**Issue by ShiroiKarasu6991** [GravityBox/GravityBox#1342]
As the title says, if the battery indicator is activated, it will appear a bit off, as seen [in this screenshot.](https://cloud.githubusercontent.com/assets/7461491/7671797/7343ac4c-fcb3-11e4-9d24-3bfe117100c0.jpg)

I have discovered that the reason is wrong padding (the statusbar indicator is using the same dimensions as the keyguard and expanded header indicators). And since the indicator is shown to the left of the icon, this misplacing occurs (would not be the case if the indicator were shown to the right). Device tested is a 2013 Moto G running AOSP 5.1.1.

Dimensions are as follows (inside SystemUI/res/values/dimens.xml):
`<dimen name="battery_level_padding_end">2.0dip</dimen>`
`<dimen name="header_battery_margin_keyguard">6.0dip</dimen>`

Setting these values, respectively, to `6.0dip` and `-2.0dip`, fixes this.

Source: I manually implemented this mod in my SystemUI.apk and I was having the same bug. Fixed it using the values I mentioned above. Also had to create two new `dimen` values for the battery indicator `TextView` to use.

**Comment by C3C0** [comment]
https://github.com/GravityBox/GravityBox/commit/e1f5fbbb974f0422a13453b5b94afe480a41ea87

**Comment by ShiroiKarasu6991** [comment]
Thanks! And sorry for the long report.
