### ISSUE TITLE
cell radio toggle is missing

### ISSUE THREAD

**Issue by dmatora** [GravityBox/GravityBox#1343]
This application can toggle cell radio https://play.google.com/store/apps/details?id=the.radioshutoff
GravityBox doesn't
Can you please implement it?

**Comment by C3C0** [comment]
There are already 2 ways:
- using long-press on cellular tile (configurable in tile specific settings)
- using GravityBox action - can be used in many ways - launcher shortcut, gb app launcher shortcut, custom tile, tasker, etc...

**Comment by C3C0** [comment]
You mean radio, not mobile data. I see. Well, there's no reason to have that in GB if it can be achieved by already existing app.

**Comment by dmatora** [comment]
well, i am using it on android smartwatches (jelly bean)
on smartwatches, having to launch an app and then switch back to original app is a major issue
unlike triggering it from pull down bar, that doesn't require resources

**Comment by dmatora** [comment]
and i can't see cell radio management on tasker or secure settings

**Comment by dmatora** [comment]
I can see i can add gravity action, but i can't see a way to add additional tasks to gravity action

I've created two tasker tasks, for enabling/disabling cell radio (through better airplane mode app plugin).
But i can't see any way to add them into GB
is there?

**Comment by dmatora** [comment]
ok, so, if i produce a pull request for standalone cell toggle, can i expect it to be merged for jelly bean?

**Comment by C3C0** [comment]
It will be reviewed. But I can't guarantee it'll actually get merged. Depends if you can provide generic -  device independent solution. Note that jellybean version is the most mediatek-friendly amongst all GB branches.
