### ISSUE TITLE
Allow selection of which System bars are orange in battery saver mode

### ISSUE THREAD

**Issue by Wikiwix** [GravityBox/GravityBox#1344]
It would be nice to have the navbar orange but keep the statusbar as it is:
With the available option one either has no indicator or the interface is strongly changed.
But if only the navbar is colored the apps keep there style (including colored/transparent statusbar) while still having a strong indicator for battery saver mode

**Comment by C3C0** [comment]
For me, notification icon (battery with + sign) is enough to know battery saver is on. UI responsiveness is another indicator :)

**Comment by Wikiwix** [comment]
That is right, but I would prefer the less subtile indicator, since my first thought, when the phone is unresponsive, is that there is something wrong...
