### ISSUE TITLE
Ringer Mode QS

### ISSUE THREAD

**Issue by tonyp** [GravityBox/GravityBox#1346]
I noticed that you're using a hack to bring back the ringer mode toggle function, introduced here: https://github.com/GravityBox/GravityBox/commit/a372a7270a823c44a84ead493214681dc20783ae

A couple weeks ago I wrote a very simple ringer mode widget and stumbled upon the same problems with Lollipop as you. Apart from the fact they replaced the default silent mode with the priority one, setting the mode to RINGER_MODE_SILENT fails with unexpected results.

According to [Google](https://developer.android.com/about/versions/android-5.0-changes.html#BehaviorNotifications) it should work:

> Setting the device to `RINGER_MODE_SILENT` causes the device to enter the new priority mode. The device leaves priority mode if you set it to `RINGER_MODE_NORMAL` or `RINGER_MODE_VIBRATE`.

After a lot of Googleing I found the reason. Due to a bug you need to set the Ringer Mode to silent twice (as I wrote a widget I had to find a fix within the standard API and couldn't rely on Xposed).

So this is how I worked around it. I call `audioManager.setRingerMode(AudioManager.RINGER_MODE_SILENT)`, then start a new Thread with `Thread.sleep(100)` and call it again. Works like a charm.

I believe this solution might be better as it uses the Android API and thus should be more compatible.

**Comment by C3C0** [comment]
Thanks for info. Ringer mode tile was brought back by romracer. It works just fine so I don't see any benefits in using something that's just another (but different) workaround :)
Let's wait for Google to fix that annoyance.
