### ISSUE TITLE
[JB] Some menu items missing?

### ISSUE THREAD

**Issue by IzzySoft** [GravityBox/GravityBox#1349]
I'm using an LG P880 (Optimus 4X HD) with its latest stock ROM (Android 4.1.2). Installed the latest (stable) Xposed, and also the latest GB.

I miss several menus I've seen in various tutorials, mainly the "Lockscreen tweaks"; on my device, the top-most item is "Statusbar tweaks" (according to several articles and videos, e.g. [Gravity box(jelly bean) walkthrough](https://www.youtube.com/watch?v=WSeVnHnSoZk), "Lockscreen tweaks" is listed on top of that usually). That video also shows a "Quicksettings" item in the "Statusbar tweaks" missing on my device – which lets me assume GB might "hide" things simply not available to the given device/Android version (those Quicksettings were AFAIR introduced with 4.2 or 4.3 – I have those "tiles" on my 4.3 device, but not on the 4.1 P880), which sounds absolutely plausible.

Am I correct with my assumption, and things like the "Lockscreen ring" are simply not possible on 4.1 – or is this anything that "can be fixed"? (If I'm right, that "hiding" feature might be useful to be mentioned in the initial post on the corresponding XDA thread. I've checked that as well as the open and closed issues here to make sure not asking a "duplicate question" – but you hopefully will forgive me not having scanned all the 885 pages of the thread at XDA :innocent:)

Thanks in advance – and thanks for this great module!

**Comment by C3C0** [comment]
Lockscreen features and quick settings in GB are not available in android 4.1. There may be other features missing but those 2 are the major ones.

**Comment by IzzySoft** [comment]
Thanks a lot for the fast response! Still a great mod :)
