### ISSUE TITLE
hardware key behaves odd after locking the phone with it 

### ISSUE THREAD

**Issue by serj111213** [GravityBox/GravityBox#1360]
I got an elephone p6000. I've set holding home button to locking my phone function. When I unlock the phone after locking it up this way, the home button doesn't respond to the first tap. But when I tap it for the second time, it works. This is pretty annoying though. When I use the locking button on the side, the home button works fine.

**Comment by C3C0** [comment]
There's already a workaround for this anomaly but this workaround is in effect only for soft keys (navigation bar). Unfortunately, I don't know how similar workaround could be made for HW keys as I don't have any Lollipop device that has HW keys.

**Comment by atcharatip** [comment]
Atcharatip9035@gmail.com

_Sent from my HUAWEI BLL-L22 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
