### ISSUE TITLE
Feature request: Custom media volume steps

### ISSUE THREAD

**Issue by TheNetStriker** [GravityBox/GravityBox#1366]
Would it be possible to set a custom volume step count? I'am using Logitech UE Boom speaker which have 32 volume steps. Gravity Box always sets 30 steps. It would be perfect if the volume steps are equal.

**Comment by C3C0** [comment]
https://github.com/GravityBox/GravityBox/commit/332f9a10ca337db3c7dadfcceb3cf91074d1b430
