### ISSUE TITLE
[Feature request] Expanded Location QS tile

### ISSUE THREAD

**Issue by Bokoblin** [GravityBox/GravityBox#1371]
Hello, I have sawn that in Cyanogen 12.1, the location tile can be expanded to display a toggle and 3 radio buttons : High Accuracy, Battery saving and Device only. Is it possible to make it via your module ?

**Comment by C3C0** [comment]
Use Location tile (SlimKat style) for more control.

**Comment by Bokoblin** [comment]
Yes , I already use it, it is great.
Btw, the icon is a bit pixelated.
