### ISSUE TITLE
[Request] Play a Sound when clicking the "Cursor control keys" arrows

### ISSUE THREAD

**Issue by wernerml** [GravityBox/GravityBox#1377]
(under: "Navigation bar tweaks")
just like the Keyboard does!

I don't know if this could be universal (for every ROM)
here it's: /system/media/audio/ui/KeypressStandard.ogg

**Comment by C3C0** [comment]
Cursor control keys are not connected with the keyboard in any way. Their behavior is in line with other navigation bar keys, including haptic feedback and touch sounds.
