### ISSUE TITLE
Redistribution restriction

### ISSUE THREAD

**Issue by ghost** [GravityBox/GravityBox#1379]
The README and the NOTICE file says:

> You may not distribute nor sell this software or parts of it in Source, Object nor in any other form without explicit permission obtained from the original author.

However, [Section 4.d.](https://www.apache.org/licenses/LICENSE-2.0#redistribution) of the Apache License explicitly states:

> The contents of the NOTICE file are for informational purposes only and do not modify the License. 

Therefore, it is not legally binding. I suggest you remove that altogether, as you cannot say it's licensed under the Apache License if you place additional restrictions on the licensees.

**Comment by C3C0** [comment]
Yes, I'm aware of it. This was added as a result of me being mad because of project being put in the play store as paid app by one individual. It has no real effect on license alone, though.
