### ISSUE TITLE
Option to show seconds in statusbar clock

### ISSUE THREAD

**Issue by eMPee584** [GravityBox/GravityBox#1382]
..not there, is it? Yes, battery drain. But useful :grinning:

**Comment by C3C0** [comment]
Such feature is not planned as I don't see any benefits that would outdo drawbacks such as higher CPU usage and status bar clutter.

**Comment by eMPee584** [comment]
I know the drawback. I would still like to show elapsing seconds in the status bar. It does have use cases.

On October 23, 2015 9:33:15 AM CEST, C3C0 notifications@github.com wrote:

> Such feature is not planned as I don't see any benefits that would
> outdo drawbacks such as higher CPU usage and status bar clutter.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/GravityBox/GravityBox/issues/1382#issuecomment-150497530

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
