### ISSUE TITLE
Navigation bar disappears after installing GravityBox - LP 5.1

### ISSUE THREAD

**Issue by dragonnn** [GravityBox/GravityBox#1387]
On two or more ROM-s with I have tested on my Xperia Z (LP 5.1 AOSP base) after installing GravityBox the nav bar is hidden (clean install, no settings changed in GravityBox) i need to go every boot in ROM settings, disable and re enable the nav bar. If any logs are need I will attach them.

**Comment by C3C0** [comment]
I've seen this in the past and already tried to do some precautions. This is caused by conflict between a ROM and GravityBox. It's impossible to cover all different ROMs out there.
