### ISSUE TITLE
[MM Feature Request]  QS: Battery tile, SlimKat location tile

### ISSUE THREAD

**Issue by Bokoblin** [GravityBox/GravityBox#1405]
Hello, 
Here are some suggestions : 
- Battery : Add an option to hide percentage and voltage (I only wan't to use it to toggle battery saver). And thus replace orange coloring indicator by the stock icon for battery saver 
  (battery with a '+' inside).
- SlimKat location: Replace KK- style icons with LP+ one (wifi icon not broken in 4 pieces).
  The following attached file might be invisible :
  ![ic_qs_location_on_wifi](https://cloud.githubusercontent.com/assets/8015512/11284398/c41bcc60-8f09-11e5-93ec-bc1e60439077.png)

NB: Can you make possible to edit QS directly in system UI Tuner thanks to GB ?

**Comment by Bokoblin** [comment]
Now there is an official API for QS, will you release a root app that use it for the QS that where on GravityBox ?

**Comment by C3C0** [comment]
No. QS management in GravityBox is not just about tiles. There are other features that can't be done without xposed framework. And AFAIK, there already is an app for custom QS tiles.

**Comment by Bokoblin** [comment]
Yep I have the app in question but certain QS were only in GB and for the
moment the dev hasn't said anything about N and his app

---

**Comment by C3C0** [comment]
The fact is, some tiles are so complicated that they can be done using xposed only. QS API has its limitations.

**Comment by Bokoblin** [comment]
It's what I thought too for some tiles like compass. What are the
limitations of the API ?

---

**Comment by C3C0** [comment]
You can't change layout, order, tiles per row, cannot provide detail views, change standard tile behavior, just to name a few.
