### ISSUE TITLE
[MM][Feature Request] Activate Now on Tap with Pie?

### ISSUE THREAD

**Issue by wardellbagby** [GravityBox/GravityBox#1406]
I've looked around and I can't find a good way of doing it without creating my own Xposed module. From what I can tell, the StatusBarService has a method called getAssist() that starts the currently set Assist App (which for everyone is still Now on Tap.) 

I could be wrong about this as I haven't tested it out, but I believe that this is what the code is saying.

**Comment by C3C0** [comment]
Already fixed for the next version.
https://github.com/GravityBox/GravityBox/commit/07270abdb474d0c85a55a48b0720abce9d1379d0

**Comment by wardellbagby** [comment]
That's beautiful. Thanks for the quick reply!
