### ISSUE TITLE
Setting the statusbar color is no longer possible [LP]

### ISSUE THREAD

**Issue by ghost** [GravityBox/GravityBox#1427]
In the earlier GB versions the statusbar color could be changed (Statusbar tweaks > Statusbar colors). Now only the icon color can be modified and it's not a very useful setting.
Is it possible to get the setting back since some may prefer monochrome statusbar background color?

![turn-on-status-bar-color-settings](https://cloud.githubusercontent.com/assets/14923168/11827975/f32595ba-a398-11e5-9973-3013c661f04a.jpg)

As far as I'm aware, there's not a single (open source) Xposed module that is able to do this.

**Comment by C3C0** [comment]
This feature is obsolete in Lollipop as it would conflict with system's native per-app coloring. It's up to the developers how they design their apps and what colors they choose for status bar within their apps. Let's respect that.
