### ISSUE TITLE
Global vibration control

### ISSUE THREAD

**Issue by ghost** [GravityBox/GravityBox#1436]
Total control of vibration would make GB even more comprehensive. Currently I'm using [Vibration Tuner](http://repo.xposed.info/module/ztc1997.vibrationtuner) module for this purpose (I have disabled vibration, strength at 0%). Some apps may "abuse" the phone vibration by using it constantly, often there's no way to turn the feature of in the app settings. 
The best solution would probably be to allow controlling the vibration mechanic globally and/or on per-application basis. 'Ultimate Notification Control' only manages the notifications.

**Comment by ghost** [comment]
@C3C0 This feature has now been implemented, but seems to be behind a paywall. Just to confirm, can I unlock premium features by donating, without GApps installed?

**Comment by C3C0** [comment]
This feature is part of ultimate notification control as it replaced option for disabling haptic feedback vibrations. You can use PayPal instead of Google play. Or compile your own version with limitations disabled

**Comment by C3C0** [comment]
Closed by https://github.com/GravityBox/GravityBox/commit/6cd592c56022a1b30bdaca6482848027fbe9c91e

**Comment by ghost** [comment]
@C3C0 I think this feature doesn't work.
- version `v80-sdk23-arm` of  the Xposed framework
- Android 6.0.1
- OnePlus One
- the latest version of GravityBox [MM]
- XPrivacy and Android app permissions are disabled for GB

`Default settings` is enabled and I have selected `override vibrations`. `Vibration pattern` is set to `0`. I did also experiment with `disable sound to vibration conversion`. `Replace original vibration` shouldn't have effect.

**Comment by C3C0** [comment]
Please, specify the exact scenario (what app, etc.). Also note, that "Default settings" apply only for those apps that don't have their own explicit UNC settings

**Comment by ghost** [comment]
> Please, specify the exact scenario (what app, etc.).

@C3C0 Doesn't work at all with Google Maps, QKSMS, AOSP keyboard, Android system. No vibrations are blocked. Before rooting my device vibration was driving me mad and I exactly remember when those apps use vibration.

> Also note, that "Default settings" apply only for those apps that don't have their own explicit UNC settings

I don't use UNC, no settings in use. Vibration Tuner module blocked everything when global vibration was disabled, I used it for over six months, but doesn't work on this version of Android.

**Comment by C3C0** [comment]
Please note, that Vibration control in Ultimate notification control default settings or per-app settings are related to notifications only and they won't affect other types of vibrations that are done directly via vibrator service (e.g. google keyboard) as such vibrations have nothing to do with notifications. Blocking vibrations completely at device level is available only within Quiet hours feature.

**Comment by ghost** [comment]
@C3C0 That's a bit confusing to me. Can I enable "quiet hours" at all times and only block vibration, without any other changes?

**Comment by C3C0** [comment]
No as the main purpose of Quiet hours is to make device silent which means audio for notifications is muted implicitly. There is currently no other feature that could disable vibrations at device level apart from option in Quiet hours.

**Comment by ghost** [comment]
[VibrationTuner](http://repo.xposed.info/module/ztc1997.vibrationtuner) has now been fixed for Android 6, if others are looking for a way to 100% disable vibration this module does the job.
