### ISSUE TITLE
Recent Tasks / App switcher re-replacement?

### ISSUE THREAD

**Issue by eMPee584** [GravityBox/GravityBox#1439]
Some OEMs do strange things to SystemUI.. Leagoo has replaced the LP app switcher with some very inferior icon-only version, and it doesn't look good, too. Now is it possible to hook in there and replace it with .. the original LP switcher? or others, like omniswitch?

**Comment by GijsTimmers** [comment]
This may very well be caused by an app Leagoo installed before sending the device to you. I had a similar issue on my phone. My app switcher was kind of funky too. I resolved it by removing some pre-installed apps, located in `/system/app`. Create a backup so you can always roll back.

**Comment by eMPee584** [comment]
.. btw no, tried removing/disabling all the strange bloat shrapnels.. it seems they modified the framework files.
