### ISSUE TITLE
Data activity inidcators broken on Moto G 2015 Marhsmallow

### ISSUE THREAD

**Issue by nicedream06** [GravityBox/GravityBox#1452]
Since the upgrade to Marshmallow, the network activity indicators no longer work on my Moto G 2015 (model number XT1540) .

The Xposed log gives the following error:
E/Xposed  ( 3573): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.systemui.statusbar.policy.MotorolaNetworkController.SignalCallback

Using DexDump I can see that the standard NetworkController.SignalCallback class appears to be included (see attached screenshot).  So if GravityBox used that call instead it may work.
![screenshot_20160120-144828](https://cloud.githubusercontent.com/assets/2739517/12461127/4335b9ba-bf85-11e5-9bce-9e7bf20213e9.png)

**Comment by C3C0** [comment]
Thanks for info. Well, different class name is most likely not the one and only issue. It would be necessary to check how signal callback functions look like. Specifically setWifiIndicators and setMobileDataIndicators and theit parameters. If you can provide me with decompiled SystemUI I would be able to check and possibly make necessary adjustments.

**Comment by nicedream06** [comment]
I will try to decompile the SystemUI APK - how can I submit it to you?

**Comment by C3C0** [comment]
Any news about decompiled SystemUI?

**Comment by njascgil** [comment]
@C3C0 
Do you still need this decompiled SystemUI? (I think I'm having the exact same problem described by the OP on my Moto G 2014 with Marshmallow - Android 6 and GB v6.1.1)

**Comment by C3C0** [comment]
Yes, that could help.

**Comment by njascgil** [comment]
I couldn't figure how to attach a zip file... Please try this link:
https://www.dropbox.com/s/s565marrugaq4nl/SystemUI_decoded.zip?dl=0

apktool reported a few warnings, but everything seems fine to me. I hope this is what you require.

**Comment by C3C0** [comment]
Link worked. ZIP seems to be OK. Thanks.
