### ISSUE TITLE
"Use Larger icons" doesn't seem to work in landscape

### ISSUE THREAD

**Issue by mirlww** [GravityBox/GravityBox#1471]
"Navigation bar tweaks" -->"Use Larger icons" doesn't seem to work in landscape.
GravityBox version : 6.0.5
Device : Nexus 6 - 6.0.1 - MMB29Q
Xposed : version 80﻿

![screenshot_20160219-213600 3](https://cloud.githubusercontent.com/assets/11570039/13237477/6234682e-da07-11e5-9ca5-06166eca233d.png)
![screenshot_20160219-213608 3](https://cloud.githubusercontent.com/assets/11570039/13237478/63717768-da07-11e5-9562-3de2beb9874c.png)
![screenshot_20160219-213754](https://cloud.githubusercontent.com/assets/11570039/13209089/b484da62-d95a-11e5-9da9-2b6bad2568a1.png)
![screenshot_20160219-221848 2](https://cloud.githubusercontent.com/assets/11570039/13209091/b8112672-d95a-11e5-8e09-d0f86d71efbc.png)
![screenshot_20160219-215538 2](https://cloud.githubusercontent.com/assets/11570039/13209092/b93118b4-d95a-11e5-883f-84ea7a27e34a.png)

**Comment by C3C0** [comment]
Needs to be reworked for 6.0.1. All sysbar alternative icons need to be replaced with the different ones, derived from the originals.
