### ISSUE TITLE
Navigation keys actions: Double-tap actions for Back and Recents

### ISSUE THREAD

**Issue by creeve4** [GravityBox/GravityBox#1472]
Double-tap actions for the Back and Recent buttons do not work for me. No matter how quickly I double-tap, the single tap action is just toggled twice. 

Setting a double-tap action for the Home button does work for me.

Nexus 5, stock 6.0.1

**Comment by C3C0** [comment]
For full action support on the soft keys you have to enable navbar tweaks. There's an info dialog telling that when you access key actions section for the first time.

**Comment by C3C0** [comment]
For full action support on the soft keys you have to enable navbar tweaks. There's an info dialog telling that when you access key actions section for the first time.

**Comment by creeve4** [comment]
I have Navbar tweaks enabled.

For full action support on the soft keys you have to enable navbar tweaks.
There's an info dialog telling that when you access key actions section for
the first time.

**Comment by creeve4** [comment]
This bug occurs when the double-tap speed is set to 100 ms. If I set it to
150 or higher, double-tap actions work for the Back and Recent buttons.
Interestingly, at 100 Ms, double-tap still works for the Home button.

**Comment by C3C0** [comment]
Home key has native double tap support since Android 4.3. Speed in GB applies to non-native only. 100ms is too short, you have to be very fast.

**Comment by creeve4** [comment]
Thank you for the explanation.
