### ISSUE TITLE
Feature Request - multiple users icon

### ISSUE THREAD

**Issue by lenisko** [GravityBox/GravityBox#1476]
Without **XposedMultiUsersModule** there is no chance to get multiple users on this device:
Lenovo TAB 2 A10-70L (LENOVO), Android version 5.0.1 (SDK 21)

Still using it, is not enabling _Fast switch user icon_ which is near settings button here https://i.imgur.com/ejGEU9N.png. Author was trying to get this icon back, but right now is out of ideas. 

Maybe someone here know how enable this icon on lenovo eco tablets?

**Comment by C3C0** [comment]
I'm sorry but I can only support devices running pure Android or those I physically own. It is not manageable for me to support devices for which I can't do testing and debugging myself.
