### ISSUE TITLE
Option to turn off vibration after fingerprint verification

### ISSUE THREAD

**Issue by pylerCM** [GravityBox/GravityBox#1488]
Just hook: https://github.com/android/platform_frameworks_base/blob/d89b76a58dcffa7dbc5974d14c7914f44233bef3/services/core/java/com/android/server/fingerprint/FingerprintUtils.java#L75

**Comment by C3C0** [comment]
Thanks. This is planned. Feature will need to support possible combinations, knowing the diversity of the users we have :) This means we need a multichoice preference which would allow a user to specify which vibrations to disable: - authentication Error/Success, or both.
