### ISSUE TITLE
Feature Request - translation

### ISSUE THREAD

**Issue by burunduk** [GravityBox/GravityBox#1492]
Maintain translation on one of the platforms: weblate, transifex, crowdin, etc.

**Comment by C3C0** [comment]
Well, I barely have time for development, let alone searching for an alternative way of translation management, which would be free to use for our purpose. Maybe some day I'll take a look.
Thanks for pointing out.

**Comment by pejakm** [comment]
It should be relatively easy and straightforward to use https://hosted.weblate.org/ as a translation platform.

**Comment by gaich** [comment]
github option is better. Do not move the translations from here, if you don`t want them to be spoiled bya crowd of people thinking Google translate usage made them real translators.

**Comment by gaich** [comment]
github option is better. Do not move the translations from here, if you don`t want them to be spoiled bya crowd of people thinking Google translate usage made them real translators.
