### ISSUE TITLE
[Feature Request] Disable quicksettings on lockscren

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1497]
It would be nice if we could choose which Tile would be available in lockscreen.

**Comment by C3C0** [comment]
Which branch? There's already such functionality in lollipop and marshmallow versions.

**Comment by jsalatiel** [comment]
Thanks, i haven't seen that before !
btw, is this the right place to feature requests ?

**Comment by C3C0** [comment]
Official space for feature requests is within respective project thread at XDA. E.g. for MM branch: http://forum.xda-developers.com/devdb/project/?id=12595#featureRequests
I'm not against posting the requests via github but it should be indicated clearly which branch of the project request applies to.
