### ISSUE TITLE
Block ongoing notification does not work for all apps

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1503]
I have noticed that "block  on Going Notification" does not work for some apps. For example, lightflow.
Everytime i restart lightflow, a new entry called lightflow appears on list and if i select , on the next restart, there will be a new one and lightflow wont be blocked.

**Comment by C3C0** [comment]
Notification blocker collects notifications based on their IDs. If lighflow uses random IDs for a notification on each start, then there is nothing to be done, unfortunately.

**Comment by jsalatiel** [comment]
Wouldn't be possible match using the appname ? For example, all entries in notification blocker appears as "Light Flow".

**Comment by C3C0** [comment]
Well, this feature was designed to allow per-notification control, not per-app control.

**Comment by jsalatiel** [comment]
Maybe a new setting for per app ultimate notification control?

**Comment by c89williams** [comment]
Ever since Android 4.1 there has been a native option to block all notifications on a per-app  basis. Does that not work in your case? I just tried it with Light Flow and it worked fine.

**Comment by jsalatiel** [comment]
Not really. When i block lightflow using the native "block all notifications", lightflow wont be able to control light colors, show toasts , etc .. So it will loose basically its features.  So i think a "per app" "block ongoing notification" inside the ultimate notification control would do the job just fine.
I dont know how you handle internally the current "block ongoing notifications", but i have tested Toasts and LED blinks in "tasker" and they work just fine even when the ongoing notification is blocked by gravitybox. ( they dont work when using native android block)
Of course this would be a new feature and should not interfere with the current "ongoing -  applies also to ongoing notifications when enabled" that already exists in U"ltimate Notification Control"

**Comment by C3C0** [comment]
This is because Android's blocking feature blocks notification completely at notification manager level. GravityBox blocks it at status bar level so notification is still there but not visible in status bar shade.

**Comment by jsalatiel** [comment]
Well, thats great ! Do you think it worths to add this new feature in ultimate notification control?
