### ISSUE TITLE
[Feature Request - MM] Bring back the default shortcut to "assistance request"

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1527]
Up to lollipop, assistance request could be toggled by swiping up the virtual home button. Starting in to MM, you are force to push and hold home button to toggle assistance request. Would it be possible revert the old shortcut ?

**Comment by C3C0** [comment]
That was a feature of SearchPanelView component of a navigation bar that has been completely removed in Marshmallow and replaced with Now on Tap which has completely different design and behavior.

**Comment by jsalatiel** [comment]
Wouldn't be possible emulate the behaviour when navigation bar is enabled in gravity box ?

**Comment by C3C0** [comment]
Not without putting essential components back into the system, which is not a trivial task via xposed framework.
