### ISSUE TITLE
System UI has stopped working

### ISSUE THREAD

**Issue by mx4k** [GravityBox/GravityBox#1538]
With the latest update on the  nVidia Tablet there is a "System has stopped working" error when swichting to landscape mode with gb activated. Would you pls fix that?

**Comment by C3C0** [comment]
Please, provide logcat of a crash.

**Comment by mx4k** [comment]
--------- beginning of main
W/IInputConnectionWrapper(15158): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(15158): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(15158): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(15158): getTextAfterCursor on inactive InputConnection

**Comment by C3C0** [comment]
?? This does not say anything about SystemUI crash.
Way to capture logcat
- start logging
- trigger system UI restart
- stop logging
  Then post contents of a log. Try to attach as file or use pastebin.com or similar

**Comment by mx4k** [comment]
I'm sorry for the unproper log. 
Here is a better one: http://pastebin.com/31rDcBSA

**Comment by C3C0** [comment]
I don't see a crash that could be related to GravityBox. Try to disable all other xposed modules apart from GravityBox to see if crash is still there or not.

**Comment by mx4k** [comment]
I disabled all the other xposedmodules and created a new logcat. 
http://pastebin.com/FmHjzH5A

**Comment by mx4k** [comment]
So, this logcat wasn't good either?

**Comment by C3C0** [comment]
Try disabling "Expandable volume panel" in Media tweaks. This is the only feature that could be related to crash.

**Comment by C3C0** [comment]
No additional info provided
