### ISSUE TITLE
[Feature request] Hold power with locked screen to turn on flashlight

### ISSUE THREAD

**Issue by Schlonky** [GravityBox/GravityBox#1539]
I noticed that the MM version har a lockscreen shortcut for the flashlight, but the only option is "Longpress Home", which is impossible on the Nexus 6 as I don't have a home-button. I remember running some custom rom at some point that had an option to longpress the power-button when the screen was on, to turn on the flashlight. Would this be something that could be implemented, or is it already implemented and am I just blind? :)

**Comment by C3C0** [comment]
GravityBox currently does not support power key long-press actions and I can't give you exact time frame when it will. Anyway, there is another possibility -  you can use Lockscreen tweaks / Shortcuts to define shortcut directly in lock screen which uses GravityBox Torch action.
![screenshot_20160418-100232](https://cloud.githubusercontent.com/assets/1543473/14597436/f1139f68-054c-11e6-9def-a638521ce421.png)

**Comment by Schlonky** [comment]
Didn't even think about that, thanks!

Leaving it open in case there's updates on it.
