### ISSUE TITLE
[bug] [MM] Several NoSuchMethodErrors and missing tiles in QuickSettings on Sony ROM

### ISSUE THREAD

**Issue by corrupt** [GravityBox/GravityBox#1543]
On the latest Sony MM ROM for Z5C (suzuran) the quicksettings module throws two tile-related errors (see [log.txt](https://github.com/GravityBox/GravityBox/files/240237/log.txt)). These appear somewhat randomly in my logs, always both at once.

Several QS tiles also disappear for me. The QS panel displays as configured right after a reboot. That lasts for a few minutes at max and then several tiles disappear. The ones I've noticed so far are Location, NFC and Data Roaming. I've attached two screenshots, once showing the intended layout right after boot (first image), the other showing the layout with missing tiles.

![intended](https://cloud.githubusercontent.com/assets/365169/14882710/47108ab2-0d3a-11e6-993d-35e2c0ced881.png) ![missing](https://cloud.githubusercontent.com/assets/365169/14882714/4c756482-0d3a-11e6-82b1-2d0eae3fb4a0.png)

The only exception showing up in the logs at that time is [this](https://github.com/GravityBox/GravityBox/files/240285/log2.txt) which doesn't appear to be related. Otherwise the log is silent.

Unfortunately I cannot say whether this is a regression as I've just started using the GravityBox' QS settings. 

Full xposed [error log](https://github.com/GravityBox/GravityBox/files/242719/error.log.txt)

**Comment by C3C0** [comment]
Note that Xperia devices are not officially supported as I don't own any of them which means it's impossible for me to make a 100% compatible xposed module. The same situation is for other brands that have own mods on top of pure Android. Sometimes I make a small adjustments based on logs I receive but such development is cumbersome and with unclear results.
If you could provide me with decompiled SystemUI.apk I would be at least able to add support for Xperia specific tiles (those that are made by Sony and are not part of AOSP) which would at least enable controlling their visibility and order via GravityBox

**Comment by corrupt** [comment]
I'm aware that Sony isn't officially supported, no worries. The error appeared simple enough to give it a shot, though. If I understand things correctly, this is just a matter of adding class names. My Java days have been over for a while but I'll look at the changes you make to maybe be able to provide a patch next time.
I don't know how far decompiled you want SystemUI, but I'm guessing smali is enough. [Here](https://github.com/GravityBox/GravityBox/files/256880/SystemUI.zip) it is then. SystemUI.apk from Sony's latest MM firmware (32.1.A.1.185 on z5c), deodexed and apktool d'ed.

**Comment by C3C0** [comment]
Thanks for decompiled SystemUI. I'll take a look at it as soon as I find enough time.

**Comment by C3C0** [comment]
Hi.
Time for some testing. Here is the version with support for all Xperia tiles I identified in decompiled SystemUI you provided. This should allow basic qs management functionality such as hiding and reordering.
Note, that they are explicitly listed as "Xperia" tiles within QS management. It is possible that some of the tiles are not available for your device but you can ignore them. Pay attention only to those that are available. Checking those that are not available in your stock ROM won't do anything.

Next thing that I tried to fix is "shouldFilterOut" NoSuchMethod error which should allow controlling of visibility of notifications in lock screen within Ultimate notification control.

Please test and report back.
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_xperia_qs.apk

Edit: the other issue regarding tiles disappearing might be related to maximum allowed number of tiles I found in decompiled SystemUI. It is currently set to 11. I can provide additional APK with this limit extended after you provide feedback for the first version.

**Comment by corrupt** [comment]
Thanks for the testing version. Unfortunately the problem persists. I replaced all tiles that had an Xperia version available in this version as instructed. As before, some of them appear after a reboot until, as I'm assuming, `mybeFixXperiaTiles` is called. After that, the same tiles as before disappear. Others don't appear at all.

I tried adding more than 11 tiles, too. Doing that in GB works right away. I'm now looking at a ridiculous 29-tile setup. For reference, here's a list of working and non-working tiles. I've noted with each of the Xperia tiles whether native QS has them. Stamina mode is currently not available in Sony MM Roms. Safe for a few of the missing ones (Throw, Detect USB, etc..) there is a GB version to replace it. So if you can't find a way to make these work, an option would be to just hide them on Xperia devices.

| Working Tiles | Non-working Tiles |
| --- | --- |
| <ul><li>Wi-Fi</li><li>Bluetooth</li><li>Xperia Mobile Data</li><li>Airplane Mode</li><li>Auto Rotation</li><li>Torch (Stock)</li><li>Do not disturb</li><li>Stay Awake</li><li>Quick App</li><li>Quick App 2</li><li>Compass</li><li>GPS (CM style)</li><li>NFC</li><li>Cast Screen</li><li>Network Mode</li><li>Battery</li><li>Location (SlimKat style)</li><li>Ringer Mode</li><li>Volume</li><li>Synchronization</li><li>Torch (GravityBox)</li><li>Sleep</li><li>Quick Record</li><li>Expanded Desktop</li><li>Screenshot</li><li>GravityBox</li><li>USB Tethering</li><li>Lock screen</li><li>Xperia Tethering</li></ul> | <ul><li>Xperia VoLTE</li><li>Location</li><li>Xperia Data Roaming</li><li>Inversion</li><li>Hotspot</li><li>Cellular</li><li>Quiet hours</li><li>Xperia Auto-sync data (available natively)</li><li>Xperia NFC (available natively)</li><li>Xperia LTE (available natively)</li><li>Xperia Stamina (not currently available in Marshmallow)</li><li>Xperia Screen mirroring (available natively)</li><li>Xperia Throw (available natively)</li><li>Xperia Detect USB device (available natively)</li></ul> |

**Comment by C3C0** [comment]
Tiles disappearing might be related to maximum tile limit that's set to 11 in Sony ROM.
Here is the version having that limit extended to 60.
I also removed not needed Xperia Stamina tile and I removed "maybeFixXperiaTiles" call.
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_xperia_qs2.apk

**Comment by corrupt** [comment]
Tiles no longer disapear at boot. However, The sony tiles that I marked non-working previously, only appear after a reboot when selected. They remain visible and functional after that reboot, until I open GB and click 'save' in the tiles selection screen. At that point these tiles disappear regardless of their checkbox. The activated ones re-appear after a reboot and disappear again when saved.

**Comment by C3C0** [comment]
OK. Please try with another version:
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_xperia_qs3.apk

**Comment by corrupt** [comment]
You are quick! Situation is unchanged. Did several reboots and deliberately changed settings, saved, rebooted again. Tiles still disappear after saving. Nothing in the logs.
Also, there is one tile with blank text in the settings. First appeared in _qs2.

**Comment by C3C0** [comment]
Hmm. I am out of ideas at this moment. This is currently as far as I can go without being able to debug it myself on a real device.

**Comment by C3C0** [comment]
Here is another version with some additional adjustments and debug logging turned on.
Please try and report back together with xposed log. Thanks.
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_xperia_qs4.apk

**Comment by corrupt** [comment]
Tiles no longer disappear when saving. Still not all tiles work though. I can maybe help you with that lack of a Sony device, if you're interested. Can I contact you outside github somehow?

**Comment by C3C0** [comment]
Can I see a log?

**Comment by corrupt** [comment]
[log.txt](https://github.com/GravityBox/GravityBox/files/269938/log.txt) I cannot use GB's tags as filterspec in logcat as they contain colons.
This is the output of `abd logcat -s Xposed:V` during a reboot. The "Recreating all tiles" messages are me clicking 'save' a couple of times.

**Comment by C3C0** [comment]
Thanks. Btw, log containing only xposed specific stuff can be exported from within Xposed Installer app or copied out from filesystem  ( /data/data/de.robv.android.xposed.installer/log/error.log )

**Comment by C3C0** [comment]
Another one:
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_xperia_qs5.apk

**Comment by corrupt** [comment]
[log5.txt](https://github.com/GravityBox/GravityBox/files/270018/log5.txt)
My log is identical with the one exported from Xposed Installer except for a bit of formatting. I'm always doing roughly the same thing here. Deactivate and activate a few tiles, click save a few times.

**Comment by C3C0** [comment]
According to log everything seems to be OK. Tiles are recreated when saving.
