### ISSUE TITLE
[Feature Request] quick settings tile for enable/disable enhanced 4g lte

### ISSUE THREAD

**Issue by crackers8199** [GravityBox/GravityBox#1562]
just got a network extender for my home which has really crappy service, but in order to use it i either have to turn off 4g entirely or toggle off hd voice...would be nice to have a tile available to toggle that particular setting rather than completely turning off 4g.

**Comment by iankitkulkarni** [comment]
Why you want to turn off Jio's HD voice service?

**Comment by C3C0** [comment]
Seems to be very specific and thus not suitable to be part of a complex module. It would be better to have a small stand-alone module just for such scenario.
