### ISSUE TITLE
[Feature Request - ALL VERSIONS] - Hotspot tile dual mode - bluetooth thetering

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1574]
Would it be possible add a dual mode to the hotspot tile ? One for the current wifi hotspot , and the other mode to enable bluetooth thetering. Both are 'hotspots'

**Comment by iankitkulkarni** [comment]
Two different tiles will be appreciated.. not a single tile which has dual option..

**Comment by C3C0** [comment]
BT tethering tile introduced in 2c804f9cde9adbf284a094a9b74eb4d615a22173
