### ISSUE TITLE
Reboot to recovery not working

### ISSUE THREAD

**Issue by pejakm** [GravityBox/GravityBox#1575]
AOSP-6.0.1, here: http://forum.xda-developers.com/optimus-4x-hd/orig-development/rom-aosp-marshmallow-6-0-1-t3376069

It simply restarts.

More info: Xposed v86, GravityBox v6.1.4

**Comment by C3C0** [comment]
GravityBox uses standard PowerManager reboot() method with "recovery" argument as can be seen here:
https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/ModPowerMenu.java#L416 
If it doesn't work there must be something broken in the ROM or recovery itself.
There is nothing I can do at my side to fix it. I would advise to ask ROM devs so they can check and test behavior of PowerManager.reboot("recovery") call.

**Comment by pejakm** [comment]
Thanks, I've notified the developer.
