### ISSUE TITLE
Expanded desktop intent not working as intended.

### ISSUE THREAD

**Issue by code-issues-pull** [GravityBox/GravityBox#1576]
action: gravitybox.intent.action.TOGGLE_EXPANDED_DESKTOP
extra: hwKeyValue (values: 0=toggle, 1=on, -1=off) (falls back to 0 when unspecified)

No matter the value entered into the extra field, this intent always acts as a toggle. You can not set it to either on/off, it will only toggle.

Have tried with the string and number hwKeyValue:1
And just the number itself: 1
And without any entry in the extra field.

All results in toggle, not specifically able to set it to on/off.

This is in Tasker, Cat:None, Mime Type:blank, Target:Broadcast Receiver

**Comment by C3C0** [comment]
Functionality changed with this commit: https://github.com/GravityBox/GravityBox/commit/06f2256b0ad488687da1379f910b69c822a468a2
Use different extra: enable (boolean)
If you omit extra, action will behave as toggle
