### ISSUE TITLE
[BUG - MM] - Network Tile icon does not reflect the current mode

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1583]
I am using dual mode for network tile and i have 3 modes 3G/2G, 3G and 4G/3G. When i tap the tile it will switch correctly the mode , but the icon will always appears as LTE TD-SCDMA LTE GLOBAL (1). Shoudn't reflect the current mode ?

**Comment by jsalatiel** [comment]
![bug](https://cloud.githubusercontent.com/assets/5522389/17792578/e95aa858-6577-11e6-9eff-1f00762ff176.jpg)

I am using the last MM version,

**Comment by C3C0** [comment]
Your network is TD-SCDMA. You have to go in QS management / Tile specific settings to choose from modes your operator supports. Those will then display within tile's detail dialog.
