### ISSUE TITLE
Feature Requests +  bountysource

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1588]
@C3C0 , i couldn't find a way to send one email for you, so i am asking here.
Do you accept bounty source for feature requests or some kind of  paypal payment to implement some features ? There are some features that i'd really like to see implemented, so i am willing to pay if it can be implemented. I could send you a list and you could tell me how much it would cost.

**Comment by C3C0** [comment]
Sorry but no. GravityBox being my free time activity and hobby I am not accepting "features for money" requests. I accept donations for what's been done already as a motivation to keep maintaining the project and provide support. If you'd like to request features, you may do so using the proper section of project's support forum at http://forum.xda-developers.com/devdb/project/?id=12595#featureRequests
Thanks for understanding.
