### ISSUE TITLE
ModAudio not working on Android 6

### ISSUE THREAD

**Issue by TheNetStriker** [GravityBox/GravityBox#1589]
ModAudio.java does not work any more on Android 6. I found out that the Class android.media.AudioService was moved to com.android.server.audio.AudioService. Also the RemotePlaybackState class doesn't seam to exist any more. I now simply set the build.prop property "ro.config.media_vol_steps" to 32 steps to get more volume steps. Can you please also implement this in your app?

**Comment by C3C0** [comment]
You are probably looking at the wrong file. ModAudio in Marshmallow branch is definitely OK when it comes to class naming, etc. Media tweaks work as expected on all supported (and even many unsupported) devices. If it doesn't work on yours it means your device runs system which is modified and thus different compared to AOSP.
Here's the actual ModAudio for MM: https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/ModAudio.java

**Comment by TheNetStriker** [comment]
Sorry, I forgot that there are seperate versions for each Android version. MM version is working fine.
