### ISSUE TITLE
"Kill all" button is not changed back to navbar button.

### ISSUE THREAD

**Issue by JoJoDeveloping** [GravityBox/GravityBox#1592]
I have set the "Kill all/Swipe all away" button to replace the "show last apps" button in the navbar when this screen is open. However, the "show last apps" button does not reappear when that screen is closed by choosing some apps (e.g. musical.ly). When it is clicked from the app, all apps are killed and I am returned to home.

**Comment by C3C0** [comment]
What device/system?

**Comment by C3C0** [comment]
No details provided
