### ISSUE TITLE
Led notification light stops working when GravityBox is activated

### ISSUE THREAD

**Issue by dominicusmento** [GravityBox/GravityBox#1595]
Hi,
I have a Vernee Apollo Lite (VerneeOS 6.0.3 -> is almost stock AOSP) which obviously has the RGB LED implemented. The problem about the phone itself is that no application can change it's LED color. Whatever the color is chosen from the ordinary led control apps, the LED stays blue, but that's the first part of the problem.

The second part of the problem is when I install the GravityBox MM, the notification LED stops working almost completely. No matter what I do the LED won't power up on any notification (preview with screen off in gbox also doesn't work). It lights only when I connect the phone to the charger. Between 0-90% of the battery the led stays red and 90-100% the LED is again turned off.
When I disable GravityBox, the LED behavior returns to stock: charging led is 0-15% red, 15-90% orange, 90-100% green and blinks blue again for all notifications.

Is there any way to completely disable ultimate notification control or to track the bug?

**Comment by C3C0** [comment]
GravityBox doesn't change LED behavior unless you use a feature that is related to LED. So I would suggest clearing GravityBox data to reset its settings. The only features that directly touch LED and can have side effects are:
- Disable LED flashing (Power tweaks)
- Battery charging LED (Power tweaks)

Regarding ultimate notification control, it uses standard public API for setting up notification light properties and is less likely to have side effects, provided you use colors your hardware actually supports. Here I would suggest to use exact colors like FF0000 for red, 00FF00 for green to avoid issues.

**Comment by dominicusmento** [comment]
Hi C3C0,
thanks for the answer.
Something strange is happening because I can't have the led working when the gravitybox is activated. When trying preview from the gravity box and led tester (app from store) they both doesn't work while GB is active. When I disable it through the xposed installer, and use led tester, it works only blue color which is I suppose because of the api which is somehow changed on the phone's ROM, but it's better then nothing. Obviously, when I disable GB I cannot test its behavior. 

The standard led logcat message should contain something like: 
`set_led_state colorRGB=....` 
but on this phone it is like:
`blink_blue, level=0, onMS=0, offMS=0`
so I think that Vernee disabled/overrode publicAPI.. Do you think that may be the case? If yes, is there any way to track the change/ find out how to blink the led through their own API..

Also, what's more.. that when the GB is active no LED blinks, so it looks like it stops working while the GB framework is active. Does it have any particular class or function which overrides the standard notification behaviour?

**Comment by C3C0** [comment]
Well that's strange. The only feature that affects notification light is "Battery charging LED". Make sure you keep this feature at Default setting. Also check value of "Pulse notification delay" within Display tweaks. It shouldn't be zero. (Standard delay in AOSP is 9000ms (9s)).
Other than that, there are no further changes that could affect LED behavior. Ultimate notification control strictly uses standard public notification API to control LED timing and colors so if other LED apps work, UNC should too.
Also please link me to an xposed log file (share using some cloud drive). Xposed log can be exported from within Xposed Installer app.
Use this GravityBox APK http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_lights_debug.apk instead of official one. This one has some debug logging turned on. Make sure to provide such xposed log where all other xposed modules are disabled.

**Comment by C3C0** [comment]
Any news on this?

**Comment by dominicusmento** [comment]
I was busy last couple of days.. will test today when I get within the range of my androd dev vm and post results..

**Comment by dominicusmento** [comment]
Ok, I tried to do some additional research on this.

I can now definitely say that while the phone is on charger (98%): 
- When there is no pending (unread) notification, the battery charging light seems to work as the default works (default == without gravitybox)
- When there is pending notification no notification LED blinks for it.. Only the green light blinks once for about half a second when I turn the screen on or off.. I think it is shown in the 2nd log like this: `GB:ModDisplay: lightId=4; color=-16777088; mode=1; onMS=500; offMS=500;`

When the phone is disconnected from the charger no LED blinks. I checked the settings they are all like you said.. Mainly "Default" values for battery charging LED, low battery warning etc.. Disable LED flashing is unchecked.. Pulse notification delay is 500ms (maybe that's related to 500ms mentioned earlier.. Under the UNC, LedON and OFF duration are 1000/750ms, led mode default/override.. no matter what I do with the UNC settings, the behavior stays the same.. Turning default settings on or off, it is always the same.. Even if I reset the app settings and leave it on default..

The other bug I noticed is in the navigation bar.. while I'm using the phone, the back key icon just becoms a rectangle.. The key works ok but the icon is wrong and I can refresh that by hiding and invoking the navigation bar again, but then the custom button is shown left instead of right.. Please see the screenshots on the drive.. I actually don't care about this bug because it's just visual, just sayin' so you know about it..

G-Drive: [https://drive.google.com/drive/folders/0B_y8ZlnBKJfib3VSQ19GUk5aMGM](https://drive.google.com/drive/folders/0B_y8ZlnBKJfib3VSQ19GUk5aMGM)

**Comment by C3C0** [comment]
Records with lightID=4 are those we have to focus on as ID 4 is for notification light. (3 is for battery and 2 is for navigation keys backlight if your device has any).
Each record has onMs and offMs 500 which is weird especially when you use different values in UNC. Maybe this duration is too short for hardware to be able to control LED on/off. Try increasing "Pulse notification delay" to at least 3000ms. This should correspond to offMs=3000 in the log then.
Other than that, I don't see issues that could be at GravityBox side. The fact that you/your device is the one and only report of such type I received makes me guess it's probably hardware related. Hard to tell.

**Comment by dominicusmento** [comment]
Yes, you are right. Pulse notification delay increase corresponds to offMs in log. onMs on the other side stays 500 which may be too low for the hardware to turn the LED on.. any hint where (file/code line) I can hard-code some other value for it? I'm tryin to do it but I'm little bit lost in a solution for xposed framework.. I don't see the notificationManager.notify() calls which should be the default android api.. Is there anyway to disable the hooks on all notifications just to make them run by phone default? I mean that gravity box doesn't monitor notifications at all?
(I have the source code, it's building and running on the phone so if you can just point me in the direction where to look?)

**Comment by C3C0** [comment]
To completely disable all features that are LED related you can:
- disable UNC by commenting out https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/GravityBox.java#L128
- disable charging LED and LED flashing while charging features (Power tweaks) by commenting out https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/GravityBox.java#L123
- disable button backlight and charging LED (Display tweaks) by commenting out
  https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/GravityBox.java#L124
- disable option for pulse notification delay by commenting out https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/SystemWideResources.java#L53-L57

**Comment by dominicusmento** [comment]
Yes, you definitely helped with this last comment. Thank you very much.
I'll now find out which part of the code is the cause and report if you want.. Don't know if my phone is the only one with the issue..maybe I'm just first to report..

**Comment by dominicusmento** [comment]
It's the last one which is the cause. Maybe it would be nice to have a checkbox option which would allow people to ignore the selected code, with something like this in description: 'Use this if your LED stopped working when you enabled gravityBox'.. 
I have successfully build myself the version which works for me but no one with the same problem can have the solution without building the apk..
(Ok, conclusion is that my phone is specific.. and the notification led now works with GBox just like it works by default.. still cannot change the LED color but i'm ok with that..)

_disable option for pulse notification delay by commenting out https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/SystemWideResources.java#L53-L57_

**Comment by C3C0** [comment]
This is strange as the feature is basically setting up a default value upon first use.
So slider reflects the stock value when module settings are open for the first time.
This means that as long as user doesn't touch that option, system default is used (well, almost... provided stock value is in interval 500ms-20000ms, see below).

Code that is responsible for setting up stock starting value for slider is here:
- SystemPropertyProvider - responsible for sending default system value read from system resources to module settings app running in user context: https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/SystemPropertyProvider.java#L116
- Settings - place where default value obtained from SystemPropertyProvider is used to set up startup value for slider:
  https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/GravityBoxSettings.java#L1933-L1941

When you look at the line where obtained value is capped to be within 500 - 20000 ms allowed interval (int delay = Math.min(Math.max(sSystemProperties.defaultNotificationLedOff, 500), 20000);)
it seems like it returns 500 in your case because value provided by provider is less than 500 or zero. I suspect config_defaultNotificationLedOff standard config resource plays a different role in your system compared to AOSP and changing it to something else than default results in side-effect you experienced. It would be interesting to decompile framework-res.apk and take a look at how config_defaultNotificationLedOff is configured. If you don't know hot to decompile this apk, I will be happy to decompile it myself if you provide APK to me.

Alternatively, you can enable DEBUG for SystemPropertyProvider here:
https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/SystemPropertyProvider.java#L37
then all system properties will be logged in xposed log. Make sure to keep code for setting up pulse notification delay commented out, just like you had.

**Comment by dominicusmento** [comment]
I've added framework-res.apk to the already shared [Gdrive folder](https://drive.google.com/drive/folders/0B_y8ZlnBKJfib3VSQ19GUk5aMGM). Phone version is the one I've taken from phone (which has latest updates installed), and ROM is taken from base ROM version..
I know to decompile but don't know what to look for. Also if it is possible to find out from the some other .apk how they are calling the led with the different colors - that would be nice, maybe you know which one.

Ok, I see now that config_defaultNotificationLedOff is set to 0 in integers.xml in framework-res.apk.

Edit: I've decompiled services.odex from phone's framework and found why the phone always blinks blue and with same intervals.. 

It seems that some student played around with the values and hardcoded them into the phone's framework.. L0L.. Converting 17170669 to ARGB gives exactly the same color the led is blinking..

```
        this.mDefaultNotificationColor = resources.getColor(17170669);
        this.mDefaultNotificationLedOn = resources.getInteger(17694801);
        this.mDefaultNotificationLedOff = resources.getInteger(17694802);
```

**Comment by C3C0** [comment]
No, those are not colors but resource IDs. You can take a look at https://android.googlesource.com/platform/frameworks/base/+/android-6.0.1_r70/services/core/java/com/android/server/notification/NotificationManagerService.java#912
where you find those variables getting set from resources.
17170669 in hex is 0x010600ed and when you search for this hex value within public.xml you will find entry that corresponds to config_defaultNotificationColor resource, So this value is resource ID, not the actual color.
Actual color is stored in colors.xml for given config_defaultNotificationColor, which in your case is #ff000080

Anyway, linked is updated APK where I have changed the minimum value for pulse notification delay seekbar. If you update, reboot and run module settings for the first time, value of seekbar should be properly set to default system value, which is zero in your case.
Please test and report back: http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_mm2.apk

**Comment by dominicusmento** [comment]
Interesting, I get a message "App not installed" for this new mm2 version.. 
While I try to install your previous versions.. lights_debug.apk for example it works.. This one from the link won't install.. :(

If this is a resource, is there a way to change that resource value via gravitybox when setting the ledColor by standard api?

**Comment by C3C0** [comment]
Maybe because you have your version installed which has different signature. You have to uninstall it first then install mm2. Or try downloading mm3: http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_mm3.apk

Regarding default ledColor, This value plays role only if Notification has [DEFAULT_LIGHTS](https://developer.android.com/reference/android/app/Notification.html#DEFAULT_LIGHTS) flag set.
UNC clears this flag and uses explicit [ledARGB](https://developer.android.com/reference/android/app/Notification.html#ledARGB), [ledOffMs](https://developer.android.com/reference/android/app/Notification.html#ledOffMS) and [ledOnMs](https://developer.android.com/reference/android/app/Notification.html#ledOnMS)

**Comment by dominicusmento** [comment]
Yup, uninstalled mine and installed yours and its working ok now.. Pulse notification is set to 0 and the notification led is working.. I can not test anymore the UNC because I've restarted the phone too many times and it's locked now.. grrr
From what I remember, I have set the UNC to override the notification but it didn't have effect.. Now I cannot open the UNC menu..

**Comment by C3C0** [comment]
Contact me at xgravitybox@gmail.com and I'll send back PayPal transaction ID which you can use to unlock UNC.

**Comment by dominicusmento** [comment]
Ok, now it works..
Regardless of what i set on the screen from screenshot, the  led blinks in its blue color and its defined intervals.. even when i click preview, it blinks blue.. so i assume that vernee changed the behavior of it's led.. thats why i have asked if there is possibility to mess directly with the settings found in framework-res.apk from gravityBox..

Maybe I'm missing something which I should set in gb, but I doubt it because all the other led color apps works the same as gb.. it's the phone's framework..

Yeah. It can be many things. One of them could be simply that LED driver doesn't support different colors and
it falls back automatically to blue when it can't interpret different value.
That's why API documentation at https://developer.android.com/reference/android/app/Notification.html#ledARGB
mentions "The hardware will do its best approximation" which means that they explicitly let developers know that
it is not guaranteed LED will be able to show color they supplied.

> What you could do easily for testing would be to change config_defaultNotificationColor to something else, e.g. green.
> Simply put this line within SystemWideResources.java in GravityBox:
> XResources.setSystemWideReplacement("android", "color", "config_defaultNotificationColor", Color.GREEN);
> 
> If it works then you can start experimenting with other colors.
> If it doesn't then it means LED driver is not capable of using different colors for notifications.

I tried the code you have provided. It's working.. Tried with Green and Yellow colors. The side effect is that led is on all the time, but I actually don't care about it..
I have more questions..
Is there anyway to set those settings on the fly.. Not only at system startup..? Or to hook at resource getColor() for config_defaultNotificationColor.. I mean, when the system asks for the value that it actually asks gravityBox for a value.. like the override eventHandler which would do the base() for all parameters except for config_defaultNotificationColor..

**Comment by C3C0** [comment]
In case of your device, I could try changing logic here https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/ModLedControl.java#L272-L276
so instead of setting Notification properties I will set value of mDefaultNotificationColor variable. Not sure about setting mDefaultNotificationLedOn and mDefaultNotificationLedOff as it would most likely break LED completely the same way as feature for pulse notification delay does. I am going to take a quick look and come up with APK in a while.

**Comment by C3C0** [comment]
OK. Here is APK where instead of
`n.ledARGB = ls.getColor();`
I'm doing
`XposedHelpers.setIntField(param.thisObject, "mDefaultNotificationColor", ls.getColor());`
when device is Vernee Apollo Lite.
I find this approach quite hacky so not sure what other side-effects it can produce.
Link: http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_mm5.apk

**Comment by dominicusmento** [comment]
Huh, I'm afraid something is broken now.. When I try to open GBox I get "waiting for response from gravitybox system framework.." and couple of seconds after that.. "GravityBox system framework not responding. Exiting."

**Comment by C3C0** [comment]
Disable and reenable module in xposed installer app. Then reboot.

**Comment by dominicusmento** [comment]
Yes, GBox works again.. Led blinks by default behavior on preview, but on notification event is red which is the value I have set in GBox.. I then changed the color to green.. Received the notification and the LED is Green.. Red and Green were always on but, that's it!
This is very very nice job!!
Can you apply the same code for LedSettingsActivity? Maybe we can mess with the LedOn/LedOff settings in the LedSettingsActivity too..?

**Comment by C3C0** [comment]
I have some ideas to make it work from preview and potentially this could also allow apps that set led color (e.g. Facebook does) to work. Currently all apps that use custom led color can't work due to led implementation your OEM introduced. Will get back to it later. Can't right now.

**Comment by dominicusmento** [comment]
No problem mister @C3C0 ! Take your time.. This would be nice feature but it's not a must, only if you want it. I hope this is your hobby and you like to do these kind of coding :D If you need any other resource from rom or anything else let me know.
I'm going to test think about the LED which is always on because I got the green blinking once and I cannot reproduce it anymore..

**Comment by C3C0** [comment]
Thanks for your generous donation. Appreciated. Attached is APK which should have preview LED fixed. If this works, next step would be to also try setting mDefaultNotificationLedOn and mDefaultNotificationLedOff.
It looks like blinking is somehow hardcoded based on color. mDefaultNotificationLedOff being zero means that LED should not turn off that's why it lights constantly. But in case of default blue color it blinks. Strange implementation indeed.
APK: http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_mm6.apk

Edit: Another APK where also mDefaultNotificationLedOn and mDefaultNotificationLedOff are being set. Note that this can break LED again, especially when other then default system values are used.
Default system values are:
- 500 for ledOn
- 0 for ledOff

APK: http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_mm7.apk
Going to get some sleep. Looking forward to your feedback tomorrow.

**Comment by dominicusmento** [comment]
Wow, preview definitely works.. 
I'm now experimenting with available colors.. 
Here are the results with preview, there are definitely some strange led behaviors:
- #ff0000ff: always on
- #ff201000: pattern -> red-yellow-red-off-green-off (random)
- #ff202000: orange blinking (from config_notificationsBatteryMediumARGB)
- #ff000080: blue blinking (from config_defaultNotificationColor)
- #ff100000: red blinking (from config_notificationsBatteryLowARGB) - this blinks shortly, and takes longer time to turn on again I think because of this: `config_notificationsBatteryLowARGB`
- #ff081000: green blinking (random, again faster blinking)
- #ff001010: light blue blinking (random, again faster blinking)

I have just tested random colors.. still didn't look at any pattern to see why some of them blinks and some don't.. This is very interesting.. and definitely don't reflect LedOn/Off times.. The pattern one is the best -> LED changes the color from one to another in gradient effect lol xD

**Comment by C3C0** [comment]
Never seen anything like that before. I updated my previous post to include APK no. 7 for testing.

**Comment by dominicusmento** [comment]
Ok, I found the template for the blinking ones.. The dot on the color picker is actually always on the same place.. I only change the color bar.
Going to test the apk #7 so I will edit the post with the results.. This now is actually pretty good and allows plenty of options to set all of the available led colors as flashing/always on.. Looking at where we were yesterday.. or couple of days ago.. this is very satisfying. :) Have a good night.

**Comment by C3C0** [comment]
Thanks. I suspect this strange logic is implemented at led driver level. (/system/lib/hw/lights.???.so)
So even if java framework code corresponds to AOSP, led driver is doing its own timings based on color values. This could be confirmed by looking at device tree source code which contains led driver source code.  But most likely it's not opensource.

**Comment by dominicusmento** [comment]
Bingo.. Don't know what have you done but #7 is like this:
#ff202000 - blinks red (was orange before), and respects the MS values set in GB..
This now works only with red color.. 

**Edit**
It works just like #6 apk when default values are set for LedOn/Off
Depending on a color choosen in color picker and ledOn/Off values the Led behaves differently.. Sometimes it works according to ledOn/Off values but only with red color, sometimes it doesn't work at all.. It ignores the color which is set. When I set ledOn/Off to default then it returns to chosen color and default blinking/alwaysOn pattern depending on a color..

Maybe it would help to set the LedOn/Off before setting a color. I doubt it but maybe it is worth of trying??

Vernee promised that they will make the whole OS open source.. will look for a driver

I have decompiled lights.so and put the files here: https://drive.google.com/open?id=0B_y8ZlnBKJfia1JkSWttTGJ3UDQ
I did it here: https://retdec.com/decompilation-run/ and it seems that it is nicely decompiled.. although I can't find anything useful there and I think I'm going to get some sleep too..

**Comment by C3C0** [comment]
OK. Thanks for info. So I guess we should stick to version 6 for now and maybe get back to it later when more info is available. I am also thinking about removing "Pulse notification delay" feature for Apollo Lite as it doesn't do what it's supposed to, anyway. I will keep On/Off timing options in UNC although they won't have any effect. What do you think?

**Comment by dominicusmento** [comment]
Yes. I also thought that it would be a must to disable the pulse notification delay slider for apollo lite.
Version 7 works just like version 6 when default ledOn and ledOff values are provided. And when the right color is chosen, it enables red led blinking in the intervals you define.. So I think the #7 is more advanced and provides more features but there should be a way (button) to reset all those values (ledOn, ledOff, ledColor) to default.. (500, 0, ff000080 -> I think those are defaults).. "Reset to Vernee Defaults" - something like that
Don't know if that's hard to implement.. only for Vernee Apollo Lite.. But it would be a nice feature where we could set e.g fast blinking red for missed call and slow blinking red for email.. That works nicely on #7.. ;)

**Comment by C3C0** [comment]
Well, I'm not keen on adding specific options for this device. Especially when things can change in the future, e.g. with another ROM update. What I could do to keep 7 functionality would be to set proper default values for ledOn and ledOff for Apollo Lite to make sure 500 and 0 is used when user is setting up per-app options for the first time.

**Comment by dominicusmento** [comment]
That's also nice workaround.. I'm thinking about setting the default color as well to #ff201000, the one with the pattern.. 
this color with default ledOn/Off works by pattern mentioned earlier.. and when changing ledOn/Off it gives #7 functionality.. after that when user changes hue/saturation on colorpicker it gives blinking colors..

I think it's a good starting point for "defaults" in gbox

**Comment by C3C0** [comment]
OK. Version 8 available for testing. Note, that default values are going to show for those apps you haven't open UNC settings for, yet. Apps you already opened have own values stored.
APK: http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_mm8.apk

**Comment by dominicusmento** [comment]
Ok, tested unc per app settings.. I can confirm that everything works as intended. 
Color/ledOn/ledOff default values are set correctly.. and the led blinks with the pattern when opening the per app unc settings. Taking another hue/saturation bar on color picker makes the led blinks accordingly..
I can also confirm that display settings doesn't show Pulse notification delay setting anymore.

I think this can easily go into master branch/production ;)

**Comment by C3C0** [comment]
OK. Thanks for testing and patience. Here is the commit with adjustments for your reference:
https://github.com/GravityBox/GravityBox/commit/82bc70f0c296aa84195d7d19b4c4738ef75b28fd

**Comment by dominicusmento** [comment]
Hello again @C3C0 , can you quckly add the "Vernee Apollo" phone to the same exception list? I switched from lite to full version of the phone so I assume it would be better if you can solve it for everyone as I see that I'm not the only one: [official forum](http://bbs.vernee.cc/forum.php?mod=viewthread&tid=1854&extra=page%3D1) 

I think we can change _Build.MODEL.equals("Apollo Lite")_ to _Build.MODEL.contains("Apollo")_

**Comment by C3C0** [comment]
Hi. I'll take a look at current implementation and get back to you later.

**Comment by C3C0** [comment]
Please test with http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_mm9.apk and report back.
Thanks.

**Comment by dominicusmento** [comment]
Hi, tested the new mm9 version you have just provided and I can confirm that it works the same way it worked on a Vernee Apollo Lite. This version works on both phones (tested on both) so I think this can go to master.
Thanks

**Comment by dari0cm** [comment]
Hi, sorry for reopening this thread, but I have the exact same problem but on a Vernee Mars Pro, the version of android in this case is Nougat, can someone help me to solve this problem? I don't have any idea of programming so I don't know how to compile the modified apk for this.

**Comment by C3C0** [comment]
Modifications we were discussing in this thread are already built into official version for Nougat but are applied only to Apollo device. https://github.com/GravityBox/GravityBox/blob/nougat/src/com/ceco/nougat/gravitybox/Utils.java#L270
Not sure if Mars comes with the same functionality as Apollo but I can compile a version for testing if you provide me with Xposed Log from which I can read info about your device to be able to adjust identification logic I linked above.

**Comment by dari0cm** [comment]
Here is the log. If you need something more, ask me. Thank you for your time.
[xposed_error_20181112_154215.log](https://github.com/GravityBox/GravityBox/files/2572302/xposed_error_20181112_154215.log)

**Comment by C3C0** [comment]
Please test this APK where I made adjustments for Mars Pro to be treated the same way as Apollo. This means everything discussed in this thread applies.
[GravityBox.zip](https://github.com/GravityBox/GravityBox/files/2575040/GravityBox.zip)

**Comment by dari0cm** [comment]
Now the LED is working, but not as its usual way.

Without GravityBox the LED work on 4 different colours:
-Red when the device is charging and battery is below 15%.
-Yellow when the device is charging and battery is between 16% and 89%.
-Green when the device is charging and battery is over 90%.
-Blue when there is a notification.

With the modified version you sent on the previous post, the LED turns to Yellow when there is a notification instead to blue, is there any way to solve this?

**Comment by C3C0** [comment]
Hardly without physically having such device. First, you should check ultimate notification control for how you have LED configured. I recommend setting LED mode to original for Default settings (in case you use them) and apps for which you have enabled ultimate notification control. This makes sure that colors are not affected by GravityBox but rather config_defaultNotificationColor (comes with ROM) is applied instead.
Then you can start experimenting with setting different colors to check if you can change the behavior.

**Comment by dari0cm** [comment]
Ok, I've managed to get it working as usual. Thank you!
