### ISSUE TITLE
Dual Sim Issue..

### ISSUE THREAD

**Issue by iankitkulkarni** [GravityBox/GravityBox#1597]
When I click on 1st Sim icon on notification drawer, the second Sim icon gets expanded.. it should show data usage on 1st Sim in general use but it shows 2nd Sim data usage. Please fix this as soon as possible..

**Comment by C3C0** [comment]
Make sure you provide complete report. What version of GravityBox, what device/system you have and provide link to an xposed log. AOSP system doesn't have 2 SIM tiles even if device is dual sim. 2 SIM tiles is an extra feature of your device which means it's possible it is not even fully supported by GravityBox thus can have far more other differences and issues compared to pure Android.

**Comment by iankitkulkarni** [comment]
Xposed log :- https://drive.google.com/file/d/0B5UsJA5haW5oczVGUlJCMUNsc2s/view?usp=drivesdk

My xda post regarding this issue and video on it..:- http://forum.xda-developers.com/showpost.php?p=68051302&postcount=2110

I have Moto G 2015(osprey) xt1550 on stock 6.0.1 .. 
The issue I am facing in GB v6.1.5
Solve the issue as soon as possible..

**Comment by C3C0** [comment]
"Please" would be nicer than "fix ASAP"...
Anyway, test with the following APK and report back including log file.
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_mm_moto_cell_tile.apk

**Comment by iankitkulkarni** [comment]
It seems the issue is fixed by your side. I mean I enabled all modules except Android N-ifiy module in xposed installer. And the problem is solved. But when I enable Android N-ifiy module, the same problem appears. The issue is solved by your side I think. Thanks for your quick support.
