### ISSUE TITLE
[Feature-Request/MM] - Lockscreen tweaks > Direct unlock > See through : Make background 100% visible (not dimmed)

### ISSUE THREAD

**Issue by Kronopt** [GravityBox/GravityBox#1604]
As it currently stands, this option makes the lockscreen look like this:
![2016-10-22 00 33 34](https://cloud.githubusercontent.com/assets/19473287/19615595/62453ef0-97f9-11e6-873a-139d937baa1c.png)

In my opinion, it would be much better if it looked like this (as it was on lollipop), with the same brightness applied to both the background and the unlock pattern dots (photoshoped image):
![2016-10-22 00 2](https://cloud.githubusercontent.com/assets/19473287/19615638/23c501b4-97fa-11e6-9eda-6b8586329606.png)

As it stands the background is barely visible when the brightness is low, which makes it very hard to look at the time, date or alarm at a glance.

I know this is not high priority, but I think it would be a nice and simple (maybe) feature to implement.

**Comment by WarmColor** [comment]
yeah，i want  it too.
