### ISSUE TITLE
[MM] Lock Screen Visibility

### ISSUE THREAD

**Issue by benqqq** [GravityBox/GravityBox#1605]
I use "Hide persistent notifications" and "Hide all notifications" options to hide the lockscreen persistent notification from app OS Monitor, BatteryBot Pro and AFWall+. Those options works fine at v6.1.5 and older version, but it fail with app BatteryBot Pro at v6.1.5.

**Comment by C3C0** [comment]
Please, be more specific.
- for which app you use which Lockscreen visibility option?
- which one exactly doesn't work?
- does it work when you go back to v6.1.5?

It would also be helpful if you provided a link to Xposed error log.

**Comment by benqqq** [comment]
I'm sorry for being unclear
- for which app you use which Lockscreen visibility option?
  both of "Hide persistent notifications" and "Hide all notifications" are not working.
- which one exactly doesn't work?
  BatteryBot Pro v9.0.1
- does it work when you go back to v6.1.5?
  Yes.
- Xposed error log
  [error.zip](https://github.com/GravityBox/GravityBox/files/545786/error.zip)

**Comment by C3C0** [comment]
Thanks. Indeed it's a bug introduced in v6.1.6
