### ISSUE TITLE
Navigation Bar wont go away

### ISSUE THREAD

**Issue by Yakie996** [GravityBox/GravityBox#1606]
Im using the latest .6 also tried .5 but neither of them work 

`10-23 08:24:47.184 I/Xposed  ( 6349): -----------------
10-23 08:24:47.184 I/Xposed  ( 6349): Starting Xposed version 86, compiled for SDK 23
10-23 08:24:47.184 I/Xposed  ( 6349): Device: XT1572 (motorola), Android version 6.0.1 (SDK 23)
10-23 08:24:47.184 I/Xposed  ( 6349): ROM: MPHS24.107-58-1
10-23 08:24:47.184 I/Xposed  ( 6349): Build fingerprint: motorola/clark_reteu/clark:6.0.1/MPHS24.107-58-1/1:user/release-keys
10-23 08:24:47.184 I/Xposed  ( 6349): Platform: arm64-v8a, 64-bit binary, system server: yes
10-23 08:24:47.184 I/Xposed  ( 6349): SELinux enabled: yes, enforcing: yes
10-23 08:24:47.194 I/Xposed  ( 6349): -----------------
10-23 08:24:47.194 I/Xposed  ( 6349): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-23 08:24:47.382 I/Xposed  ( 6349): Detected ART runtime
10-23 08:24:47.399 I/Xposed  ( 6349): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-23 08:24:47.538 I/Xposed  ( 6349): Loading modules from /data/app/de.Maxr1998.xposed.gpm-2/base.apk
10-23 08:24:47.671 I/Xposed  ( 6349):   Loading class de.Maxr1998.xposed.gpm.hooks.Main
10-23 08:24:47.680 I/Xposed  ( 6349): Loading modules from /data/app/com.devadvance.rootcloak2-1/base.apk
10-23 08:24:47.704 I/Xposed  ( 6349):   Loading class com.devadvance.rootcloak2.RootCloak
10-23 08:24:47.713 I/Xposed  ( 6349): Loading modules from /data/app/com.oasisfeng.greenify-1/base.apk
10-23 08:24:47.765 I/Xposed  ( 6349):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
10-23 08:24:47.775 I/Xposed  ( 6349):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
10-23 08:24:47.777 I/Xposed  ( 6349): Loading modules from /data/app/me.rijul.knockcode-1/base.apk
10-23 08:24:47.797 I/Xposed  ( 6349):   Loading class me.rijul.knockcode.XposedMod
10-23 08:24:47.808 I/Xposed  ( 6349): Loading modules from /data/app/fi.razerman.bancontactrootbypasser-1/base.apk
10-23 08:24:47.846 I/Xposed  ( 6349):   Loading class fi.razerman.bancontactrootbypasser.RootDetectionBypass
10-23 08:24:47.854 I/Xposed  ( 6349): Loading modules from /data/app/net.madnation.sskip-1/base.apk
10-23 08:24:47.875 I/Xposed  ( 6349):   Loading class net.madnation.sskip.sskip
10-23 08:24:47.876 I/Xposed  ( 6349): Loading modules from /data/app/com.ryansteckler.nlpunbounce-1/base.apk
10-23 08:24:47.897 I/Xposed  ( 6349):   Loading class com.ryansteckler.nlpunbounce.hooks.Wakelocks
10-23 08:24:47.911 I/Xposed  ( 6349): Loading modules from /data/app/com.smartmadsoft.xposed.aio-2/base.apk
10-23 08:24:47.942 I/Xposed  ( 6349):   Loading class com.smartmadsoft.xposed.aio.Loader
10-23 08:24:47.958 I/Xposed  ( 6349): Loading modules from /data/app/com.ceco.marshmallow.gravitybox-2/base.apk
10-23 08:24:48.031 I/Xposed  ( 6349):   Loading class com.ceco.marshmallow.gravitybox.GravityBox
10-23 08:24:48.038 I/Xposed  ( 6349): GB:Hardware: qcom
10-23 08:24:48.039 I/Xposed  ( 6349): GB:Product: clark_reteu
10-23 08:24:48.039 I/Xposed  ( 6349): GB:Device manufacturer: motorola
10-23 08:24:48.039 I/Xposed  ( 6349): GB:Device brand: motorola
10-23 08:24:48.039 I/Xposed  ( 6349): GB:Device model: XT1572
10-23 08:24:48.041 I/Xposed  ( 6349): GB:Device type: phone
10-23 08:24:48.041 I/Xposed  ( 6349): GB:Is MTK device: false
10-23 08:24:48.041 I/Xposed  ( 6349): GB:Is Xperia device: false
10-23 08:24:48.041 I/Xposed  ( 6349): GB:Is Moto XT device: true
10-23 08:24:48.042 I/Xposed  ( 6349): GB:Has telephony support: true
10-23 08:24:48.042 I/Xposed  ( 6349): GB:Has Gemini support: false
10-23 08:24:48.042 I/Xposed  ( 6349): GB:Android SDK: 23
10-23 08:24:48.042 I/Xposed  ( 6349): GB:Android Release: 6.0.1
10-23 08:24:48.042 I/Xposed  ( 6349): GB:ROM: MPHS24.107-58-1
10-23 08:24:48.077 I/Xposed  ( 6349): Loading modules from /data/app/tw.fatminmin.xposed.minminguard-1/base.apk
10-23 08:24:48.115 I/Xposed  ( 6349):   Loading class tw.fatminmin.xposed.minminguard.Main
10-23 08:24:48.201 I/Xposed  ( 6349): Loading modules from /data/app/com.Taptigo.Xposed.XNotifications-1/base.apk
10-23 08:24:48.265 I/Xposed  ( 6349):   Loading class com.Taptigo.Xposed.XNotifications.Hooks.Hook
10-23 08:24:48.306 I/Xposed  ( 6349): Loading modules from /data/app/com.sabik.assistantenabler-1/base.apk
10-23 08:24:48.329 I/Xposed  ( 6349):   Loading class com.sabik.assistantenabler.AssistantEnabler
10-23 08:24:48.330 I/Xposed  ( 6349): Loading modules from /data/app/de.robv.android.xposed.mods.appsettings-1/base.apk
10-23 08:24:48.349 I/Xposed  ( 6349):   Loading class de.robv.android.xposed.mods.appsettings.XposedMod
10-23 08:24:48.365 I/Xposed  ( 6349): Loading modules from /data/app/net.jzhang.powernap-2/base.apk
10-23 08:24:48.409 I/Xposed  ( 6349):   Loading class net.jzhang.powernap.xposed.WakeLockManager
10-23 08:24:48.440 I/Xposed  ( 6349): Loading modules from /data/app/com.voidvapps.intelli3g-1/base.apk
10-23 08:24:48.466 I/Xposed  ( 6349):   Loading class com.voidvapps.intelli3g.Xposed3GHook
10-23 08:24:48.478 I/Xposed  ( 6349): Loading modules from /data/app/com.czbix.xposed.wifipassword-1/base.apk
10-23 08:24:48.491 I/Xposed  ( 6349):   Loading class com.czbix.xposed.wifipassword.Patch
10-23 08:24:48.494 I/Xposed  ( 6349): Loading modules from /data/app/com.ivianuu.halo-2/base.apk
10-23 08:24:48.532 I/Xposed  ( 6349):   Loading class com.ivianuu.halo.Xposed.MainXposed
10-23 08:24:49.999 I/Xposed  ( 6756): GB:Is AOSP forced: true
10-23 08:24:50.156 I/Xposed  ( 6756): Amplify: Version 3.3.6c
10-23 08:24:50.156 I/Xposed  ( 6756): Amplify: Attempting 19to21 AlarmHook
10-23 08:24:50.158 I/Xposed  ( 6756): Amplify: Successful 19to21 AlarmHook
10-23 08:24:50.158 I/Xposed  ( 6756): Amplify: Attempting 21 WakeLockHook
10-23 08:24:50.159 I/Xposed  ( 6756): Amplify: Successful 21 WakeLockHook
10-23 08:24:50.159 I/Xposed  ( 6756): Amplify: Service Blocking Status: true
10-23 08:24:50.159 I/Xposed  ( 6756): Amplify: Attempting 23 ServiceHook
10-23 08:24:50.161 I/Xposed  ( 6756): Amplify: Successful 23 ServiceHook
10-23 08:24:50.196 I/Xposed  ( 6756): [Power Nap] Trying alternative service hook.
10-23 08:24:50.198 E/Xposed  ( 6756): java.lang.NoSuchMethodError: com.android.server.am.ActiveServices#startServiceLocked(android.app.IApplicationThread,android.content.Intent,java.lang.String,int,int,int,android.content.Context)#exact
10-23 08:24:50.198 E/Xposed  ( 6756):   at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:337)
10-23 08:24:50.198 E/Xposed  ( 6756):   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:178)
10-23 08:24:50.198 E/Xposed  ( 6756):   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:253)
10-23 08:24:50.198 E/Xposed  ( 6756):   at net.jzhang.powernap.xposed.WakeLockManager.try17to21ServiceHook(WakeLockManager.java:211)
10-23 08:24:50.198 E/Xposed  ( 6756):   at net.jzhang.powernap.xposed.WakeLockManager.hookServices(WakeLockManager.java:185)
10-23 08:24:50.198 E/Xposed  ( 6756):   at net.jzhang.powernap.xposed.WakeLockManager.handleLoadPackage(WakeLockManager.java:129)
10-23 08:24:50.198 E/Xposed  ( 6756):   at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
10-23 08:24:50.198 E/Xposed  ( 6756):   at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
10-23 08:24:50.198 E/Xposed  ( 6756):   at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
10-23 08:24:50.198 E/Xposed  ( 6756):   at de.robv.android.xposed.XposedInit$3$1.beforeHookedMethod(XposedInit.java:135)
10-23 08:24:50.198 E/Xposed  ( 6756):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
10-23 08:24:50.198 E/Xposed  ( 6756):   at com.android.server.SystemServer.startBootstrapServices(<Xposed>)
10-23 08:24:50.198 E/Xposed  ( 6756):   at com.android.server.SystemServer.run(SystemServer.java:273)
10-23 08:24:50.198 E/Xposed  ( 6756):   at com.android.server.SystemServer.main(SystemServer.java:173)
10-23 08:24:50.198 E/Xposed  ( 6756):   at java.lang.reflect.Method.invoke(Native Method)
10-23 08:24:50.198 E/Xposed  ( 6756):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
10-23 08:24:50.198 E/Xposed  ( 6756):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
10-23 08:24:50.198 E/Xposed  ( 6756):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
10-23 08:25:32.186 I/Xposed  ( 7059): [Taptigo-XNotifications] Hooking systemUI
10-23 08:25:32.306 I/Xposed  ( 7059): [Taptigo-XNotifications] Headsup is controlled by headsup manager
10-23 08:25:32.425 I/Xposed  ( 7059): [Taptigo-XNotifications][ERROR] Error dumping BaseStatusBar, Exception: Exception message: open failed: ENOENT (No such file or directory)
10-23 08:25:32.425 I/Xposed  ( 7059): 
10-23 08:25:32.425 I/Xposed  ( 7059):  Stack trace:java.io.File.createNewFile(File.java:939)
10-23 08:25:32.425 I/Xposed  ( 7059): com.Taptigo.Shared.g.f.a(SourceFile:191)
10-23 08:25:32.425 I/Xposed  ( 7059): com.Taptigo.Xposed.XNotifications.Hooks.ap.a(SourceFile:312)
10-23 08:25:32.425 I/Xposed  ( 7059): com.Taptigo.Xposed.XNotifications.Hooks.ap.a(SourceFile:271)
10-23 08:25:32.425 I/Xposed  ( 7059): com.Taptigo.Xposed.XNotifications.Hooks.ap.c(SourceFile:256)
10-23 08:25:32.425 I/Xposed  ( 7059): com.Taptigo.Xposed.XNotifications.Hooks.ap.a(SourceFile:90)
10-23 08:25:32.425 I/Xposed  ( 7059): com.Taptigo.Xposed.XNotifications.Hooks.Hook.handleLoadPackage(SourceFile:100)
10-23 08:25:32.425 I/Xposed  ( 7059): de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
10-23 08:25:32.425 I/Xposed  ( 7059): de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
10-23 08:25:32.425 I/Xposed  ( 7059): de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
10-23 08:25:32.425 I/Xposed  ( 7059): de.robv.android.xposed.XposedInit$1.beforeHookedMethod(XposedInit.java:93)
10-23 08:25:32.425 I/Xposed  ( 7059): de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
10-23 08:25:32.425 I/Xposed  ( 7059): android.app.ActivityThread.handleBindApplication(<Xposed>)
10-23 08:25:32.425 I/Xposed  ( 7059): android.app.ActivityThread.-wrap1(ActivityThread.java)
10-23 08:25:32.425 I/Xposed  ( 7059): android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
10-23 08:25:32.425 I/Xposed  ( 7059): android.os.Handler.dispatchMessage(Handler.java:102)
10-23 08:25:32.425 I/Xposed  ( 7059): android.os.Looper.loop(Looper.java:148)
10-23 08:25:32.425 I/Xposed  ( 7059): android.app.ActivityThread.main(ActivityThread.java:5443)
10-23 08:25:32.425 I/Xposed  ( 7059): java.lang.reflect.Method.invoke(Native Method)
10-23 08:25:32.425 I/Xposed  ( 7059): com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
10-23 08:25:32.425 I/Xposed  ( 7059): com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
10-23 08:25:32.425 I/Xposed  ( 7059): de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
10-23 08:25:32.425 I/Xposed  ( 7059): 
10-23 08:25:32.425 I/Xposed  ( 7059): Inner exception:
10-23 08:25:32.425 I/Xposed  ( 7059): Exception message: open failed: ENOENT (No such file or directory)
10-23 08:25:32.425 I/Xposed  ( 7059): 
10-23 08:25:32.425 I/Xposed  ( 7059):  Stack trace:libcore.io.Posix.open(Native Method)
10-23 08:25:32.425 I/Xposed  ( 7059): libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
10-23 08:25:32.425 I/Xposed  ( 7059): java.io.File.createNewFile(File.java:932)
10-23 08:25:32.425 I/Xposed  ( 7059): com.Taptigo.Shared.g.f.a(SourceFile:191)
10-23 08:25:32.425 I/Xposed  ( 7059): com.Taptigo.Xposed.XNotifications.Hooks.ap.a(SourceFile:312)
10-23 08:25:32.425 I/Xposed  ( 7059): com.Taptigo.Xposed.XNotifications.Hooks.ap.a(SourceFile:271)
10-23 08:25:32.425 I/Xposed  ( 7059): com.Taptigo.Xposed.XNotifications.Hooks.ap.c(SourceFile:256)
10-23 08:25:32.425 I/Xposed  ( 7059): com.Taptigo.Xposed.XNotifications.Hooks.ap.a(SourceFile:90)
10-23 08:25:32.425 I/Xposed  ( 7059): com.Taptigo.Xposed.XNotifications.Hooks.Hook.handleLoadPackage(SourceFile:100)
10-23 08:25:32.425 I/Xposed  ( 7059): de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
10-23 0`

**Comment by C3C0** [comment]
Please:
- make sure to test with scenario where only GravityBox is enabled and all other modules are disabled
- post a log where only GravityBox is enabled
- do not paste contents, attach as file or use some kind of cloud, e.g. google drive
- also write which options exactly you use for navigation bar

**Comment by Yakie996** [comment]
![screenshot_20161023-093634](https://cloud.githubusercontent.com/assets/19747119/19624725/5f4997f8-9904-11e6-88fc-df61217e3634.png)
![screenshot_20161023-093630](https://cloud.githubusercontent.com/assets/19747119/19624726/5f4affe4-9904-11e6-92bb-ba84ed802d07.png)
![screenshot_20161023-093609](https://cloud.githubusercontent.com/assets/19747119/19624727/5f4b5354-9904-11e6-9254-63babe7caba5.png)

**Comment by Yakie996** [comment]
https://drive.google.com/file/d/0B5L4e1ZQQ_3nYTAyajZxOThLZWc/view?usp=drivesdk

**Comment by C3C0** [comment]
The one and only thing that comes to my mind. It is possible that you have navbar forced in build.prop so I would check that. Look for qemu.hw.mainkeys=0. If it's there I suggest you completely remove that line from there.

**Comment by Yakie996** [comment]
yes the lat worked! thank you!

**Comment by C3C0** [comment]
Maybe it would be also good to find out where this setting came from. It's not GravityBox as it doesn't directly modify build.prop nor any other system file. Maybe it's a consequence of using some other module that directly modifies build.prop
