### ISSUE TITLE
Some log glitch on OnePlus 3

### ISSUE THREAD

**Issue by cbdreinulldrei** [GravityBox/GravityBox#1610]
Not sure how this is going to be treated. I fully understand this device does not use AOSP, still, as most of it works fine, maybe this can be worked around.

10-25 20:11:54.007 E/Xposed  ( 4450): java.lang.NoSuchMethodError: com.android.systemui.statusbar.phone.PanelView#instantExpand()#exact
10-25 20:11:54.007 E/Xposed  ( 4450):   at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:337)
10-25 20:11:54.007 E/Xposed  ( 4450):   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:178)
10-25 20:11:54.007 E/Xposed  ( 4450):   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:253)
10-25 20:11:54.007 E/Xposed  ( 4450):   at com.ceco.marshmallow.gravitybox.ModStatusBar.init(ModStatusBar.java:961)
10-25 20:11:54.007 E/Xposed  ( 4450):   at com.ceco.marshmallow.gravitybox.GravityBox.handleLoadPackage(GravityBox.java:179)
10-25 20:11:54.007 E/Xposed  ( 4450):   at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
10-25 20:11:54.007 E/Xposed  ( 4450):   at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
10-25 20:11:54.007 E/Xposed  ( 4450):   at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
10-25 20:11:54.007 E/Xposed  ( 4450):   at de.robv.android.xposed.XposedInit$1.beforeHookedMethod(XposedInit.java:93)
10-25 20:11:54.007 E/Xposed  ( 4450):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
10-25 20:11:54.007 E/Xposed  ( 4450):   at android.app.ActivityThread.handleBindApplication(<Xposed>)
10-25 20:11:54.007 E/Xposed  ( 4450):   at android.app.ActivityThread.access$1600(ActivityThread.java:159)
10-25 20:11:54.007 E/Xposed  ( 4450):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1445)
10-25 20:11:54.007 E/Xposed  ( 4450):   at android.os.Handler.dispatchMessage(Handler.java:102)
10-25 20:11:54.007 E/Xposed  ( 4450):   at android.os.Looper.loop(Looper.java:148)
10-25 20:11:54.007 E/Xposed  ( 4450):   at android.app.ActivityThread.main(ActivityThread.java:5507)
10-25 20:11:54.007 E/Xposed  ( 4450):   at java.lang.reflect.Method.invoke(Native Method)
10-25 20:11:54.007 E/Xposed  ( 4450):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-25 20:11:54.007 E/Xposed  ( 4450):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-25 20:11:54.007 E/Xposed  ( 4450):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
10-25 20:11:58.106 I/Xposed  ( 4450): GB:ModStatusBar: Error setting long-press handler on mTime: com.android.systemui.statusbar.phone.QuickStatusBarHeader#mTime
10-25 20:11:58.140 I/Xposed  ( 4450): GB:StatusbarSignalCluster: Error hooking getOrInflateState: com.android.systemui.statusbar.SignalClusterView#inflatePhoneState(int)#exact
10-25 20:11:58.140 I/Xposed  ( 4450): GB:StatusbarSignalCluster: Error hooking getOrInflateState: com.android.systemui.statusbar.SignalClusterView#inflatePhoneState(int)#exact

**Comment by C3C0** [comment]
This error is related to "Expand notification panel" action that was reworked since 6.2.0.
Looks like 1+3 is missing some stuff that's present in AOSP. 
Try testing with this APK and report back:
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_issue_1610.apk

**Comment by cbdreinulldrei** [comment]
Looks great except for one last bit:

11-11 08:30:12.788 I/Xposed  ( 4099): GB:ModStatusBar: Error setting up Disable peek hooks: com.android.systemui.statusbar.phone.PanelView#instantExpand()#exact

**Comment by C3C0** [comment]
You can disregard the second one. Please confirm whether actions to show/collapse notificanion panel and QS panel work.

**Comment by cbdreinulldrei** [comment]
Can you specify which ones to test specifically? Thanks!

**Comment by C3C0** [comment]
E.g. Navigation keys action, assign "expand notification panel" to some key and test whether panel gets expanded when you execute action.

**Comment by cbdreinulldrei** [comment]
Expand quick setting works. Expand notifications does not seem to work. But maybe I don't have the right notifications to test...

**Comment by cbdreinulldrei** [comment]
Anything I can be of further help with? Apart from this not working, it'd still be great to keep this in the main branch. Many other features do work and maybe a deodexed SystemUI might shed some light on the right hooks...

**Comment by cbdreinulldrei** [comment]
Latest Log with test version:

11-14 16:02:13.465 I/Xposed  ( 3764): GB:ModStatusBar: Error setting up Disable peek hooks: com.android.systemui.statusbar.phone.PanelView#instantExpand()#exact
11-14 16:02:19.838 I/Xposed  ( 3764): GB:ModStatusBar: Error setting long-press handler on mTime: com.android.systemui.statusbar.phone.QuickStatusBarHeader#mTime
11-14 16:02:19.842 I/Xposed  ( 3764): GB:StatusbarSignalCluster: Error hooking getOrInflateState: com.android.systemui.statusbar.SignalClusterView#inflatePhoneState(int)#exact
11-14 16:02:19.843 I/Xposed  ( 3764): GB:StatusbarSignalCluster: Error hooking getOrInflateState: com.android.systemui.statusbar.SignalClusterView#inflatePhoneState(int)#exact

**Comment by C3C0** [comment]
These are normal error messages as a result of GravityBox not being compatible nor designed for OxygenOS. There is currently no plan to fix them on my side as I don't own any device running such system.
