### ISSUE TITLE
Update to 6.1.6 broke hide all persistent notifications on lockscreen

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1618]
After update to 6.1.6 ( dont remember the old version), the lockscreen is full of persistent notifications, even after rechecking if the default setting in gravitybox is to hide all persistent notifications from lockscreen.

**Comment by C3C0** [comment]
It was fixed in 6.1.7. Btw, the latest official version is 6.2.1. 6.1.6 is a history.

**Comment by jsalatiel** [comment]
This is really strange, the latest version avaliable inside my xposed framework is 6.1.6.
![_20161111_050412 jpg](https://cloud.githubusercontent.com/assets/5522389/20208472/2f2eea3c-a7cd-11e6-98a0-46ab1cfbe77a.jpg)

**Comment by C3C0** [comment]
Hit refresh or clear data of xposed installer app
