### ISSUE TITLE
[R1HD, 6.0.1] Cursor control keys, etc not working

### ISSUE THREAD

**Issue by nyanpasu64** [GravityBox/GravityBox#1620]
Blu R1HD Amazon. Android 6.0.1. Magisk systemless Xposed and phh's superuser.

Under "navigation bar tweaks", checking"cursor control keys" (or any other of the 4 checkboxes total) will not do anything. I really need cursor control...

(Unfortunately, the volume key cursor control interferes with Terminal/Termux volume keys as ctrl/fn. Can it be disabled per app?)

**Comment by C3C0** [comment]
Sorry but it's not possible without me physically having such device. OEM probably put their additional stuff on top of pure Android which breaks compatibility with this module. Regarding volume key cursor control and term apps - yes I know about it but don't currently have a solution. It's not a priority.
