### ISSUE TITLE
Setting without any entry in strings.xml (Show brightness icon)

### ISSUE THREAD

**Issue by Basti1512** [GravityBox/GravityBox#1622]
In "Statusbar tweaks -> QuickSettings management -> Show brightness icon" I found a setting without an entry in strings.xml. Therefore it is difficult to add an appropriate translation ;-)

**Comment by C3C0** [comment]
It's there:
Lollipop: https://github.com/GravityBox/GravityBox/blob/lollipop/res/values/strings.xml#L2029
Marshmallow: https://github.com/GravityBox/GravityBox/blob/marshmallow/res/values/strings.xml#L2020

**Comment by Basti1512** [comment]
Shit, my repo was not up to date. Sorry for any inconvenience.

**Comment by C3C0** [comment]
No problem :)
