### ISSUE TITLE
[Feature-Request/MM] OnePlus Phone can't use!

### ISSUE THREAD

**Issue by Dove137** [GravityBox/GravityBox#1624]
My OnePlus 3T can't use all hardware key actions. (back/home/recent button)

**Comment by C3C0** [comment]
I'm working on improving compatibility with OP3T but it's too complicated and will take some time.

**Comment by C3C0** [comment]
https://github.com/GravityBox/GravityBox/commit/3d1ca1d3b07bcbb9665ebc98f49c085e74cadeba

**Comment by Dove137** [comment]
New version is fixed!!!  Thank you~
