### ISSUE TITLE
[OP2, OOS 3.5.6]  Brightness control Not working

### ISSUE THREAD

**Issue by f-cramer** [GravityBox/GravityBox#1634]
On Oneplus Two, Oxygen OS 3.5.6, Android 6.0.1, Xposed v87 brightness control via status bar swipe is not working.

**Comment by C3C0** [comment]
1) Make sure auto-brightness is turned off
2) Provide full xposed error log exported after testing the feature

**Comment by C3C0** [comment]
No additional info provided
