### ISSUE TITLE
One Plus 3 ( Not T ) GravityBox MM QuickSettings broken

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1635]
I have installed OxygenOS beta 7 on my Oneplus 3 ( 3.5.6 ) / GravityBox6.3.2-rev2  and i noticed a big problem with quicksettings. The moment i enable quicksettings, the phone wont work after reboot, i will only get a blink 'desktop' that answers to no commands or clicks. After disable the module using recovery, i was able to see that gravitybox is not detecting OxygenOS correctly.
 
GB:Is OxygenOS 3.5 ROM: false

so it is probably trying to hook in different places.
I also noticed that if i enable navigation bar, the navigation bar will show but it wont do its primary functions ( back/home/recents ), i think it is also related.

**Comment by C3C0** [comment]
Please, try adb shell and enter command:
getprop ro.oxygen.version
post result

**Comment by jsalatiel** [comment]
shell@OnePlus3:/ $ getprop ro.oxygen.version                               
OP3_O2_Open_7

**Comment by jsalatiel** [comment]
Just to make sure there was not another problem i have changed isOxygenOs35Rom to 'return true' in Utils.java class and everyhing started working just fine, though gravitybox unlocker wont unlock the UNC features anymore. :/

**Comment by C3C0** [comment]
OK. Thanks. Now the question is how many other beta versions of 3.5 exist...

**Comment by jsalatiel** [comment]
The last 3.5.xx is beta 7. Starting on beta 8 is android nougat. Could you release a version that also checks for "OP3_O2_Open_7" to validate if it is a oxygen3.5 ?

**Comment by C3C0** [comment]
I see. So it seems it's the only one we have to take care of.

**Comment by jsalatiel** [comment]
Apparently beta 5, 6 and 7 are oxygenOS 3.5.4 , 3.5.5 and 3.5.6.

**Comment by C3C0** [comment]
beta 4 was lollipop or marshmallow already?

**Comment by jsalatiel** [comment]
According to youtube ( https://www.youtube.com/watch?v=ODyGnfBhekw ) is already marshmallow.
I have never used beta 4. I started on beta 5 =)

**Comment by C3C0** [comment]
Can you please test this APK?
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_oos_3.5_beta.apk

**Comment by jsalatiel** [comment]
It is working great ! thanks !

**Comment by C3C0** [comment]
Version 6.3.2-rev3 is now available via Xposed Installer
