### ISSUE TITLE
[OP3/3T] Network Toggles widgets not working for the data sim card

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1638]
in oneplus 3/3t , the widgets for toggle network mode ( 2g/3g only/4g...) only changes the mode for the SIM1. If you use the SIM2 as data card, the toggle will have no effect.
These toggle should detect the current data card and change the modes for it , instead try to change only the SIM1.

**Comment by C3C0** [comment]
What widgets?
If you mean quick settings tile then note that you can long-press it to switch whether it applies to Sim slot one or 2. It is indicated within tile label. Moreover there is a setting in Quicksettings management / Tile specific settings / Network mode tile settings where you can set to what Slot it applies by default. This settings is also used in case of using GravityBox Action for toggling network mode.

**Comment by jsalatiel** [comment]
I am talking about gravitybox actions. I know about the default slot in quick settings, but what i was trying to say is that when i try to toggle, gravitybox could detect the current data sim in use and change the network mode for that slot.

**Comment by jsalatiel** [comment]
and the same would be a nice behaviour for the gravitybox.intent.action.CHANGE_NETWORK_TYPE =)

**Comment by C3C0** [comment]
GravityBox is not restricted to change network type for data SIM only. You can change it for both slots regardless of whether there is mobile data or not. GravityBox action uses SIM slot that's currently defined in the settings I mentioned earlier. If you want to control active SIM slot for network type changes, you can do so using gravitybox.intent.action.QS_NETWORK_MODE_SIM_SLOT_CHANGED together with simSlot extra (integer; 0 == slot1, 1 == slot2)
