### ISSUE TITLE
[Feature-Request / MM] - Quiet Mode Wear-Only

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1639]
Currently there are 3 quiet modes: ON - OFF - AUTO
Would it be possible to create a mode called WEAR ONLY that would essentially avoid any sound or vibration on the mobile ( including those apps in quiet hours exception list ) while still sending the vibration to the android wear ?
It would be great to use during work.

**Comment by C3C0** [comment]
I use "Mute device vibrations" leaving "Mute notification vibrations" unchecked exactly for this purpose. This allows my watch to vibrate while phone stays quiet. Exceptions still make noise though.

**Comment by jsalatiel** [comment]
Hi @C3C0, i also use the  "Mute device vibrations" leaving "Mute notification vibrations" unchecked.
but as you have mentioned, the sound will still make noise. Thats why i though about a "WEAR ONLY" mode that could be easily toggled even by send an intent through tasker.
