### ISSUE TITLE
[NX511J, 6.0.1] Data activity indicators showing in the middle of dual sim signal status icons

### ISSUE THREAD

**Issue by beansandmash** [GravityBox/GravityBox#1641]
Firstly, thank you for this amazing mod, I have been using it across many devices and versions!

I am experiencing a small bug with the data activity indicators in that it is not showing on top of the signal status, but rather it shifts everything to the left and puts it in the middle of both signal statuses (dual SIM). If I swap the SIMs, the indicator doesn't show at all, and if I reboot, it shows it in the middle. WiFi activity indicator works as expected, screenshot below.

![activityindicator](https://cloud.githubusercontent.com/assets/19478069/23090499/29265de2-f597-11e6-88a7-304222563b1b.png)

I apologise as I know I am not using AOSP, rather I am using MoKee 6.0.1 (open source, based on AOSP) on a dual SIM ZTE Nubia Z9 Mini. Xposed error log is attached.

[error.log.txt](https://github.com/GravityBox/GravityBox/files/784786/error.log.txt)

**Comment by C3C0** [comment]
Indicators are designed for AOSP and even a small change in ROM your device runs can break it. Mokee is not officially supported as I can support only those systems that are AOSP or devices I physically own.

**Comment by beansandmash** [comment]
Ah, fair enough. Do you have any hints that you could provide for me fixing it myself? The only errors that are being logged seem to be related to updateBatteryPadding(), which doesn't appear to be a problem.

My intuition is that when it's getting resId via mResources.getIdentifier() in https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/StatusbarSignalCluster.java#L254-L268, it's finding a hidden icon between the two? I would need to find the proper resId of the nestedGroup that is exhibiting data activity?

Or perhaps it's phoneStates.get(0) that's grabbing the wrong ViewGroup? In that case, could I check the visibility of the object and go to the first visible group?

Thanks in advance

**Comment by C3C0** [comment]
Feature injects SignalActivity view into mobile view container which is expected to be a FrameLayout.
https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/StatusbarSignalCluster.java#L116
If it's different type of layout in your system then SignalActivity layout needs to be adjusted accordingly.

**Comment by beansandmash** [comment]
Ah, thank you, mobile_signal_group appears to be a FrameLayout nested inside LinearLayout instead of just a FrameLayout. https://github.com/MoKee/android_frameworks_base/blob/mkm/packages/SystemUI/res/layout/mobile_signal_group.xml

I'll have a go at modifying it at some point, not entirely sure what I'm doing at the moment.. I wouldn't need to modify SignalActivity right (presumably I'd break wifi data activity if I did)? I should be able to target the child FrameLayout of nestedGroup in https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/StatusbarSignalCluster.java#L254-L268 ?

Apologies for the stupid questions, I am not an android dev :(

**Comment by C3C0** [comment]
Yes, you have to pass that child FrameLayout as a container when creating SignalActivity instance here:
https://github.com/GravityBox/GravityBox/blob/marshmallow/src/com/ceco/marshmallow/gravitybox/StatusbarSignalCluster.java#L265
quick solution to get correct nestedGroup is to use:
nestedGroup = nestedGroup.getChildAt(0); // FrameLayout is the first child of mobile group

**Comment by beansandmash** [comment]
Thank you so much for the help! 👍
