### ISSUE TITLE
Statusbar - Data Traffic Monitor overlaps clock when it is centered

### ISSUE THREAD

**Issue by Kronopt** [GravityBox/GravityBox#1642]
Nexus 5
Android M 6.0.1 Build M4B30Z
Xposed Framework 87
GravityBox 6.3.2-rev3

Settings:
Statusbar tweaks -> Clock settings: Center clock
Statusbar tweaks -> Data traffic monitor -> Data traffic monitor style: Omni style

When the righthand side of the statusbar gets crowded enough, the data traffic monitor will overlap the clock.

![overlapping](https://cloud.githubusercontent.com/assets/19473287/23093111/f1bad618-f5d1-11e6-9643-b11f2f613d80.png)

**Comment by C3C0** [comment]
Unfortunately there's nothing I can do about it. Either make your clock shorter or use left side for data traffic monitor.

**Comment by Kronopt** [comment]
Ok.

I found another bug that I think might be related to this:
Same settings as before plus data traffic monitor position set to 'right'.

Data traffic monitor appears centered on the statusbar while in the lockscreen (it should be on the right)

**Comment by C3C0** [comment]
It's by design. Traffic monitor is always centered in lock screen due to lock screen statusbar nature.
