### ISSUE TITLE
gravitybox [Ll] nav bar not working

### ISSUE THREAD

**Issue by ivanzhng** [GravityBox/GravityBox#1649]
I'm Android version is on lollipop 5.1 all option works fine but the navigation bar setting is not working

**Comment by C3C0** [comment]
Sorry, but you'll have to provide far more information than that.
- what device
- what system it is running. 
- share Xposed Error log that can be exported from within Xposed Installer app

Note that navbar tweaks are designed on top of standard Android's navigation bar and may be totally incompatible with navigation bar modified by OEM of your device.

**Comment by C3C0** [comment]
Closing as no necessary info provided
