### ISSUE TITLE
[Feature Request] Allow changing screenshot delay time

### ISSUE THREAD

**Issue by ghost** [GravityBox/GravityBox#1653]
Currently the Screenshot feature in GravityBox has a [1 second delay](https://github.com/GravityBox/GravityBox/blob/jellybean/src/com/ceco/gm2/gravitybox/ModHwKeys.java#L1504), there are some Xposed modules that are able to change the delay of screenshots, but they can't change GravityBox one for obvious reasons.

Ideally there should be an option to modify this value or remove it, so users that have a custom button enabled with the screenshot feature do not need to wait 1 second for he screenshot to go through.

**Comment by C3C0** [comment]
Better would be to differentiate delay based on from where screenshot was called. E.g. when from QS tile delay is required as enough time for notification panel to collapse must be allowed.
