### ISSUE TITLE
Wear Mode should honor 'interactive mode'

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1667]
Wear mode is great, but it should keep notifications quiet during user interaction, so it would not vibrate the wear if you are actively using your phone.

**Comment by jsalatiel** [comment]
@C3C0 How do you check if interactive ?  powermanager.isInteractive() ? I have noticed that i am missing several notifications on my wear after this change.
Reading the documentation on the .isInteractive method, there is the following:

When this method returns true, the device is awake and ready to interact
     * with the user (although **this is not a guarantee that the user is actively**
     * **interacting with the device just this moment**).

If you are really using this method to detect if the phone is 'interactive' , could you change it to check using display.getState() ==  Display.STATE_ON from DisplayManager ?

**Comment by C3C0** [comment]
None of isInteractive or Display.STATE_ON guarantee user is interacting with a device - as user can be only peeking in lock screen.
I am using a different approach - listening to ACTION_USER_PRESENT broadcast which is sent AFTER user has bypassed lock screen (in case user is not using lock screen, event is received as soon as Display state is ON / home screen shows)

**Comment by jsalatiel** [comment]
Hum , but how do you detect the device is not in use anymore ? When the screen is off ? I am missing several notifications (vibration on wear) even with the screen off. Usually those that come in less than one minute after screen is off.

**Comment by jsalatiel** [comment]
and according to what you have mentioned, when i am peeking in lock screen the wear should vibrate since it is not unlocked yet (ACTION_USER_PRESENT has not broadcast yet), but it does not vibrate.

**Comment by jsalatiel** [comment]
Actually it vibrate a few times. But i dont like this non deterministic behaviour =)
Thanks, @C3C0! This is probably some nasty bug in android.

**Comment by C3C0** [comment]
Hmm. I used wear mode myself since it was introduced and didn't notice missing vibrations on a watch. Also, this detection logic is not used for wear only mode but also for "interactive mode" in quiet hours. So if this one works OK there is no reason wear mode wouldn't. I currently switched my main device to Nougat so cannot test.

**Comment by jsalatiel** [comment]
@C3C0  shouldn't "interactive mode" be activated during phone call ? I noticed that while in a call, i keep getting vibrations from notifications.  It would be nice having a phone not vibrating when i am "busy" on a call.

**Comment by C3C0** [comment]
Well, when you are dealing with a call while device is locked then this session is considered non-interactive. I would need to add another condition. Interactive would be either when device is unlocked and lock screen is dismissed or there is an active call.

**Comment by jsalatiel** [comment]
That  would be great.
Btw, i always forget to ask, wouldn't be better to move "Interactive Mode" from UNC -> QuietMode -> "Interactive Mode"   to UNC -> "Interactive Mode".

Inside quiet mode the user thinks that this will only work when quiet mode is active.

**Comment by C3C0** [comment]
It's due to the design. This feature is available only when quiet hours feature is enabled as a whole.

**Comment by C3C0** [comment]
Please, can you test this APK for me during the phone call?
There is a new logic where user presence is evaluated also with regards to current phone call state.
Thanks.
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_Oreo_8.2.0-wip3.apk

**Comment by jsalatiel** [comment]
Sorry the delay. I am on nougat. The name appears to be for oreo.
Can you compile it for N ?

**Comment by C3C0** [comment]
Ahh. I see.
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_Nougat_7.2.0-wip1.apk
Not sure if you will be able to download as there is going to be a planned power outage so server will be offline.

**Comment by jsalatiel** [comment]
It appears to be working. I am gonna test for 2 more days and report back here

**Comment by jsalatiel** [comment]
So, i found a little bug.
1) The phone is in standby
2) Someone calls you and you pick up - Phone is now in interactive mode, no vibration which is great
3) You hang up and keep using the phone - The phone is not in "interactive mode" even though you are using. You have to turn the screen off and on to be "interactive" again

**Comment by C3C0** [comment]
"Keep using your phone" means you unlock after the phone call?

**Comment by jsalatiel** [comment]
Yeah, i unlock using fingerprint scan from the OP3T.
I am gonna test it again.

**Comment by C3C0** [comment]
OK. Looks like ACTION_USER_PRESENT event is not as reliable as I thought. I reworked the logic to avoid using it. Now I am using PowerManager in combination with KeyguardManager to calculate whether user is present.

**Comment by jsalatiel** [comment]
Do you want me to test it ?

**Comment by C3C0** [comment]
I have some ongoing work in another branch so I can compile APK for testing later if you are interested to test.

**Comment by jsalatiel** [comment]
If you wanna help, i am here!

**Comment by C3C0** [comment]
Thanks. Link to new APK:
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_Nougat_7.2.0-wip2.apk
Note in case you use auto Quiet Hours - this version comes with support for multiple time ranges for auto Quiet Hours so you will have to define your intervals as the previous ones are not going to be preserved due to design changes.

**Comment by jsalatiel** [comment]
I am still testing... but i noticed one small bug, interactive mode on call also mutes "On Call Connected" and "On call disconnected" from Call Vibrations in "Phone Tweaks" . It should not.

**Comment by C3C0** [comment]
Well, I can't differentiate between those and other vibrations in case of "mute device vibrations" option which blocks vibrator across the board.

**Comment by jsalatiel** [comment]
No problem :+1:

**Comment by C3C0** [comment]
Potential solution would be to automatically switch to "mute notification vibration" policy during call.

**Comment by jsalatiel** [comment]
Do you see any drawbacks in doing this ?

**Comment by jsalatiel** [comment]
Strange, in my configuration i only have "Mute notificaiton Vibrations" enabled. Mute device vibrations is already not selected.

**Comment by jsalatiel** [comment]
Got it. The vibration during call is only supressed for me if WEAR MODE is enabled. So it is fine :)

**Comment by C3C0** [comment]
You are right. Interactive mode is applied to notifications only - it shouldn't affect other device vibrations.

**Comment by jsalatiel** [comment]
So why wear mode  prevent vibration On Call Connected?

**Comment by jsalatiel** [comment]
It is just a question, it is no problem at all.
All the vibrations being quiet on interactive mode during wearmode is really perfect :)

**Comment by C3C0** [comment]
Wear mode implicitly blocks all device vibrations even if "mute device  vibrations" is disabled for standard quiet hours.
