### ISSUE TITLE
Add intents to change defaultVoice/DefaultSMS/DefaultData subscription on one plus 3

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1668]
Would it be possible/difficult add some intent to change the default voice/sms /data subscription.
It would allow it to automate a few things using tasker including automatically switch the data from one subscription to another if there is no service on the current default one.

**Comment by C3C0** [comment]
I'll take a look at it. Will you be able to eventually do some testing for me?

**Comment by jsalatiel** [comment]
Sure, btw i forgot to mention that my phone is the one plus 3.
What i am thinking is that we could have 3 intents:
gravitybox.intent.action.CHANGE_DEFAULT_SMS
gravitybox.intent.action.CHANGE_DEFAULT_DATA
gravitybox.intent.action.CHANGE_DEFAULT_CALL
 
containing the EXTRA "simSlot" which could be 0,1,.. or ASK ( ASK in case of call and SMS )

What do you think ?

**Comment by C3C0** [comment]
I'm not sure I'll be able to hook some user interface (in case of ASK) but let's see.

**Comment by C3C0** [comment]
APK for testing:
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_jsalatiel.apk

Usage:
Action: gravitybox.intent.action.CHANGE_DEFAULT_SIM_SLOT
Extras:
- subType (String), mandatory. Allowed values: VOICE, SMS, DATA
- simSlot (int), optional. Allowed values: 0, 1
If you omit simSlot extra or its value is -1 you will be asked to choose SIM slot via dialog.

Let me know how it went.

**Comment by jsalatiel** [comment]
SMS and DATA are working great. 
Voice is not working. It always stays as ASK.

**Comment by C3C0** [comment]
Implementation is the same for all of three. So if those other 2 work, VOICE should do too.
Are you sure it's not a foreign dialog coming from the system?

**Comment by jsalatiel** [comment]
OK. I am gonna attach a few pictures and try to explain how i am testing.

This is my default picture on image 1:

![screenshot_20170522-114515](https://cloud.githubusercontent.com/assets/5522389/26314584/d89c9fc0-3ee4-11e7-9e06-111da2960d61.png)

by default i use data and sms from slot 2 (TIM) and for voice i prefer the ASK option.

Now i went to tasker, and used the intent to change data sim to slot 0 (OI). After broadcast the intent this is the new picture of settings:

![screenshot_20170522-114549](https://cloud.githubusercontent.com/assets/5522389/26314635/fef64d24-3ee4-11e7-83e0-6f3f970fa404.png)

The data was changed sucessfully to sim slot 0 (OI)

Now i broadcast the intent to change SMS to slot 0. It also worked! Here is the result.

![screenshot_20170522-114613](https://cloud.githubusercontent.com/assets/5522389/26314685/2271d264-3ee5-11e7-913e-dbb5bb06d2b3.png)


Now i sent the broadcast to change the voice slot to 0 (also tried 1),  and here is the result. Nothing has changed!
 
![screenshot_20170522-114709](https://cloud.githubusercontent.com/assets/5522389/26314743/47dd9aba-3ee5-11e7-83b4-398fd1cedbba.png)

**Comment by C3C0** [comment]
Now I get​ what you meant. My implementation doesn't​ count on system's "ask mode". It only sets sim slot which apparently system doesn't accept when ask mode is enabled. Try turning off ask mode and try again. I guess it'll work then.

**Comment by jsalatiel** [comment]
Yeah, it works! But it would be nice if we could also select the 'ask mode'. 
Anyway, thank you very much!

**Comment by C3C0** [comment]
Looking at the Android sources calls have to be handled completely different way. So I will probably skip it and allow only sms and data if quick solution can't be found.

**Comment by jsalatiel** [comment]
Thanks !

**Comment by C3C0** [comment]
OK. Here is another version.
I reworked VOICE so now it also allows setting ASK.
You can do that by passing extra simSlot=2 (only applicable when subType=VOICE)
When you do not supply simSlot extra, dialog will also contain ASK option.
Please test both scenarios - with explicit simSlot extra and without simSlot extra.
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_jsalatiel2.apk
Thanks.

**Comment by jsalatiel** [comment]
Just tested both methods, now it is working perfectly !
Thank you very much.

**Comment by jsalatiel** [comment]
Maybe i am asking too much , but could you broadcast a Sticky Intent with the simslot being used for each type ? =)

**Comment by C3C0** [comment]
I could do that as a reply to a request (e.g. another intent action) as otherwise I would have to add a tracking logic which would track changes.

**Comment by jsalatiel** [comment]
it can be a reply =)

**Comment by C3C0** [comment]
OK. Here is APK #3
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_jsalatiel3.apk

When you send intent with action:
gravitybox.intent.action.GET_DEFAULT_SIM_SLOT
you will receive reply in form of a broadcast with the following params:
action: gravitybox.intent.action.REPORT_DEFAULT_SIM_SLOT
extras: simSlotVoice, simSlotSms, simSlotData
their values are 0, 1 or -1 in case it was not possible to get that info. 
Note, that you will receive -1 also in case Voice is set to ASK.

**Comment by jsalatiel** [comment]
There's only a small bug: if sms is set to always ask, it is not returning -1. I think we didnt account for the 'always ask' in case of sms. But for me this is not a problem :-)
Thanks!

**Comment by C3C0** [comment]
I wonder how it is possible to set ASK for SMS as from what I see in the sources of Android 6.0.1 SIM settings, it is possible only for Voice:
https://android.googlesource.com/platform/packages/apps/Settings/+/android-6.0.1_r78/src/com/android/settings/sim/SimDialogActivity.java#203

**Comment by jsalatiel** [comment]
Maybe it is something specific for oxygenOS.

**Comment by C3C0** [comment]
Most likely. Nevermind, I'm going to commit the changes soon.
