### ISSUE TITLE
GravityBox disappears after second reboot

### ISSUE THREAD

**Issue by huangyg11** [GravityBox/GravityBox#1674]
Install gravitybox, reboot, worked.

And reboot again, can't find gravitybox in xposed modules, here is xposed log:

[xposed_error_20170711_234800.log.txt](https://github.com/GravityBox/GravityBox/files/1139602/xposed_error_20170711_234800.log.txt)

And reboot again, the gravitybox can't found even in the xposed logs.

**Comment by C3C0** [comment]
I don't see how module missing in xposed installer could be related to module itself as it doesn't have any effect on module management. Most likely some kind of an xposed framework glitch or some other external factor. Moreover, judging from the errors in the log, your device's system is not fully compatible with GravityBox as there are many changes that make system different compared to pure Android.

**Comment by huangyg11** [comment]
Sorry for posting in the wrong place. Would you mind telling me where I should ask for help?

**Comment by C3C0** [comment]
Not sure. Maybe in your device specific forums where you can share experience with others running the same configuration.
