### ISSUE TITLE
support Android7.1 Nougat

### ISSUE THREAD

**Issue by WrBug** [GravityBox/GravityBox#1675]
hello,I'm fitting the android 7.1 devices and fixing some bug，I wanna publish on 
Xposed Module Repository，so I need your permission，thanks！

also you can see :
[https://github.com/WrBug/GravityBox](https://github.com/WrBug/GravityBox)

**Comment by C3C0** [comment]
Please, don't do that. Another clone of GB in official repository is the last thing we need. Using different package name would break quite many things outside the project. You can use it unofficially for personal use.
Moreover, current state of unofficial Xposed Framework is not ready for full GB development. You can read my statement whichj also contains link to statement of Xposed developer here: https://plus.google.com/116827098689898644151/posts/7C3mdFDayQe
