### ISSUE TITLE
Gravity Box For Nougat Zip Invalid Format

### ISSUE THREAD

**Issue by PreachJohn** [GravityBox/GravityBox#1679]
I just tried an install using Wugfresh. TWRP would not Install. 'Invalid Zip Format'.

**Comment by C3C0** [comment]
GravityBox is a normal app. Flashing it via recovery makes no sense.

**Comment by PreachJohn** [comment]
Your answer makes no sense. How else do you install a zip file? It is in an invalid zip format.
 I flash any and every other zip file successfully.

**Comment by C3C0** [comment]
What zip file? GravityBox is always distributed as classic APK. I don't know where you get zip file from and what it's supposed to do thus you should ask at the source.

**Comment by PreachJohn** [comment]
https://github.com/GravityBox/GravityBox/tree/nougat

This download is in zip format.

JohnB

**Comment by C3C0** [comment]
It's a download for source code. Compiled APKs can be get at forum.xda-developers.com or repo.xposed.info (nougat version is not there as it was designed for unofficial Xposed Framework which is far from being stable and fully functional)

**Comment by PreachJohn** [comment]
Ah, so that's it. My bad.
It's just that the Nougat APK will not stay working on my Nexus
6/7.1.1/Magisk Rooted phone. It appeared to work, then quit. That's what
puzzles me.
The Magisk ported Xposed Framework apparently Active was what it was
supposed to work in. But no.
Thanks much for your excellent replies.
PreachJohn
