### ISSUE TITLE
[Feature Request] AOSP Signal Network indicators

### ISSUE THREAD

**Issue by lars18th** [GravityBox/GravityBox#1680]
Hi,

In recent devices the "4G", "H+", "LTE", etc. are texts using the position of one icon sided to the signal icon.
Please, can you add the function to use the "old" behaviour of putting the text inner to the signal icon?

Thank you!

**Comment by C3C0** [comment]
Sorry, but I am not able to support devices running Android modified by OEM without physically owning them.
