### ISSUE TITLE
Pixel XL

### ISSUE THREAD

**Issue by Romank1** [GravityBox/GravityBox#1681]
Pixel XL
Android N 7.1.2 Build njh47f
Xposed Framework 88.1
GravityBox 7.0.0 Final

GravityBox works on Pixel XL 7.1.2 but the changes are reset when the device is rebooted and have to be applied again each time.

I can post the log, if you need.

**Comment by C3C0** [comment]
I don't think logs can help here. I am using standard Xposed Framework API to read preferences so I do not have a clue what might be wrong but I doubt it's in the module. Maybe post a complete listing of /data/data/com.ceco.nougat.gravitybox folder so I can check how it looks like at filesystem level.

**Comment by C3C0** [comment]
Looks like it probably has something to do with File Based Encryption. As mentioned here: https://github.com/rovo89/XposedBridge/issues/192#issuecomment-335760806

**Comment by Romank1** [comment]
Please download /data/data/com.ceco.nougat.gravitybox:
https://www.dropbox.com/s/uiijskfbcdww06t/com.ceco.nougat.gravitybox.zip?dl=0

**Comment by Romank1** [comment]
I can test the debug versions, if you want.

**Comment by Romank1** [comment]
https://forum.xda-developers.com/showpost.php?p=74117358&postcount=355

> On stock OOS oneplus 5, settings are not remembered. A lot of modules this happens with, I think it has to do with encryption and because of it, settings files are not available at boot but only after unlocking?
> A soft reboot fixes it, but it's annoying

I agree, after a soft reboot, it works fine also on Pixel.

**Comment by C3C0** [comment]
I am investigating whether there is a workaround possible. I will get back to you when I come up with something.

**Comment by Romank1** [comment]
Ok

**Comment by C3C0** [comment]
Please, can you test with this APK? It should use protected storage for preferences thus they should survive reboot on FBE devices.
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_7.0.0_FBE_test1.apk
Please, report back. Thanks.

**Comment by Romank1** [comment]
test1 version works!  no more settings lost.

Thanks

**Comment by Romank1** [comment]
But I have another problem, keys remap don't works for any key.
Can you check this?

**Comment by C3C0** [comment]
It's a current bug where all the devices are identified as running OxygenOS.
I messed up detection logic...

**Comment by Romank1** [comment]
Do you have the test version to test this?

**Comment by C3C0** [comment]
Closed by https://github.com/GravityBox/GravityBox/commit/d825b7be445c18de9a90eb8f77c1c5eb2b74deb8

**Comment by Jasi2169** [comment]
@Romank1 can you give me your email ? and test one apk for me so that i can test if it remembers the changes with FBE ?

**Comment by C3C0** [comment]
Wasn't that issue already resolved? Since GB v7.0.1

**Comment by Jasi2169** [comment]
it is resolved still i am testing for myself ;)
