### ISSUE TITLE
Vibration Mode icon shown twice in the statusbar

### ISSUE THREAD

**Issue by nchaitreddy** [GravityBox/GravityBox#1682]
Running FreedomOS verison 4.5 on OnePlus 3T. I can provide log if you want.

**Comment by imranzahid01** [comment]
I have a stock oneplus 5. The work around is to check `hide vibration icon` the toggle sound settings to vibrate and full.

**Comment by C3C0** [comment]
It's a glitch in OOS on OP5. OnePlus keeps 2 vibrate icons for no reason. GravityBox is not adding it, it only controls its visibility.

**Comment by nchaitreddy** [comment]
Okay. Hiding the vibration icon works for now. Will it be corrected in the future update?

**Comment by C3C0** [comment]
The thing is what OnePlus basically did was that they changed icon for do not disturb silent mode to vibrate icon. I will remove the option for hiding vibrate icon in GravityBox in case of OOS as that icon is not used at all in this ROM.
