### ISSUE TITLE
[Feature Request] Rename "Status Bar Colors" or add functionality to alter status bar color.

### ISSUE THREAD

**Issue by code-issues-pull** [GravityBox/GravityBox#1687]
Initially the issue was raised in 2015: https://github.com/GravityBox/GravityBox/issues/1427

Seems a bit silly considering some people may want to lock their status bar to a fixed color (AMOLED screens locked to black for example).

But, if the feature won't be implemented, it seems appropriate to just rename the category to "Status Bar Icon Colors" since that is all that it currently alters.

Thanks!

**Comment by C3C0** [comment]
Well, it's still about colors in status bar, whether background can be modified or not so I don't see a reason renaming that, especially when it should be done for all currently supported localizations.
For fixed color, there is an option for disabling Translucent decor in Display tweaks.
