### ISSUE TITLE
Overlapping of Center clock and bluetooth icon

### ISSUE THREAD

**Issue by nchaitreddy** [GravityBox/GravityBox#1689]
In Dual sim phones like oneplus 3t, when bluetooth and vibration mode both are enabled, the center clock overlaps the bluetooth icon

**Comment by C3C0** [comment]
It's not just this case. There are many others. This is a standard side effect of using center clock and there is nothing that can be done about it.

**Comment by nchaitreddy** [comment]
Can't it be programmed so as to shift a little if no space is there?

**Comment by C3C0** [comment]
No as it resides in an independent container that's on top of status bar, thus there's no connection between it and other system icons. Moreover it wouldn't be a "center clock" after shifting anymore.

**Comment by nchaitreddy** [comment]
Okay
