### ISSUE TITLE
[GravityBox-N] Add vibrate icon when vibration is toggle using quicktiles OOS

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1697]
When one set vibrate by clicking the Ringer Mode Tile , it should put some vibrate icon on the status bar, otherwise you just do not know if it is in vibrate mode or not.
Using Oxygen OS 4.5.1 on OP3T.
Thanks!

**Comment by C3C0** [comment]
It's caused by this commit. https://github.com/GravityBox/GravityBox/commit/e974aaa6f68a599bbbcf924c6a92b0c277b07013 
The thing is OnePlus uses vibrate icon for their silent mode and people ended up with 2 icons in the status bar. Need to think about a solution.
