### ISSUE TITLE
Capture Exceptions, turn off log output

### ISSUE THREAD

**Issue by Cypher01** [GravityBox/GravityBox#1700]
The Xposed log is completely flooded with error messages from GravityBox. This makes it really hard to see the output from other modules.

This is most probably related to different roms, not all classes/methods are available on every rom.

Please capture all Exceptions and add a setting to turn off the Xposed log output.

You could simply surround every hook with something like this:

```
try {
    // do your stuff
} catch (ClassNotFoundError e) {
    if (logOutputOn) {
        // log output
    }
} catch (NoSuchMethodError e) {
    if (logOutputOn) {
        // log output
    }
}
```

**Comment by C3C0** [comment]
Yes, happens on incompatible devices. Logs on compatible ones is perfectly clean. All exceptions are already being captured but there is currently no option to dynamically turn error logging on/off from module settings. It's just too many of them to take care of and would require a lot of time to go through the whole module. Maybe one day when I have enough time.

**Comment by Cypher01** [comment]
I know that this is because of incompatible devices/roms. I understand, that GravityBox is designed for being used with only certain roms. Nevertheless it's always a good idea to not generally assume that a class/method exists, but catch the above exceptions.

Of course I understand, that this is a very time consuming task. Anyway, it would be great if you improve this, when you have time.
