### ISSUE TITLE
Compatibility with lenovo stock rom

### ISSUE THREAD

**Issue by 2shrestha22** [GravityBox/GravityBox#1701]
I have Lenovo a319. It uses 5 step signal icon but gravitybox only have 4 step lolipop signal icon, so stock signal appears instead of lolipop icon when signal is full. Also add option to disable RINGER_MODE_NORMAL statusbar icon. I have unnecessary speaker icon in statusbar.

**Comment by C3C0** [comment]
Lenovo devices are not officially supported. They come with system highly modified by manufacturer and it is impossible for me to target them without physically owning them. I'm sorry.
