### ISSUE TITLE
Immersive mode/expanded desktop not functioning

### ISSUE THREAD

**Issue by code-issues-pull** [GravityBox/GravityBox#1709]
Nexus6, 7.1.1 (stock rom/kernel)
GB 7.0.6

Adding expanded desktop to power menu doesn't show it in power menu.

Using the expanded desktop quick toggle added by GB does nothing and it remains disabled.

Other GB functions I use seem to work fine aside from this.

**Comment by C3C0** [comment]
Hi.

Make sure you set desired expanded desktop mode in Display tweaks.

Regards,
C.
