### ISSUE TITLE
[feature request] multiple progressbars along eachother in statusbar

### ISSUE THREAD

**Issue by iriman** [GravityBox/GravityBox#1713]
hi, thank you for this useful module. it was some time ago i was using cyanogen roms with some usefull tweaks and now this module has made almost all of them available for me again.
I have a suggestion for progress bar:
Is it possible to make more rooms up to 3 for progress bars in statusbar?
If there is one progress bar then it will fullfil the statusbar. if another one comes, the progressbar splits into two separate bars and if there are 3 progress bars, then it splits into 3 bars along each other with diffrent colors or a small number on them to distinguish between progress of first, second and third download. 
thanks

**Comment by zaaraameera2014** [comment]
Developer

**Comment by C3C0** [comment]
There is already support for more simultaneous progress bars. But they do not appear at once not to clutter screen. There is a cycling mechanism which cycles between multiple progress bars in 5 seconds interval.

**Comment by iriman** [comment]
I didn't know it. This is better than my suggestion, as it can handle more progresses.
thanks
