### ISSUE TITLE
Battery statusbar icon moves some slots to the left

### ISSUE THREAD

**Issue by shinizzle** [GravityBox/GravityBox#1718]
On  Oxygen OS 5.0.1 Oreo 8.0  xposed  v90 beta 2  the battery icon on  statusbar  works,  but  is shifted from the far right slot to le  left in front of wifi and  gsm  signal icons. 

![screenshot_20180125-175337_01 1](https://user-images.githubusercontent.com/35811499/35401190-1d55f9f4-01f9-11e8-8c08-d68f204f4249.jpg)

 I  am certainly not versed in android coding but i think the  BatteryStyleController.java  line 146 got something to do  with that. Furthermore  the system battery percentage can not be enabled anymore  after gb has been installed.

**Comment by C3C0** [comment]
Oxygenos compatibility is planned to be improved. I've got op3t which I can use for that purpose. It's still running Nougat, though.
