### ISSUE TITLE
Nav icons unreasonably small when shrinking nav bar height

### ISSUE THREAD

**Issue by jfjfivkfnd** [GravityBox/GravityBox#1719]
GB: 8.0 beta 1
OS: 8.1 with Jan update
Device: Nexus 5x

Settings were restored from Nougat. Nav icons are unreasonably small when adjusting nav bar height to even 75%. It appears the icons are scaling whereas before (I think) the nav bar size changed while the icons stayed the same size, or the scalping wasn't as drastic. Screen shot of 75% vs 100% ==> https://imgur.com/a/3rX63

**Comment by C3C0** [comment]
They changed the layout of the keys in Oreo again, including the way they scale and pad.
Also they are smaller than on Nougat. I had to do a dynamic padding recalculation based on navbar dimension to achieve scaling. https://github.com/GravityBox/GravityBox/blob/oreo/src/com/ceco/oreo/gravitybox/ModNavigationBar.java#L996
Maybe it would be enough to lower the factor.
