### ISSUE TITLE
Add option to use full status bar

### ISSUE THREAD

**Issue by rapperskull** [GravityBox/GravityBox#1720]
Is it possible to add an option to use the full status bar? I find the fact that the icons are no longer aligned to the edges very annoying, and it looks worse with the battery bar activated.

**Comment by C3C0** [comment]
Google messed up this one. They redesigned system bars for rounded-corner displays but they didn't make it optional so it applies to every device, not only those that really come with such a display. 
I will try to look at it later.

**Comment by rapperskull** [comment]
Thank you, I know about the rounded screen problem, but indeed they made a quick fix without thinking.

**Comment by rapperskull** [comment]
https://www.xda-developers.com/google-pixel-2-rounded-screen-corners/
Could this be helpful? Setting the padding to 0 worked on my Nexus 5X.

**Comment by C3C0** [comment]
ba20a4fa2ce64ae96e1377b6402f33123f27cb97
