### ISSUE TITLE
Back icon moves to close to home icon when cursor control keys enabled

### ISSUE THREAD

**Issue by ZoharML** [GravityBox/GravityBox#1723]
When I set the navigation bar-> cursor control keys, whenever the keyboard pops up, the "back" icon jumps to the right, and very near to the "home" icon.
The "hide IME switcher" value has no effect on this movement

Tested on Oneplus 5T running OOS oreo beta 2.

Back icon in correct position:
![screenshot_20180126-002403](https://user-images.githubusercontent.com/33901345/35458972-1f812b7e-02e7-11e8-94b9-cdc1efca8223.jpg)

Back icon in wrong position:
![screenshot_20180126-002426](https://user-images.githubusercontent.com/33901345/35458973-1fa85794-02e7-11e8-8e96-50fca1d92105.jpg)

**Comment by C3C0** [comment]
That's unfortunate. It works fine on OxygenOS 5.0.1 (stable) on my OP3T

**Comment by C3C0** [comment]
If possible, please share the following files:
/system/framework/framework-res.apk
/system/framework/oneplus-framework-res.apk
/system/priv-app/OPSystemUI

Then I will eventually be able to take a look how navbar on OOS beta is designed.

**Comment by ZoharML** [comment]
[gb[o] 1723.zip](https://github.com/GravityBox/GravityBox/files/1679510/gb.o.1723.zip)

**Comment by duckredbeard** [comment]
OOS has an option to hide the nav bar.  When hide is enabled it adds a small circle button on the left side of the nig bar to toggle it.  I did not have that option enabled when I had this anomaly.

**Comment by duckredbeard** [comment]
Forgot to mention… OP5T on OOS 5.0.3 Oreo 8.0.0.

**Comment by duckredbeard** [comment]
OOS has an option to hide the nav bar.  When hide is enabled it adds a small circle button on the left side of the nig bar to toggle it.  I did not have that option enabled when I had this anomaly.

**Comment by duckredbeard** [comment]
![screenshot_20180214-164213](https://user-images.githubusercontent.com/29324842/36229786-63184afc-11a6-11e8-86e8-4be1c655a9b7.jpg)
Here is that screenshot with the dot, without the cursor control enabled
![screenshot_20180214-164213](https://user-images.githubusercontent.com/29324842/36229772-5ccc7164-11a6-11e8-9822-23bb8cbe3ecf.jpg)

**Comment by duckredbeard** [comment]
OOS has an option to hide the nav bar.  When hide is enabled it adds a small circle button on the left side of the nig bar to toggle it.  I did not have that option enabled when I had this anomaly.

**Comment by duckredbeard** [comment]
![screenshot_20180214-164213](https://user-images.githubusercontent.com/29324842/36229831-8133e604-11a6-11e8-9bf5-da8b537eeba7.jpg)

**Comment by C3C0** [comment]
Yes, this additional button occupies slot that would normally been assigned to cursor control key.
Attached APK contains logic that changes OP navbar layout to a standard one. Please test just for curiosity. Note that most likely their additional button won't show due to this change.
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_Oreo_8.0.0_180215.apk

**Comment by ZoharML** [comment]
![untitled-1](https://user-images.githubusercontent.com/33901345/36250120-8a25ff82-1245-11e8-97da-582063319fe6.jpg)
I've installed the APK. 
It is much better, but still need to fix it a bit.
see the image.
line 1= original OOS, with out GravityBox. 
line 2= this APK, no keyboard on. both the rectangle and the box moved from the circle.
line 3 = this APK + keyboard on. still the rectangle and the box moved from the circle.
line 4 = with the previous version of GravityBox, no keyboard. same as the original OOS.

(1+2+3 are with BlackNavigationBar module)

Zohar

**Comment by C3C0** [comment]
Looks like there is no way for me to do adjustments without being able to work with a real device. Unfortunately.

**Comment by ZoharML** [comment]
I would have come to you with my phone to run this test but probebly we are not even from the same country.
I can offer you to test every apk you can trow on me and give back this kind of screen shoots.

**Comment by ZoharML** [comment]
I can also offer you to do a remote desktop connection to my PC.
I will install the development environment on my local PC and connect mt 5T to it.

**Comment by C3C0** [comment]
Please, if still relevant, could you test the last APK (WIP-4) linked thread regarding cursor control keys? Thanks.
https://github.com/GravityBox/GravityBox/issues/1909
