### ISSUE TITLE
[Feature-Request] Search Feature

### ISSUE THREAD

**Issue by Kronopt** [GravityBox/GravityBox#1724]
GravityBox provides 100+ features. Sometimes it can be a hassle if you want to find out if a given feature exists. A search function would be much appreciated in these cases.

Something like this (photoshopped):
![2018-01-27 16 26 042](https://user-images.githubusercontent.com/19473287/35474035-a4b69966-0380-11e8-8617-0e36bb1f18ef.png)

**Comment by C3C0** [comment]
I understand there are many options and search option would be useful but current implementation uses clean PreferenceScreen which does not allow such functionality. Settings part of the module would need to be redesigned from scratch and this is a problem for me as when I finally find time to work on GravityBox, it's always about taking care of functionality, compatibility fixes, adjustments, etc. UI would need a massive overhaul but there is currently no room for such activities. Maybe one day I'll get back to it, though.
