### ISSUE TITLE
QuickApp tile "breaks" after reboot

### ISSUE THREAD

**Issue by TheSysWiz** [GravityBox/GravityBox#1745]
Every time I reboot my Pixel 2 XL phone, the QuickApp tile icon turns into a question mark and does not work.  To fix, I have to click on the "edit pen" to get into edit mode, remove the QuickApp tile, exit edit mode, go back into edit mode and then re-add the QuickApp tile.

This has been the case since the first Oreo GravityBox was released.

**Comment by GT500x** [comment]
Curious if this is the same issue I encountered on my oneplus 5.

Seems that, at least on oxygen OS with fbe enabled, storage is not available prior to unlocking. When gravitybox tries to initialize the quick apps after boot (prior to unlocking) it can't access those apps and throws an exception. I thought this behavior was limited to OOS based on chat with @c3c0. 

I created a pull request to fix on OOS but might be needed for other devices as well. 

Would help if you could post a log. 

https://github.com/GravityBox/GravityBox/pull/1744

**Comment by C3C0** [comment]
Interesting. That would mean it would be worth it to not restrict your patches to oos only but make them for all fbe devices.
