### ISSUE TITLE
[Feature request] Disable "Statusbar Tweak --> Battery settings" option

### ISSUE THREAD

**Issue by VinhNgT** [GravityBox/GravityBox#1762]
Because it removes the stock the battery percent and the included "Battery percent text" looks kinda ugly :-\

BTW I'm using SS Note 5 with stock Nougat rom

**Comment by VinhNgT** [comment]
Edit: It's ugly because the text size of the time and the battery pecent is not the same, which makes the status bar "unbalanced" (aka ugly)

**Comment by C3C0** [comment]
Closed by f37bc9f6d8a0a674c671073d8c7db8f3baf1f6ae
