### ISSUE TITLE
[Bug report] Quick settings for network modes sometimes do not work.

### ISSUE THREAD

**Issue by RSDamasceno** [GravityBox/GravityBox#1792]
# Xposed logs & catalog bellow 

### Xposed logs:
03-06 00:52:37.619 I/Xposed  (  509): -----------------
03-06 00:52:37.619 I/Xposed  (  509): Starting Xposed version 90-beta3, compiled for SDK 27
03-06 00:52:37.619 I/Xposed  (  509): Device: XT1802 (motorola), Android version 8.1.0 (SDK 27)
03-06 00:52:37.619 I/Xposed  (  509): ROM: OPM1.171019.018
03-06 00:52:37.619 I/Xposed  (  509): Build fingerprint: google/walleye/walleye:8.1.0/OPM1.171019.011/4448085:user/release-keys
03-06 00:52:37.619 I/Xposed  (  509): Platform: arm64-v8a, 64-bit binary, system server: yes
03-06 00:52:37.619 I/Xposed  (  509): SELinux enabled: yes, enforcing: no
03-28 17:00:53.056 I/Xposed  (  509): -----------------
03-28 17:00:53.056 I/Xposed  (  509): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
03-28 17:00:54.875 I/Xposed  (  509): Detected ART runtime
03-28 17:00:54.877 I/Xposed  (  509): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
03-28 17:00:55.256 I/Xposed  (  509): Loading modules from /data/app/com.ceco.oreo.gravitybox-tZm3RSuseLu98haarA1gUg==/base.apk
03-28 17:00:55.377 I/Xposed  (  509):   Loading class com.ceco.oreo.gravitybox.GravityBox
03-28 17:00:55.392 I/Xposed  (  509): GB:Hardware: qcom
03-28 17:00:55.392 I/Xposed  (  509): GB:Product: Moto G5S Plus
03-28 17:00:55.392 I/Xposed  (  509): GB:Device manufacturer: motorola
03-28 17:00:55.392 I/Xposed  (  509): GB:Device brand: motorola
03-28 17:00:55.392 I/Xposed  (  509): GB:Device model: XT1802
03-28 17:00:55.395 I/Xposed  (  509): GB:Device type: phone
03-28 17:00:55.395 I/Xposed  (  509): GB:Is MTK device: false
03-28 17:00:55.395 I/Xposed  (  509): GB:Is Xperia device: false
03-28 17:00:55.397 I/Xposed  (  509): GB:Is Moto XT device: true
03-28 17:00:55.397 I/Xposed  (  509): GB:Is OxygenOS ROM: false
03-28 17:00:55.397 I/Xposed  (  509): GB:Has Lenovo custom UI: false
03-28 17:00:55.399 I/Xposed  (  509): GB:Has telephony support: true
03-28 17:00:55.399 I/Xposed  (  509): GB:Has Gemini support: false
03-28 17:00:55.399 I/Xposed  (  509): GB:Android SDK: 27
03-28 17:00:55.399 I/Xposed  (  509): GB:Android Release: 8.1.0
03-28 17:00:55.399 I/Xposed  (  509): GB:ROM: OPM1.171019.018
03-28 17:00:55.399 I/Xposed  (  509): GB:Error logging: false
03-28 17:01:00.497 I/Xposed  (  510): -----------------
03-28 17:01:00.497 I/Xposed  (  510): Starting Xposed version 90-beta3, compiled for SDK 27
03-28 17:01:00.497 I/Xposed  (  510): Device: XT1802 (motorola), Android version 8.1.0 (SDK 27)
03-28 17:01:00.497 I/Xposed  (  510): ROM: OPM1.171019.018
03-28 17:01:00.497 I/Xposed  (  510): Build fingerprint: google/walleye/walleye:8.1.0/OPM1.171019.011/4448085:user/release-keys
03-28 17:01:00.497 I/Xposed  (  510): Platform: arm64-v8a, 32-bit binary, system server: no
03-28 17:01:00.497 I/Xposed  (  510): SELinux enabled: yes, enforcing: no
03-28 17:01:03.023 I/Xposed  (  510): -----------------
03-28 17:01:03.023 I/Xposed  (  510): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
03-28 17:01:04.325 I/Xposed  (  510): Detected ART runtime
03-28 17:01:04.326 I/Xposed  (  510): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
03-28 17:01:04.579 I/Xposed  (  510): Loading modules from /data/app/com.ceco.oreo.gravitybox-tZm3RSuseLu98haarA1gUg==/base.apk
03-28 17:01:04.685 I/Xposed  (  510):   Loading class com.ceco.oreo.gravitybox.GravityBox
03-28 17:01:06.292 I/Xposed  ( 1562): GB:Is AOSP forced: false
03-28 17:15:21.865 I/XposedInstaller(11856): RepoLoader -> Downloaded http://dl.xposed.info/repo/partial/14609.xml.gz with status 0 (error: null), size 66 bytes
03-28 17:15:21.869 I/XposedInstaller(11856): RepoLoader -> Updated repository http://dl.xposed.info/repo/full.xml.gz to version 14609 (0 new / 0 removed modules)
03-28 17:41:32.703 I/XposedInstaller(23669): RepoLoader -> Downloaded http://dl.xposed.info/repo/partial/14609.xml.gz with status 0 (error: null), size 66 bytes
03-28 17:41:32.706 I/XposedInstaller(23669): RepoLoader -> Updated repository http://dl.xposed.info/repo/full.xml.gz to version 14609 (0 new / 0 removed modules)

### Logs: 
---- 28 de mar de 2018 18:29:53 ----

03-28 18:28:22.149  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:28:22.259  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:28:22.328  2724  2724 D PerAppMonitor: Package Name is com.android.systemui

03-28 18:28:22.991  2724  2724 D PerAppMonitor: Package Name is com.android.systemui

03-28 18:28:23.662  1100  1100 I rild_32 : type=1400 audit(0.0:4264): avc: denied { block_suspend } for uid=1001 capability=36 scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=capability2 permissive=1

03-28 18:28:24.728  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:28:25.071  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:28:25.792  2849  2849 W SearchService: Abort, client detached.

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: Network error

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: com.google.android.apps.gsa.shared.exception.GsaIOException: Error code: 660100 | Exception in CronetUrlRequest: net::ERR_CONNECTION_CLOSED, ErrorCode=5, InternalErrorCode=-100, Retryable=true

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at com.google.android.libraries.gsa.d.a.bg.d(SourceFile:26)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at com.google.android.libraries.gsa.d.a.bi.onFailed(SourceFile:163)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at org.chromium.net.impl.cu.onFailed(SourceFile:12)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at org.chromium.net.impl.ac.run(SourceFile:8)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at com.google.android.libraries.gsa.d.a.bn.run(SourceFile:2)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at com.google.android.apps.gsa.shared.util.concurrent.b.g.run(Unknown Source:4)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at com.google.android.apps.gsa.shared.util.concurrent.b.au.run(SourceFile:4)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at com.google.android.apps.gsa.shared.util.concurrent.b.au.run(SourceFile:4)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at java.lang.Thread.run(Thread.java:764)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at com.google.android.apps.gsa.shared.util.concurrent.b.i.run(SourceFile:6)

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: Caused by: org.chromium.net.impl.cf: Exception in CronetUrlRequest: net::ERR_CONNECTION_CLOSED, ErrorCode=5, InternalErrorCode=-100, Retryable=true

03-28 18:28:25.825  2849 22751 W VelvetNetworkClient: 	at org.chromium.net.impl.CronetUrlRequest.onError(SourceFile:213)

03-28 18:28:26.014  2724  2724 D PerAppMonitor: Package Name is scd.lcex

03-28 18:28:26.019  2724  2724 D PerAppMonitor: Profile does not exist. Using Default

03-28 18:28:26.804  4715  4748 D QcrilMsgTunnelSocket: readRilMessage: Buffer = [B@64aefd0 HexData = [010000000404000011000000514f454d484f4f4bef0308000100000003]

03-28 18:28:26.804  4715  4748 D QcrilMsgTunnelSocket: Rcvd UNSOL response with 28 bytes data for SUB0

03-28 18:28:26.804  4715  4748 D QcrilMsgTunnelSocket: Response ID 525295 is not served in this process.

03-28 18:28:26.804  4715  4748 D QcrilMsgTunnelSocket: To broadcast an Intent via the notifier to external apps

03-28 18:28:26.807  4715  4748 D QcrilMsgTunnelSocket: readRilMessage: Buffer = [B@64aefd0 HexData = [010000000404000011000000514f454d484f4f4bfa0308000100000000]

03-28 18:28:26.807  4715  4748 D QcrilMsgTunnelSocket: Rcvd UNSOL response with 28 bytes data for SUB0

03-28 18:28:26.807  4715  4748 D QcrilMsgTunnelSocket: Response ID 525306 is not served in this process.

03-28 18:28:26.807  4715  4748 D QcrilMsgTunnelSocket: To broadcast an Intent via the notifier to external apps

03-28 18:28:26.805  4715  4715 D QcrilMsgTunnelIfaceManager: handleMessage what = 0

03-28 18:28:26.818  4715  4715 D QcrilMsgTunnelIfaceManager: handleMessage what = 0

03-28 18:28:27.380  4715  4748 D QcrilMsgTunnelSocket: readRilMessage: Buffer = [B@64aefd0 HexData = [010000000404000011000000514f454d484f4f4bef0308000100000003]

03-28 18:28:27.380  4715  4748 D QcrilMsgTunnelSocket: Rcvd UNSOL response with 28 bytes data for SUB0

03-28 18:28:27.381  4715  4748 D QcrilMsgTunnelSocket: Response ID 525295 is not served in this process.

03-28 18:28:27.381  4715  4748 D QcrilMsgTunnelSocket: To broadcast an Intent via the notifier to external apps

03-28 18:28:27.381  4715  4748 D QcrilMsgTunnelSocket: readRilMessage: Buffer = [B@64aefd0 HexData = [010000000404000011000000514f454d484f4f4bfa0308000100000000]

03-28 18:28:27.381  4715  4748 D QcrilMsgTunnelSocket: Rcvd UNSOL response with 28 bytes data for SUB0

03-28 18:28:27.381  4715  4748 D QcrilMsgTunnelSocket: Response ID 525306 is not served in this process.

03-28 18:28:27.381  4715  4748 D QcrilMsgTunnelSocket: To broadcast an Intent via the notifier to external apps

03-28 18:28:27.381  4715  4715 D QcrilMsgTunnelIfaceManager: handleMessage what = 0

03-28 18:28:27.388  4715  4715 D QcrilMsgTunnelIfaceManager: handleMessage what = 0

03-28 18:28:30.849  2939  4117 W GAv4-SVC: Network compressed POST connection error: java.net.ConnectException: Failed to connect to ssl.google-analytics.com/::1:443

03-28 18:28:31.804  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:28:31.893  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:28:32.010  2724  2724 D PerAppMonitor: Package Name is com.android.systemui

03-28 18:28:32.434  2724  2724 D PerAppMonitor: Package Name is com.android.systemui

03-28 18:28:36.148  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:28:36.489  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:28:38.106  2724  2724 D PerAppMonitor: Package Name is scd.lcex

03-28 18:28:38.110  2724  2724 D PerAppMonitor: Profile does not exist. Using Default

03-28 18:28:40.763  1562  1816 E LightsService: Light requested not available on this device. 2

03-28 18:28:42.221  4715  4748 D QcrilMsgTunnelSocket: readRilMessage: Buffer = [B@64aefd0 HexData = [010000000404000011000000514f454d484f4f4bef0308000100000003]

03-28 18:28:42.221  4715  4748 D QcrilMsgTunnelSocket: Rcvd UNSOL response with 28 bytes data for SUB0

03-28 18:28:42.221  4715  4748 D QcrilMsgTunnelSocket: Response ID 525295 is not served in this process.

03-28 18:28:42.221  4715  4748 D QcrilMsgTunnelSocket: To broadcast an Intent via the notifier to external apps

03-28 18:28:42.221  4715  4715 D QcrilMsgTunnelIfaceManager: handleMessage what = 0

03-28 18:28:42.227  4715  4748 D QcrilMsgTunnelSocket: readRilMessage: Buffer = [B@64aefd0 HexData = [010000000404000011000000514f454d484f4f4bfa0308000100000000]

03-28 18:28:42.227  4715  4748 D QcrilMsgTunnelSocket: Rcvd UNSOL response with 28 bytes data for SUB0

03-28 18:28:42.227  4715  4748 D QcrilMsgTunnelSocket: Response ID 525306 is not served in this process.

03-28 18:28:42.227  4715  4748 D QcrilMsgTunnelSocket: To broadcast an Intent via the notifier to external apps

03-28 18:28:42.230  4715  4715 D QcrilMsgTunnelIfaceManager: handleMessage what = 0

03-28 18:28:43.501   562   562 I rmt_storage: rmt_storage_connect_cb: clnt_h=0x19 conn_h=0xf08970c8

03-28 18:28:43.501   562   562 I rmt_storage: rmt_storage_rw_iovec_cb: /boot/modem_fs1: clnt_h=0x19: req_h=0x19 msg_id=3: R/W request received

03-28 18:28:43.501   562   562 I rmt_storage: rw_iovec client->path = /boot/modem_fs1

03-28 18:28:43.501   562   562 I rmt_storage: wakelock acquired: 1, error no: 42

03-28 18:28:43.502   562  1148 I rmt_storage: rmt_storage_client_thread: /boot/modem_fs1: clnt_h=0x19 Unblock worker thread (th_id: -261187216)

03-28 18:28:43.699   562  1148 I rmt_storage: rmt_storage_client_thread: /boot/modem_fs1: clnt_h=0x19: req_h=0x19 msg_id=3: Bytes written = 1572864

03-28 18:28:43.699   562  1148 I rmt_storage: rmt_storage_client_thread: /boot/modem_fs1: clnt_h=0x19: req_h=0x19 msg_id=3: Send response: res=0 err=0

03-28 18:28:43.699   562  1148 I rmt_storage: rmt_storage_client_thread: /boot/modem_fs1: clnt_h=0x19 About to block rmt_storage client thread (th_id: -261187216) wakelock released: 1, error no: 0

03-28 18:28:43.699   562  1148 I rmt_storage: 

03-28 18:28:43.704   562   562 I rmt_storage: rmt_storage_disconnect_cb: clnt_h=0x19 conn_h=0xf08970c8

03-28 18:28:49.095  1562  1865 E LightsService: Light requested not available on this device. 2

03-28 18:28:50.427  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:28:50.564  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:28:50.678  2724  2724 D PerAppMonitor: Package Name is com.android.systemui

03-28 18:28:51.175  2724  2724 D PerAppMonitor: Package Name is com.android.systemui

03-28 18:28:52.667  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:28:53.014  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:28:54.557  2724  2724 D PerAppMonitor: Package Name is scd.lcex

03-28 18:28:54.562  2724  2724 D PerAppMonitor: Profile does not exist. Using Default

03-28 18:29:00.264 23757 23766 V MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false

03-28 18:29:00.264 23757 23766 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null

03-28 18:29:00.265   611  8719 D NuPlayerDriver: reset(0xe65c1000) at state 4

03-28 18:29:00.265   611  8719 D NuPlayerDriver: notifyListener_l(0xe65c1000), (8, 0, 0, -1), loop setting(0, 0)

03-28 18:29:00.266   611  3973 D NuPlayerDriver: notifyResetComplete(0xe65c1000)

03-28 18:29:00.267 23757 23766 V MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false

03-28 18:29:00.267 23757 23766 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null

03-28 18:29:00.267   611  8719 D NuPlayerDriver: reset(0xe7ea72a0) at state 4

03-28 18:29:00.268   611  8719 D NuPlayerDriver: notifyListener_l(0xe7ea72a0), (8, 0, 0, -1), loop setting(0, 0)

03-28 18:29:00.268   611  3976 D NuPlayerDriver: notifyResetComplete(0xe7ea72a0)

03-28 18:29:00.302   570   570 I surfaceflinger: type=1400 audit(0.0:4265): avc: denied { ioctl } for uid=1000 path="/dev/kgsl-3d0" dev="tmpfs" ino=7571 ioctlcmd=94a scontext=u:r:surfaceflinger:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1

03-28 18:29:01.430  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:29:01.635  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:29:01.664  2724  2724 D PerAppMonitor: Package Name is com.android.systemui

03-28 18:29:02.230  2724  2724 D PerAppMonitor: Package Name is com.android.systemui

03-28 18:29:04.603  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:29:04.946  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:29:05.709 31464 31464 D wpa_supplicant: wlan0: BSS: Remove id 4 BSSID 1c:5f:2b:5c:9f:38 SSID 'D-Link_DIR-615' due to wpa_bss_flush_by_age

03-28 18:29:05.710 31464 31464 D wpa_supplicant: wlan0: BSS: Remove id 5 BSSID c8:3a:35:42:6d:18 SSID 'TRAKINA_RJ' due to wpa_bss_flush_by_age

03-28 18:29:05.710 31464 31464 D wpa_supplicant: wlan0: BSS: Remove id 6 BSSID 20:aa:4b:c5:ca:e2 SSID 'Victor' due to wpa_bss_flush_by_age

03-28 18:29:05.710 31464 31464 D wpa_supplicant: p2p0: BSS: Remove id 4 BSSID 1c:5f:2b:5c:9f:38 SSID 'D-Link_DIR-615' due to wpa_bss_flush_by_age

03-28 18:29:05.710 31464 31464 D wpa_supplicant: p2p0: BSS: Remove id 5 BSSID c8:3a:35:42:6d:18 SSID 'TRAKINA_RJ' due to wpa_bss_flush_by_age

03-28 18:29:05.710 31464 31464 D wpa_supplicant: p2p0: BSS: Remove id 6 BSSID 20:aa:4b:c5:ca:e2 SSID 'Victor' due to wpa_bss_flush_by_age

03-28 18:29:05.725  2050  2065 I zygote64: Background concurrent copying GC freed 118130(4MB) AllocSpace objects, 80(1600KB) LOS objects, 49% free, 6MB/13MB, paused 185us total 100.607ms

03-28 18:29:05.725  2050  2059 W JavaBinder: BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.android.systemui.qs.external.TileLifecycleManager

03-28 18:29:05.727  2050  2059 I chatty  : uid=10037(com.android.systemui) ReferenceQueueD identical 8 lines

03-28 18:29:05.727  2050  2059 W JavaBinder: BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.android.systemui.qs.external.TileLifecycleManager

03-28 18:29:05.963  2724  2724 D PerAppMonitor: Package Name is scd.lcex

03-28 18:29:05.973  2724  2724 D PerAppMonitor: Profile does not exist. Using Default

03-28 18:29:11.051  1562 22155 E LightsService: Light requested not available on this device. 2

03-28 18:29:13.455  1562  1865 E LightsService: Light requested not available on this device. 2

03-28 18:29:13.564  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:29:13.709  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:29:13.750  2724  2724 D PerAppMonitor: Package Name is com.android.systemui

03-28 18:29:14.415  2724  2724 D PerAppMonitor: Package Name is com.android.systemui

03-28 18:29:17.978  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:29:18.322  2050  2050 D StatusBar: disable<e i a s b h r c s q >

03-28 18:29:19.894  2724  2724 D PerAppMonitor: Package Name is scd.lcex

03-28 18:29:19.903  2724  2724 D PerAppMonitor: Profile does not exist. Using Default

03-28 18:29:23.237  1562  1816 E LightsService: Light requested not available on this device. 2

03-28 18:29:42.787 29341  1836 D WhatsApp: LL_D M [216:ReaderThread] RECV <message from='status@broadcast' type='media' id='C1963F910309E3EF6516ADCDBF78B386' participant='5521981334258@s.whatsapp.net' phash='1:bR6SpZGW' t='1522272575' notify='Roberta%20Chaves'><enc v='2' type='pkmsg'>3%08%e5%85%f4%04%12!%05%e0mb%96P%fe%f0*%8a%e3%c7%01a%0a%8e%1b%df%eb%deL%bar%f4<*%eb%da%10%b1%184%15%1a!%05%f4~%10%b68j%1de%cd%caL%d6Wi%cdT%85%b5d%de3%82%ff8%015R%1c%a4-%93%09"%a2%013%0a!%05%98%d6%89%f7s;%90%842/%a2%f8%85%92%e8%03~%c9%1b%bbC%02%0bZ%c2%f9%d4s%d4%0bk%1f%10%04%18%00"p&%97%e9B%00]Z%c2%f4.J%f0%a5[%93%86v%83%be%8d%1fJ%a8%d3Y%8e%9f%f6zF]%0e%098%ca%af%a8%98+%b1%0c%ac%da%d9Q+u@%cd%13%e8%19%a7%c6%96%c2b%a7u6%de%a9%8a%0bZ%0bT%b5c%a6g{%b7h%c8%d8%98%a6%da%f3G(i4[%be%b6%91%1d%ee%ebz%d1%18rFZ%f8fDf%e5%190o%a4%25%88%82%bf%f7r%b4^%c0%9f%de%82%96%1a(%9b%84%d9%d5%060%02</enc></message>

03-28 18:29:42.878 29341 29413 D WhatsApp: LL_D M [178:WriterThread] SEND <receipt to='status@broadcast' id='C1963F910309E3EF6516ADCDBF78B386' participant='5521981334258@s.whatsapp.net'/>

03-28 18:29:44.079 29341 29413 D WhatsApp: LL_D M [178:WriterThread] SEND <presence type='unavailable'/>

03-28 18:29:44.093 29341 29413 D WhatsApp: LL_D M [178:WriterThread] SEND </stream:stream>

03-28 18:29:45.006 29341  1836 D WhatsApp: LL_D M [216:ReaderThread] RECV  

03-28 18:29:45.038  1562 22155 I ActivityManager: Killing 517:com.android.systemui:screenshot/u0a37 (adj 906): empty #17

03-28 18:29:45.054  1562  1808 W system_server: kill(-517, 9) failed: No such process

03-28 18:29:45.151  1562  1808 I chatty  : uid=1000(system) ActivityManager identical 6 lines

03-28 18:29:45.189  1562  1808 W system_server: kill(-517, 9) failed: No such process

03-28 18:29:45.189  1562  1808 I system_server: Successfully killed process cgroup uid 10037 pid 517 in 135ms

03-28 18:29:45.288  1562  1814 W ActivityManager: setHasOverlayUi called on unknown pid: 517

03-28 18:29:46.817 26103 26137 E AnalyticsUploader: error in uploading the analytic file

03-28 18:29:46.817 26103 26137 E AnalyticsUploader: com.instagram.common.p.f.a: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)

03-28 18:29:46.817 26103 26137 E AnalyticsUploader: 	at com.instagram.common.p.f.q.onError(:203094)

03-28 18:29:46.817 26103 26137 E AnalyticsUploader: 	at com.facebook.proxygen.JniHandler.onError(:72498)

03-28 18:29:46.817 26103 26137 E AnalyticsUploader: 	at com.facebook.proxygen.EventBase.loopForever(Native Method)

03-28 18:29:46.817 26103 26137 E AnalyticsUploader: 	at com.facebook.proxygen.HTTPThread.run(:72427)

03-28 18:29:46.817 26103 26137 E AnalyticsUploader: 	at com.instagram.common.p.f.g.run(:202626)

03-28 18:29:46.817 26103 26137 E AnalyticsUploader: 	at java.lang.Thread.run(Thread.java:764)

03-28 18:29:50.050  1562  1865 E LightsService: Light requested not available on this device. 2

03-28 18:29:52.604  2756  2756 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's

03-28 18:29:52.604  2756  2780 I zygote64: Do full code cache collection, code=252KB, data=151KB

03-28 18:29:52.605  2756  2780 I zygote64: After code cache collection, code=194KB, data=119KB

03-28 18:29:52.771  2724  2724 D PerAppMonitor: Package Name is scd.lcex

03-28 18:29:52.775  2724  2724 D PerAppMonitor: Profile does not exist. Using Default

03-28 18:29:53.408  2756  2756 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's

---- 28 de mar de 2018 18:29:53 ----

**Comment by C3C0** [comment]
1) You should enable Error logging in About menu of GravityBox to be able to see errors logged from GravityBox
2) Oreo version does not officially support Moto devices as I currently do not own any to be able to make adjustments

**Comment by RSDamasceno** [comment]
Sorry, there is no error related to GravityBox in this case. As I did not know that the long press function changed SIM configuration, I probably have switched to SIM 2 (currently empty) and simple pressing changed the corresponding SIM configuration.

Thank you!

P.S .: Please consider the long press option to send to #*#*4636*#*#. Via check box in GravityBox settings maybe.
