### ISSUE TITLE
something wrong with setting long press keyboard

### ISSUE THREAD

**Issue by xmflswood** [GravityBox/GravityBox#1835]
phone: G9287
android version: 7.0
I set the key "APP_SWITCH"(left to home) to screen shot while long press,but it actually do two things:
1.APP_SWITCH
2.screen shot

And it also happen the same with the key BACK(long press)
sorry for my little English,if it's neccesary,I would post a .gif for you.

**Comment by C3C0** [comment]
I am sorry but I cannot investigate nor fix in case it is a Samsung device running their customized OS as it would require me to physically own such device.
