### ISSUE TITLE
Missing "Switch Data Card" tile in quick settings

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1838]
After switching from gravitybox M to O, i noticed that the quicksettings tile to "Switch data card" is unavailable (OxygenOS). Could you please add it ?

**Comment by C3C0** [comment]
GravityBox does not have such tile. It was part of stock system. If it is not there it means they removed it.

**Comment by jsalatiel** [comment]
Thanks for let me know!
