### ISSUE TITLE
[Bug] Profile icons on status bar are removed - OnePlus 6

### ISSUE THREAD

**Issue by ThisIsGettingWeird** [GravityBox/GravityBox#1840]
On the one plus 6 the old style do not disturb star icon is placed on the status bar with the slider set to vibrate or silent modes. Also the silent mode icon is removed entirely when the phone is set to that mode.

Thanks

**Comment by C3C0** [comment]
Please, share your xposed log as I need to create a function to identify whether device is OP6 and disable responsible modification. This is as much as I can do at this moment as there is no way for me to make adjustments without testing myself.

**Comment by ThisIsGettingWeird** [comment]
Sure - here it is

01-03 09:11:06.788 I/Xposed  (  686): -----------------
01-03 09:11:06.788 I/Xposed  (  686): Starting Xposed version 90-beta3, compiled for SDK 27
01-03 09:11:06.788 I/Xposed  (  686): Device: ONEPLUS A6003 (OnePlus), Android version 8.1.0 (SDK 27)
01-03 09:11:06.788 I/Xposed  (  686): ROM: ONEPLUS A6003_22_180517
01-03 09:11:06.788 I/Xposed  (  686): Build fingerprint: OnePlus/OnePlus6/OnePlus6:8.1.0/OPM1.171019.011/05172042:user/release-keys
01-03 09:11:06.788 I/Xposed  (  686): Platform: arm64-v8a, 64-bit binary, system server: yes
01-03 09:11:06.788 I/Xposed  (  686): SELinux enabled: yes, enforcing: yes
01-03 09:11:06.803 I/Xposed  (  686): -----------------
01-03 09:11:06.803 I/Xposed  (  686): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
01-03 09:11:08.376 I/Xposed  (  686): Detected ART runtime
01-03 09:11:08.377 I/Xposed  (  686): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
01-03 09:11:08.571 I/Xposed  (  686): Loading modules from /data/app/cn.zhougy0717.xposed.niwatori-URaeyc3TbbvCgt-CdPLeZA==/base.apk
01-03 09:11:08.653 I/Xposed  (  686):   Loading class cn.zhougy0717.xposed.niwatori.Niwatori
01-03 09:11:08.698 I/Xposed  (  686): Loading modules from /data/app/com.mayulive.swiftkeyexi-JlvDrDvQEMZLwOScnBacxw==/base.apk
06-08 18:54:35.430 I/Xposed  (  686):   Loading class com.mayulive.swiftkeyexi.LoadPackageHook
06-08 18:54:35.433 I/Xposed  (  686): Loading modules from /data/app/com.ryansteckler.nlpunbounce-XnYK5rJ6XMsTziBrUjaH5w==/base.apk
06-08 18:54:35.470 I/Xposed  (  686):   Loading class com.ryansteckler.nlpunbounce.hooks.Wakelocks
06-08 18:54:35.476 I/Xposed  (  686): Loading modules from /data/app/com.oasisfeng.greenify-W0ap331TAYPlhjf-0bJcXA==/base.apk
06-08 18:54:35.552 I/Xposed  (  686):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
06-08 18:54:35.557 I/Xposed  (  686):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
06-08 18:54:35.557 I/Xposed  (  686): Loading modules from /data/app/com.yuanwofei.blacknavigationbar-O-cRAZb8oif_1K2h93pqRw==/base.apk
06-08 18:54:35.568 I/Xposed  (  686):   Loading class com.yuanwofei.blacknavigationbar.MainHook
06-08 18:54:35.569 I/Xposed  (  686): Loading modules from /data/app/com.ceco.oreo.gravitybox-BEXKvl6-9YoIuSzcVYgN0g==/base.apk
06-08 18:54:35.891 I/Xposed  (  686):   Loading class com.ceco.oreo.gravitybox.GravityBox
06-08 18:54:35.911 I/Xposed  (  686): GB:Hardware: qcom
06-08 18:54:35.911 I/Xposed  (  686): GB:Product: OnePlus6
06-08 18:54:35.911 I/Xposed  (  686): GB:Device manufacturer: OnePlus
06-08 18:54:35.911 I/Xposed  (  686): GB:Device brand: OnePlus
06-08 18:54:35.911 I/Xposed  (  686): GB:Device model: ONEPLUS A6003
06-08 18:54:35.911 I/Xposed  (  686): GB:Device type: phone
06-08 18:54:35.912 I/Xposed  (  686): GB:Is MTK device: false
06-08 18:54:35.912 I/Xposed  (  686): GB:Is Xperia device: false
06-08 18:54:35.912 I/Xposed  (  686): GB:Is Moto XT device: false
06-08 18:54:35.912 I/Xposed  (  686): GB:Is OxygenOS ROM: true
06-08 18:54:35.912 I/Xposed  (  686): GB:Has telephony support: true
06-08 18:54:35.912 I/Xposed  (  686): GB:Has Gemini support: false
06-08 18:54:35.912 I/Xposed  (  686): GB:Android SDK: 27
06-08 18:54:35.912 I/Xposed  (  686): GB:Android Release: 8.1.0
06-08 18:54:35.912 I/Xposed  (  686): GB:ROM: ONEPLUS A6003_22_180517
06-08 18:54:35.912 I/Xposed  (  686): GB:Error logging: false
06-08 18:54:42.224 I/Xposed  (  687): -----------------
06-08 18:54:42.224 I/Xposed  (  687): Starting Xposed version 90-beta3, compiled for SDK 27
06-08 18:54:42.224 I/Xposed  (  687): Device: ONEPLUS A6003 (OnePlus), Android version 8.1.0 (SDK 27)
06-08 18:54:42.224 I/Xposed  (  687): ROM: ONEPLUS A6003_22_180517
06-08 18:54:42.224 I/Xposed  (  687): Build fingerprint: OnePlus/OnePlus6/OnePlus6:8.1.0/OPM1.171019.011/05172042:user/release-keys
06-08 18:54:42.224 I/Xposed  (  687): Platform: arm64-v8a, 32-bit binary, system server: no
06-08 18:54:42.224 I/Xposed  (  687): SELinux enabled: yes, enforcing: yes
06-08 18:54:42.226 I/Xposed  (  687): -----------------
06-08 18:54:42.226 I/Xposed  (  687): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
06-08 18:54:43.113 I/Xposed  (  687): Detected ART runtime
06-08 18:54:43.114 I/Xposed  (  687): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
06-08 18:54:43.380 I/Xposed  (  687): Loading modules from /data/app/cn.zhougy0717.xposed.niwatori-URaeyc3TbbvCgt-CdPLeZA==/base.apk
06-08 18:54:43.463 I/Xposed  (  687):   Loading class cn.zhougy0717.xposed.niwatori.Niwatori
06-08 18:54:43.522 I/Xposed  (  687): Loading modules from /data/app/com.mayulive.swiftkeyexi-JlvDrDvQEMZLwOScnBacxw==/base.apk
06-08 18:54:44.478 I/Xposed  (  687):   Loading class com.mayulive.swiftkeyexi.LoadPackageHook
06-08 18:54:44.480 I/Xposed  (  687): Loading modules from /data/app/com.ryansteckler.nlpunbounce-XnYK5rJ6XMsTziBrUjaH5w==/base.apk
06-08 18:54:44.516 I/Xposed  (  687):   Loading class com.ryansteckler.nlpunbounce.hooks.Wakelocks
06-08 18:54:44.522 I/Xposed  (  687): Loading modules from /data/app/com.oasisfeng.greenify-W0ap331TAYPlhjf-0bJcXA==/base.apk
06-08 18:54:44.595 I/Xposed  (  687):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
06-08 18:54:44.600 I/Xposed  (  687):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
06-08 18:54:44.600 I/Xposed  (  687): Loading modules from /data/app/com.yuanwofei.blacknavigationbar-O-cRAZb8oif_1K2h93pqRw==/base.apk
06-08 18:54:44.655 I/Xposed  (  687):   Loading class com.ceco.oreo.gravitybox.GravityBox
06-08 18:54:45.907 I/Xposed  ( 1470): Amplify: Version 4.0.1
06-08 18:54:45.907 I/Xposed  ( 1470): Amplify: Attempting 19to21 AlarmHook
06-08 18:54:45.908 I/Xposed  ( 1470): Amplify: Successful 19to21 AlarmHook
06-08 18:54:45.908 I/Xposed  ( 1470): Amplify: Attempting 21 WakeLockHook
06-08 18:54:45.911 I/Xposed  ( 1470): Amplify: Successful 21 WakeLockHook
06-08 18:54:45.911 I/Xposed  ( 1470): Amplify: Attempting 23 ServiceHook
06-08 18:54:45.911 I/Xposed  ( 1470): Amplify: Standard Service hook failed.
06-08 18:54:45.911 I/Xposed  ( 1470): Amplify: Successful 23 ServiceHook
06-08 18:54:45.913 I/Xposed  ( 1470): GB:Is AOSP forced: false
06-08 18:54:49.853 E/Xposed  ( 2041): java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
06-08 18:54:49.853 E/Xposed  ( 2041): 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:388)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:373)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:168)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:168)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at cn.zhougy0717.xposed.niwatori.FlyingHelper.onSettingsLoaded(FlyingHelper.java:109)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at cn.zhougy0717.xposed.niwatori.FlyingHelper.onSettingsLoaded(FlyingHelper.java:133)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at cn.zhougy0717.xposed.niwatori.FlyingHelper.initialize(FlyingHelper.java:97)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at cn.zhougy0717.xposed.niwatori.FlyingHelper.<init>(FlyingHelper.java:42)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at cn.zhougy0717.xposed.niwatori.ModActivity.createFlyingHelper(ModActivity.java:50)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at cn.zhougy0717.xposed.niwatori.ModActivity$2.afterHookedMethod(ModActivity.java:124)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at com.android.internal.policy.DecorView.<init>(<Xposed>)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at com.android.internal.policy.PhoneWindow.generateDecor(PhoneWindow.java:2344)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2705)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at com.android.internal.policy.PhoneWindow.installDecor(<Xposed>)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:460)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:451)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at android.app.Dialog.setContentView(Dialog.java:539)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at android.inputmethodservice.InputMethodService.initViews(InputMethodService.java:859)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at android.inputmethodservice.InputMethodService.onCreate(InputMethodService.java:827)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at bwx.onCreate(PG:61)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3483)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at android.app.ActivityThread.-wrap4(Unknown Source:0)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1776)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at android.os.Looper.loop(Looper.java:164)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at android.app.ActivityThread.main(ActivityThread.java:6753)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at java.lang.reflect.Method.invoke(Native Method)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-08 18:54:49.853 E/Xposed  ( 2041): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
06-08 18:54:49.935 I/Xposed  ( 1470): Amplify: XposedReceiver has been successfully installed.
06-08 18:54:50.456 I/Xposed  ( 2051): NFW(ModPhoneStatusBar_N$2#afterHookedMethod): attached to status bar
06-08 18:55:12.665 I/Xposed  ( 2983): Exi/LoadPackageHook, Module loaded in com.touchtype.swiftkey
06-08 18:55:13.636 I/Xposed  ( 2983): Exi/LoadPackageHook, Finished priority work incom.touchtype.swiftkey

**Comment by C3C0** [comment]
Please, test with the following APK and report back:
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_Oreo_8.1.1-wip-4.apk

**Comment by ThisIsGettingWeird** [comment]
That's solved it! Thankyou!
