### ISSUE TITLE
[N] QuietMode quick settings do not allow select "Auto"

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1841]
When toggling the quicksettings tile for quiet mode, there is only ON, OFF and WEAR available. Could you please add an option to AUTO ? It would also be nice if we could select which modes would be cycled on tap. 

Thanks.

**Comment by C3C0** [comment]
Long-press to activate auto. Another long-press while during auto mode opens QuietHours settings.

**Comment by jsalatiel** [comment]
Perfect, thanks!
