### ISSUE TITLE
[N/O]  "Interactive Mode"  conflicts with "Override notification vibration"

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1842]
I have "Interactive Mode" set, so i should not get any vibration or sound if i am interacting with the device. But i have a few apps configured to override vibrate pattern and these appears to vibrate despite the interactive mode setting.

I am attaching the screenshot of the configuration. Whatsapp always vibrate despite i am using the device or not.

I also think there is a little problem with the "Interactive Mode" randomly not working at all (sounding and vibrating), i dont know if you test if it is interactive using the powerManager.isInteractive(), but this method has flaws. I saw some comments that if powerManager.isInteractive() returns false, you should also check  using display manager if the screen is on. Well, maybe a improvement.

Thanks!

![screenshot_20180608-142435](https://user-images.githubusercontent.com/5522389/41171994-c19e8362-6b28-11e8-811a-8a08bac80a39.jpg)
![screenshot_20180608-142516](https://user-images.githubusercontent.com/5522389/41171995-c1ba8512-6b28-11e8-8dc2-af914dfc427e.jpg)

**Comment by C3C0** [comment]
Interactive mode depends on "Mute notification vibrations". If it's disabled, notifications will vibrate during interactive mode.

**Comment by C3C0** [comment]
Regarding "isInteractive" theory - it doesn't play role as interactive mode is based on a different rule - if user is present on the device (which means device is on and lock screen is not showing). This is detected by listening on ACTION_USER_PRESENT broadcast that system sends as soon as user has bypassed the lock screen.

**Comment by C3C0** [comment]
On a side note, I will have to reword mute vibrations options as they no longer work on Android Wear 2.0. Unfortunately, Wear 2.0 has independent notification vibration handling (due to built in option for various patterns) so it no longer respects notification vibration attributes set by apps.

**Comment by jsalatiel** [comment]
@C3C0 Thanks, it works if enabling "Mute notifications vibrations". But i have a question, what exactly "mute device vibration" does ? The help text says "Turns off ALL vibrations **including notification vibrations** ... except on wear" thats why i thought that i should use this + wear mode to get full silent mode on the mobile while still vibrating the wear. i always thought that mute notification vibrations and mute device vibration were mutually exclusive. Anyway, thanks! I am using "Mute notification vibration" + Wear mode and also disabled "Turns off ALL vibrations" to achieve what i want. About the isInteractive theory, i will try to build a tasker profile to check for this and see if somehow this is not being broadcasted when gravitybox's "mute on interactive" behaves strange.

**Comment by jsalatiel** [comment]
For now i am using wear 1.5, but very soon i will buy one wear 2.0 device and i can help you with feedbacks if you need.

**Comment by jsalatiel** [comment]
I almost forgot, wouldn't be possible add an option to allow "Mute interactive" also ignore per app rules? By default, it is nice to have it respect those, but it would be nice if we have the option to also ignore them.

**Comment by C3C0** [comment]
Mute notification vibrations - it sets an attribute of each notification to suppress a vibration. This attribute is part of what devs can set at notification level. Mute device vibrations hooks on vibrator service thus any request to vibrate that comes whether from notification service or any app directly using vibrator service (e.g. haptic feedback) is suppressed. This method doesn't alter notification vibrate attributes that's why notifications coming to wear device can still vibrate.
However, things changed in Wear 2.0 in such way that it doesn't respect notification vibrate attributes set by app sending notification but rather uses own built in vibration logic based on wear settings (normal, short, long, double). This has another drawback and it's that custom vibrate patterns on wear no longer work.
Edit: I have Huawei watch (the old version) running wear 2.0 so behavior I described is based on real experience.

**Comment by jsalatiel** [comment]
Should i close this ? or leave opened to let others understand the difference between those modes ?

**Comment by C3C0** [comment]
It can be read also when closed. I am going to reference this thread in a commit dealing with updated Mute option descriptions

**Comment by C3C0** [comment]
Also I'll try to add option for interactive mode regarding ignoring quiet hours as suggested.

**Comment by jsalatiel** [comment]
Thanks! It will be great have this option!
