### ISSUE TITLE
Data traffic monitor overlaps wear mode icon

### ISSUE THREAD

**Issue by jsalatiel** [GravityBox/GravityBox#1843]
Just a "cosmetic" issue.

![screenshot_20180609-090848](https://user-images.githubusercontent.com/5522389/41191460-33221740-6bc6-11e8-9dcb-f6f2edfa1c67.jpg)

**Comment by C3C0** [comment]
Yes, this is a common issue in case of elements centered in status bar (centered clock, traffic monitor) as centered layout is an independent layout overlaying status bar window. The solution is change position option of traffic monitor to the right (which makes it part of system icon area) or left (which makes it part of notification area).

**Comment by jsalatiel** [comment]
Thanks! good to know.
