### ISSUE TITLE
Screen continuously wakes up every few seconds

### ISSUE THREAD

**Issue by Kronopt** [GravityBox/GravityBox#1859]
Nexus 5
Android M 6.0.1 Build M4B30Z
Xposed Framework 89
GravityBox 6.5.1

Every time the screen is turned off (either by pressing the menu button or by letting it time out to sleep) it wakes up automatically after a few seconds.
This only happens with GB 6.5.1.
As soon as I reverted back to 6.5.0 it ceases to happen.

**Comment by C3C0** [comment]
Did you check if there were any errors in the Xposed log? (Note, that "Error logging" needs to be enabled in About menu)
