### ISSUE TITLE
"Settings backup" doesn't backup "Ultimate Notification Control" Default settings and Per-app settings

### ISSUE THREAD

**Issue by Kronopt** [GravityBox/GravityBox#1860]
Nexus 5
Android M 6.0.1 Build M4B30Z
Xposed Framework 89
GravityBox 6.5.1

Noticed this as I was reverting from 6.5.1 to 6.5.0.
I don't know about "Active Screen" and "Quiet hours" settings though, as I don't use them.

**Comment by C3C0** [comment]
Make sure you rebooted right after restoring the settings.

**Comment by Kronopt** [comment]
I tried it again and it worked fine this time.
But it's weird, as I did restart the first time (it shows a message requesting a restart).
