### ISSUE TITLE
Lockscreen custom wallpaper issue

### ISSUE THREAD

**Issue by flamendless** [GravityBox/GravityBox#1862]
Hi, using the latest version of gb for marshmallow, the custom wallpaper for lockscreen doesn't work after the latest update. After selecting and cropping the image, the gb crashes. 

_Sent from my Liquid Zest 4G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by C3C0** [comment]
Please provide logcat of a crash. There weren't any changes in this area for quite some time.

**Comment by flamendless** [comment]
> There weren't any changes in this area for quite some time.

I know, it's been working before, but after the update, it didnt anymor.

Using the command : `adb logcat | grep "GravityBox"`

Here's the output up to the `GravityBox has stopped` error
`
07-16 10:35:00.775   337  2371 I BufferQueueProducer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xaf220000,id:9913,api:1,p:30847,c:337) queueBuffer: fps=0.78 dur=23138.03 max=22339.50 min=9.42
07-16 10:35:00.865   982  1975 V WindowManager: Changing focus from Window{1c55f9 u0 com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings} to Window{a571649 u0 Lockscreen tweaks} Callers=com.android.server.wm.WindowManagerService.addWindow:2874 com.android.server.wm.Session.addToDisplay:171 android.view.IWindowSession$Stub.onTransact:124 com.android.server.wm.Session.onTransact:133 
07-16 10:35:00.867   982  1045 I WindowManager: Focus moving from Window{1c55f9 u0 com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings} to Window{a571649 u0 Lockscreen tweaks}
07-16 10:35:01.150   982  1045 I WindowManager: Losing delayed focus: Window{1c55f9 u0 com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings}
07-16 10:35:03.991   982  1768 V WindowManager: Set focused app to: AppWindowToken{9986e5a token=Token{df1ce05 ActivityRecord{c99857c u0 com.ceco.marshmallow.gravitybox/.PickImageActivity t603}}} old focus=AppWindowToken{214e8a8 token=Token{1b1a8cb ActivityRecord{234979a u0 com.ceco.marshmallow.gravitybox/.GravityBoxSettings t603}}} moveFocusNow=true
07-16 10:35:04.002 30847 30847 D ActivityThread: ACT-AM_ON_PAUSE_CALLED ActivityRecord{b11ccb5 token=android.os.BinderProxy@bf17f4a {com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings}}
07-16 10:35:04.020 30847 30847 V ActivityThread: ActivityRecord{40a96d2 token=android.os.BinderProxy@ae263a3 {com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.PickImageActivity}}: app=com.ceco.marshmallow.gravitybox.GravityBoxApplication@14fcfd8, appName=com.ceco.marshmallow.gravitybox, pkg=com.ceco.marshmallow.gravitybox, comp={com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.PickImageActivity}, dir=/data/app/com.ceco.marshmallow.gravitybox-1/base.apk
07-16 10:35:04.755 30847 30847 V ActivityThread: Finishing stop of ActivityRecord{b11ccb5 token=android.os.BinderProxy@bf17f4a {com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings}}: show=true win=com.android.internal.policy.PhoneWindow@8a633c9
07-16 10:35:05.452 30847 30847 V PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =ViewRoot{26a26e5 com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings,ident = 1}, this =com.android.internal.policy.PhoneWindow$DecorView{80f5b5f I.E...... R......D 0,0-720,1280}
07-16 10:35:05.483   337  1149 I BufferQueueProducer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xaf220000,id:9913,api:1,p:-1,c:337) disconnect(P): api 1
07-16 10:35:05.484   337  1149 I BufferQueueConsumer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xaf220000,id:9913,api:1,p:-1,c:337) getReleasedBuffers: returning mask 0xffffffffffffffff
07-16 10:35:05.497   337  2371 I BufferQueueProducer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xaf220000,id:9913,api:1,p:-1,c:337) disconnect(P): api 1
07-16 10:35:06.610   337   337 I BufferQueueConsumer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xaf220000,id:9913,api:1,p:-1,c:-1) disconnect(C)
07-16 10:35:06.612   337   337 I BufferQueue: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xaf220000,id:9913,api:1,p:-1,c:-1) ~BufferQueueCore
07-16 10:35:11.301 30847 30847 V PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{26a26e5 com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings,ident = 1}, this =com.android.internal.policy.PhoneWindow$DecorView{80f5b5f V.E...... R.....ID 0,0-720,1280}
07-16 10:35:11.410   337   337 D BufferQueueDump: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings] this:0xb5d60280, value:0xbea946b8, iLen:6
07-16 10:35:11.410   337   337 I BufferQueueConsumer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xb297c000,id:9919,api:0,p:-1,c:337) setConsumerName: com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings
07-16 10:35:11.410   337   337 I BufferQueueConsumer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xb297c000,id:9919,api:0,p:-1,c:337) setDefaultBufferSize: width=720 height=1280
07-16 10:35:11.422 30847 30861 D OpenGLRenderer: CanvasContext() 0xa9d67800 initialize window=0xaeb86608, title=com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings
07-16 10:35:11.423   337  2371 I BufferQueueProducer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xb297c000,id:9919,api:1,p:30847,c:337) connect(P): api=1 producer=(30847:com.ceco.marshmallow.gravitybox) producerControlledByApp=true
07-16 10:35:11.428   337   525 D BufferQueueProducer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xb297c000,id:9919,api:1,p:30847,c:337) allocateBuffers: allocating from 4 buffers up to 4 buffers
07-16 10:35:11.574   337   525 I BufferQueueProducer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xb297c000,id:9919,api:1,p:30847,c:337) new GraphicBuffer needed
07-16 10:35:11.584   337   527 I BufferQueueProducer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xb297c000,id:9919,api:1,p:30847,c:337) new GraphicBuffer needed
07-16 10:35:11.942   982  1045 D ActivityManager: ACT-IDLE_NOW_MSG from windowsVisible() for idle: ActivityRecord{234979a u0 com.ceco.marshmallow.gravitybox/.GravityBoxSettings t603}
07-16 10:35:12.406   337   666 I BufferQueueProducer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xb297c000,id:9919,api:1,p:30847,c:337) new GraphicBuffer needed
07-16 10:35:12.442 30847 30847 V PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =ViewRoot{26a26e5 com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings,ident = 1}, this =com.android.internal.policy.PhoneWindow$DecorView{80f5b5f I.E...... R......D 0,0-720,1280}
07-16 10:35:12.455   337   666 I BufferQueueProducer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xb297c000,id:9919,api:1,p:-1,c:337) disconnect(P): api 1
07-16 10:35:12.456   337   666 I BufferQueueConsumer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xb297c000,id:9919,api:1,p:-1,c:337) getReleasedBuffers: returning mask 0xffffffffffffffff
07-16 10:35:12.463   337   525 I BufferQueueProducer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xb297c000,id:9919,api:1,p:-1,c:337) disconnect(P): api 1
07-16 10:35:12.544  2084  2084 D ClipboardActionsAccessibilityService: EventType: TYPE_WINDOW_STATE_CHANGED; EventTime: 411977790; PackageName: com.ceco.marshmallow.gravitybox; MovementGranularity: 0; Action: 0 [ ClassName: com.ceco.marshmallow.gravitybox.PickImageActivity; Text: [GravityBox [MM]]; ContentDescription: null; ItemCount: -1; CurrentItemIndex: -1; IsEnabled: true; IsPassword: false; IsChecked: false; IsFullScreen: true; Scrollable: false; BeforeText: null; FromIndex: -1; ToIndex: -1; ScrollX: -1; ScrollY: -1; MaxScrollX: -1; MaxScrollY: -1; AddedCount: -1; RemovedCount: -1; ParcelableData: null ]; recordCount: 0
07-16 10:35:12.893   337   337 I BufferQueueConsumer: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xb297c000,id:9919,api:1,p:-1,c:-1) disconnect(C)
07-16 10:35:12.894   337   337 I BufferQueue: [com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings](this:0xb297c000,id:9919,api:1,p:-1,c:-1) ~BufferQueueCore
07-16 10:35:15.299 30847 30847 V PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{26a26e5 com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.GravityBoxSettings,ident = 1}, this =com.android.internal.policy.PhoneWindow$DecorView{80f5b5f V.E...... R.....ID 0,0-720,1280}
07-16 10:35:15.315   982  1829 V WindowManager: Set focused app to: AppWindowToken{214e8a8 token=Token{1b1a8cb ActivityRecord{234979a u0 com.ceco.marshmallow.gravitybox/.GravityBoxSettings t603}}} old focus=AppWindowToken{9986e5a token=Token{df1ce05 ActivityRecord{c99857c u0 com.ceco.marshmallow.gravitybox/.PickImageActivity t603}}} moveFocusNow=true
07-16 10:35:15.507  2084  2084 D ClipboardActionsAccessibilityService: EventType: TYPE_WINDOW_STATE_CHANGED; EventTime: 411980754; PackageName: android; MovementGranularity: 0; Action: 0 [ ClassName: com.android.server.am.AppErrorDialog; Text: [Unfortunately, GravityBox [MM] has stopped., OK]; ContentDescription: null; ItemCount: -1; CurrentItemIndex: -1; IsEnabled: true; IsPassword: false; IsChecked: false; IsFullScreen: false; Scrollable: false; BeforeText: null; FromIndex: -1; ToIndex: -1; ScrollX: -1; ScrollY: -1; MaxScrollX: -1; MaxScrollY: -1; AddedCount: -1; RemovedCount: -1; ParcelableData: null ]; recordCount: 0
`

**Comment by C3C0** [comment]
Please, use adb logcat *:E instead of output filtered by grep. I need to see the whole stack trace of crash. Thanks.

**Comment by flamendless** [comment]
Okay, here's the output
```
07-16 18:04:03.761   349  1305 E DrmMtkUtil/DrmUtil: checkDcf: not dcf type, dcf version value [79]
07-16 18:04:03.761   349  1305 E Cta5File: Cta5File::isCta5NormalFile false, bad magic:OggS
07-16 18:04:03.761   349  1305 E Cta5File: Cta5File::isCta5MultimediaFile false, bad magic:¶ÊáwI¡P
07-16 18:04:03.770   348  1695 E DrmMtkUtil/DrmUtil: parseDcf: not dcf type, dcf version value [79]
07-16 18:04:03.770   348  1695 E DrmMtkPlugIn: onOpenDecryptSession() : failed to parse dcf file.
07-16 18:04:03.780   349 21622 E APEExtractor: getAPEInfo not ape 5004
07-16 18:04:03.782   349 21622 E         : unknown object: 5367674f-200-0-00000000000069ec, 40019 bytes
07-16 18:04:03.783   349 21622 E         : error parsing header: -6
07-16 18:04:03.820   663   663 E AndroidRuntime: FATAL EXCEPTION: main
07-16 18:04:03.820   663   663 E AndroidRuntime: Process: com.ceco.marshmallow.gravitybox, PID: 663
07-16 18:04:03.820   663   663 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { dat=file://storage/emulated/0/Pictures/_20180716_180403.JPG (has extras) }} to activity {com.ceco.marshmallow.gravitybox/com.ceco.marshmallow.gravitybox.PickImageActivity}: java.lang.IllegalArgumentException: Unknown URL file://storage/emulated/0/Pictures/_20180716_180403.JPG
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3929)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3972)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:175)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:111)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5728)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
07-16 18:04:03.820   663   663 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unknown URL file://storage/emulated/0/Pictures/_20180716_180403.JPG
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at android.content.ContentResolver.delete(ContentResolver.java:1372)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at com.ceco.marshmallow.gravitybox.PickImageActivity.sendResult(PickImageActivity.java:192)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at com.ceco.marshmallow.gravitybox.PickImageActivity.onActivityResult(PickImageActivity.java:128)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6500)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3925)
07-16 18:04:03.820   663   663 E AndroidRuntime: 	... 10 more
```

**Comment by C3C0** [comment]
Thanks. Please try with the following APK and report back.
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_Marshmallow_6.5.2-wip1.apk

**Comment by flamendless** [comment]
Still error. A toast says
```
Open failed: ENOENT (no such file pr directory)
```

**Comment by C3C0** [comment]
Your photo app may not be compatible with File URLs. Try using another one. E.g. Google Photos to see whether it works.

**Comment by C3C0** [comment]
OK. I reverted changes ported from Nougat and got back to old-school direct file access method. Please try with the following APK:
http://ceco.sk.eu.org/GooMirror/GravityBox/GravityBox_Marshmallow_6.5.2-wip2.apk

**Comment by flamendless** [comment]
Alright it works now! Thanks
