### ISSUE TITLE
Battery statusbar icon has a right padding

### ISSUE THREAD

**Issue by YassGo** [GravityBox/GravityBox#1889]
On my OnePlus 5 with latest OxygenOS 8.1, the battery statusbar icon has a right padding space compared to default one. 
[Xposed.log](https://github.com/GravityBox/GravityBox/files/2572415/Xposed.log)

**Comment by C3C0** [comment]
Please:
- post a screenshot with "Layout bounds" enabled in developer settings
- did you try hiding stock battery icon in OOS settings to check if padding behavior is the same?

**Comment by YassGo** [comment]
YesvI tried to hide but the issue stills there. I'll post screenshots with and without the GB battery icon.
![screenshot_20181113-085319](https://user-images.githubusercontent.com/10463716/48400506-ce41ea80-e726-11e8-927d-968925c5f297.jpg)
![screenshot_20181113-085326](https://user-images.githubusercontent.com/10463716/48400507-ce41ea80-e726-11e8-91b1-e109592ee4de.jpg)

**Comment by C3C0** [comment]
OK. Thanks. Can you test with attached version?
[GravityBox_Oreo_8.4.0_WIP.zip](https://github.com/GravityBox/GravityBox/files/2584054/GravityBox_Oreo_8.4.0_WIP.zip)

**Comment by YassGo** [comment]
It seems okay now !
![screenshot_20181115-084759](https://user-images.githubusercontent.com/10463716/48538181-0aef1c80-e8b4-11e8-9ed3-4bd30ecc3064.jpg)
![screenshot_20181115-084749](https://user-images.githubusercontent.com/10463716/48538188-0f1b3a00-e8b4-11e8-9df6-e62dac316a03.jpg)
