### ISSUE TITLE
Data traffic monitor is not shown on mobile data network.

### ISSUE THREAD

**Issue by lucianomex** [GravityBox/GravityBox#1890]
**Problem:**
Data traffic monitor is not shown on mobile data network.

**Description:**
Data traffic monitor is working only on wifi connection, even if is checked "mobile data only" is not working on mobile data connection. Both Omni and simple style are not working on mobile data.

**ROM info**
Moto G5 Plus (XT1687) Android 8.1 stock version (security patch aug 01/18).
Xposed v90.2-beta 3 Systemless

**Module version** 
GravityBox [O] 8.4.0

**Screenshots**
On Wifi connection is working fine.
![Wifi ON](https://i.imgur.com/V9E38Dm.png)

On data mobile connection is not working.
![Wifi off, data mobile on](https://i.imgur.com/wlbUidm.png)

Even if mobile data only is selected is not working.
![Wifi off, data mobile on, mobile data only on](https://i.imgur.com/PKub6CE.png)

**Xposed Log**
[xposed_error_.log](https://github.com/GravityBox/GravityBox/files/2587706/xposed_error_20181115_201516.log)

Thank you.

**Comment by C3C0** [comment]
I will try to put 8.1 on my Moto G5p when I have more time and only then I will be able to tell where the problem is and whether it's fixable.

**Comment by lucianomex** [comment]
Thank you very much for your answer.

**Comment by C3C0** [comment]
I just tested on 8.1.0_OPS28.85-17 and it seems to be working OK. Tried with both SIM slots.
![screenshot_20181207-093742](https://user-images.githubusercontent.com/1543473/49636865-22797b00-fa04-11e8-8005-cf263a9018c7.png)

**Comment by lucianomex** [comment]
A clean install of the ROM, Magisk and Xposed solved the issue.

Thank you for taking your time to check.

**Comment by andronoob** [comment]
I guess that this problem might be caused by the data saver mode.
