### ISSUE TITLE
[Feature request] Turn on flash-light when long press power btn on screen off.

### ISSUE THREAD

**Issue by kmvan** [GravityBox/GravityBox#1892]
Phone: Samsung s9+ G9650
OS: Android 8.0

The Samsung OS has not this feature, but I think that it's very convenient feature when I am in dark.
Thanks.

**Comment by Kronopt** [comment]
That's already a feature.
At least pre android 8.0.
Search the settings for "torch" and see if you find it

**Comment by kmvan** [comment]
@Kronopt Thanks the reply. The samsung OS does not include this feature.
![image](https://user-images.githubusercontent.com/3839554/49693350-0d8b1c00-fbab-11e8-9bb7-ff3a984c2b75.png)

**Comment by Kronopt** [comment]
I meant to say that it's already a GravityBox feature.
Search the settings of GravityBox for "torch".

**Comment by kmvan** [comment]
@Kronopt Oh, got it. Thanks.
