### ISSUE TITLE
[Feature Request] Application launcher as shortcut

### ISSUE THREAD

**Issue by flamendless** [GravityBox/GravityBox#1896]
Title sums it up, have gb allow other app to use gb's application launcher by adding it as a shortcut so users can use it aside from navbar and buttons

_Sent from my Liquid Zest 4G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by C3C0** [comment]
Already possible. Use GravityBox actions. You can test by adding GravityBox widget (shortcut) to launcher home screen. Choose "Show application launcher" from the list of available actions.

**Comment by flamendless** [comment]
Oh okay, thanks
