### ISSUE TITLE
custom key is disturbing the nav bar layout - Oneplus 6

### ISSUE THREAD

**Issue by GorvGoyl** [GravityBox/GravityBox#1909]
When I enable the custom key, the back key (left side) moves towards the centre and collapse with the centre home key.
Please see the screenshots to understand.
Device: OnePlus 6, Android Oreo 8.1

menu key is working fine as exected.
let me know if you need further support, I would really like to have this bug fixed :)

![screenshot_20190219-130556__01](https://user-images.githubusercontent.com/7106086/52990200-7237e200-344a-11e9-828c-23656bf09a9a.jpg)
![screenshot_20190219-130604__01](https://user-images.githubusercontent.com/7106086/52990198-706e1e80-344a-11e9-9e8c-c79f29b4ae88.jpg)

**Comment by C3C0** [comment]
I recently have made some improvements in Pie version so it is worth trying how this will behave on Oreo. Attached is the APK to test. Note, that there may still be some specialties in navigation bar added by OnePlus which could affect compatibility. Those things are hard to analyze without physically owning a device.
[GravityBox-8.5.0-WIP.zip](https://github.com/GravityBox/GravityBox/files/2878838/GravityBox-8.5.0-WIP.zip)

**Comment by GorvGoyl** [comment]
tried but didn't work,how can i help you fix this (except from shipping my device :P). should i provide you some system framework file to analyse 
the code ?

**Comment by C3C0** [comment]
Can you post a screenshot with "Show layout bounds" (developer options) enabled?
Also if you could get me a fully decompiled SystemUI, it would maybe help.

**Comment by GorvGoyl** [comment]
![screenshot_20190220-124052](https://user-images.githubusercontent.com/7106086/53064962-0c605e80-350d-11e9-8279-8f11fc3d87d9.jpg)
![screenshot_20190220-124106](https://user-images.githubusercontent.com/7106086/53064968-0f5b4f00-350d-11e9-811c-d25ebe5e8a9a.jpg)

**Comment by C3C0** [comment]
OK. Can you pull system files form your device? I need:
- contents of /system/framework
- contents of /system/priv-app/OPSystemUI (or SystemUI if not present)
Please, ZIP and share if possible.

**Comment by JerryGoyal** [comment]
https://drive.google.com/drive/u/0/folders/1Ahe0zTg6z8YfkE7I-yhZp5CFAFvFeAPD

**Comment by GorvGoyl** [comment]
I tried to decompile OPSystemUI online but failed, it seems decompiling SystemUI is bit complicated because of dependency on framework file. Anyway I've added those system apk files to drive in case it helps you https://drive.google.com/drive/u/0/folders/1Ahe0zTg6z8YfkE7I-yhZp5CFAFvFeAPD

I'll try again to decompile offline and share the source code if i succeed

**Comment by GorvGoyl** [comment]
do you need all the files under 

> OK. Can you pull system files form your device? I need:
> 
> * contents of /system/framework
> * contents of /system/priv-app/OPSystemUI (or SystemUI if not present)
>   Please, ZIP and share if possible.

do you need all the files inside framework folder or source code of framework apk?

**Comment by C3C0** [comment]
Let's start with framework-res.apk and oneplus-framework-res.apk
Plus full  /system/priv-app/OPSystemUI

**Comment by GorvGoyl** [comment]
I've decompiled however can't upload the code now due to company strict policies.. i know it sounds strange.. I will send you the code when I reach home from the personal laptop in next 5-6 hrs

**Comment by C3C0** [comment]
Could you at least post contents of SystemUI/res/layout/navigation_layout.xml and also value of config_navBarLayout from res/values ?
Thanks.

**Comment by GorvGoyl** [comment]
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout android:layout_width="fill_parent" android:layout_height="fill_parent" android:paddingStart="@dimen/nav_content_padding" android:paddingEnd="@dimen/nav_content_padding" android:layout_marginStart="@dimen/rounded_corner_content_padding" android:layout_marginEnd="@dimen/rounded_corner_content_padding"
  xmlns:android="http://schemas.android.com/apk/res/android" xmlns:systemui="http://schemas.android.com/apk/res-auto">
    <com.android.systemui.statusbar.phone.NearestTouchFrame android:id="@id/nav_buttons" android:layout_width="fill_parent" android:layout_height="fill_parent">
        <LinearLayout android:orientation="horizontal" android:id="@id/ends_group" android:clipChildren="false" android:layout_width="fill_parent" android:layout_height="fill_parent" />
        <LinearLayout android:gravity="center" android:orientation="horizontal" android:id="@id/center_group" android:clipChildren="false" android:layout_width="fill_parent" android:layout_height="fill_parent" />
    </com.android.systemui.statusbar.phone.NearestTouchFrame>
    <com.android.systemui.statusbar.policy.DeadZone android:layout_gravity="top" android:id="@id/deadzone" android:layout_width="fill_parent" android:layout_height="fill_parent" systemui:decayTime="@integer/navigation_bar_deadzone_decay" systemui:holdTime="@integer/navigation_bar_deadzone_hold" systemui:maxSize="@dimen/navigation_bar_deadzone_size_max" systemui:minSize="@dimen/navigation_bar_deadzone_size" systemui:orientation="horizontal" />
</FrameLayout>

**Comment by C3C0** [comment]
Strange. Are you sure it's complete? This is how it's defined in AOSP:
https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-8.1.0_r61/packages/SystemUI/res/layout/navigation_layout.xml

**Comment by GorvGoyl** [comment]
u r right it's not complete. i'm not able to FULLY decompile systemui.apk 
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:58)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:81)

i'm using APK-Multi-Tool to decompile https://forum.xda-developers.com/showthread.php?t=1310151

**Comment by C3C0** [comment]
Did you try with apktool directly? Do you have framework-res.apk and oneplus-framework-res.apk installed?

**Comment by GorvGoyl** [comment]
I think i was able to decompile it correctly this time with your mentioned apktool
```
I: Using Apktool 2.3.4 on OPSystemUI.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\gourav.goyal\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

**Comment by GorvGoyl** [comment]
navigation layout file:
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout android:layout_width="fill_parent" android:layout_height="fill_parent" android:paddingStart="@dimen/nav_content_padding" android:paddingEnd="@dimen/nav_content_padding" android:layout_marginStart="@dimen/rounded_corner_content_padding" android:layout_marginEnd="@dimen/rounded_corner_content_padding"
  xmlns:android="http://schemas.android.com/apk/res/android" xmlns:systemui="http://schemas.android.com/apk/res-auto">
    <com.android.systemui.statusbar.phone.NearestTouchFrame android:id="@id/nav_buttons" android:layout_width="fill_parent" android:layout_height="fill_parent">
        <LinearLayout android:orientation="horizontal" android:id="@id/ends_group" android:clipChildren="false" android:layout_width="fill_parent" android:layout_height="fill_parent" />
        <LinearLayout android:gravity="center" android:orientation="horizontal" android:id="@id/center_group" android:clipChildren="false" android:layout_width="fill_parent" android:layout_height="fill_parent" />
    </com.android.systemui.statusbar.phone.NearestTouchFrame>
    <com.android.systemui.statusbar.policy.DeadZone android:layout_gravity="top" android:id="@id/deadzone" android:layout_width="fill_parent" android:layout_height="fill_parent" systemui:decayTime="@integer/navigation_bar_deadzone_decay" systemui:holdTime="@integer/navigation_bar_deadzone_hold" systemui:maxSize="@dimen/navigation_bar_deadzone_size_max" systemui:minSize="@dimen/navigation_bar_deadzone_size" systemui:orientation="horizontal" />
</FrameLayout>
```

**Comment by GorvGoyl** [comment]
search result for config_navBarLayout (let me know if you need complete files):
```
Searching 3 files for "config_navBarLayout"

C:\Users\gourav.goyal\Downloads\andromeda\OPSystemUI\res\values\public.xml:
 7164      <public type="string" name="compat_mode_off" id="0x7f1101a3" />
 7165      <public type="string" name="compat_mode_on" id="0x7f1101a4" />
 7166:     <public type="string" name="config_navBarLayout" id="0x7f1101a5" />
 7167:     <public type="string" name="config_navBarLayout_RTL" id="0x7f1101a6" />
 7168      <public type="string" name="config_persistentDockedActivityIntentUri" id="0x7f1101a7" />
 7169      <public type="string" name="config_rat_2g" id="0x7f1101a8" />
 ....
 7683      <public type="string" name="oem_unlock_enable_summary" id="0x7f1103b1" />
 7684      <public type="string" name="ok" id="0x7f1103b2" />
 7685:     <public type="string" name="oneplus_config_navBarLayout" id="0x7f1103b3" />
 7686:     <public type="string" name="oneplus_config_navBarLayout_RTL" id="0x7f1103b4" />
 7687      <public type="string" name="oneplus_contorl_font_family_body1" id="0x7f1103b5" />
 7688      <public type="string" name="oneplus_contorl_font_family_body2" id="0x7f1103b6" />

C:\Users\gourav.goyal\Downloads\andromeda\OPSystemUI\res\values\strings.xml:
  425      <string name="compat_mode_off">Stretch to fill screen</string>
  426      <string name="compat_mode_on">Zoom to fill screen</string>
  427:     <string name="config_navBarLayout">nav,space,back;home;recent,space,menu_ime</string>
  428:     <string name="config_navBarLayout_RTL">nav,space,recent;home;back,space,menu_ime</string>
  429      <string name="config_persistentDockedActivityIntentUri" />
  430      <string name="config_rat_2g">2G</string>
  ...
  986      <string name="oem_unlock_enable_summary">Allow the bootloader to be unlocked</string>
  987      <string name="ok">@android:string/ok</string>
  988:     <string name="oneplus_config_navBarLayout">nav,space,back;home;recent,space,menu_ime</string>
  989:     <string name="oneplus_config_navBarLayout_RTL">nav,space,recent;home;back,space,menu_ime</string>
  990      <string name="oneplus_contorl_font_family_body1">Slate-book</string>
  991      <string name="oneplus_contorl_font_family_body2">Slate-medium</string>
```

**Comment by GorvGoyl** [comment]
> Did you try with apktool directly? Do you have framework-res.apk and oneplus-framework-res.apk installed?

yes i have both framwork files in my phone

**Comment by C3C0** [comment]
OK. Thanks. Please test with this APK. Also please send me the info from xposed log after testing. I added some logging regarding views in navbar layout.
[GravityBox-8.5.0-WIP-2.zip](https://github.com/GravityBox/GravityBox/files/2893072/GravityBox-8.5.0-WIP-2.zip)

Also, what is this "nav" button in OOS? What is it designed for? When is it showing?
<string name="oneplus_config_navBarLayout">nav,space,back;home;recent,space,menu_ime</string>

**Comment by GorvGoyl** [comment]
didn't work, here are the logs https://drive.google.com/file/d/16aGAyrOjbIKEcbD03UsmP4PF2nUrn31j/view?usp=drivesdk

that nav button is to "show or hide navigation bar" by tapping on the button. by default this button is disabled but button can be made visible from phone settings

https://www.google.com/amp/s/www.androidcentral.com/how-enable-navigation-gestures-oneplus-6%3famp

**Comment by C3C0** [comment]
Can I also have another screen shot with layout bounds enabled?

**Comment by GorvGoyl** [comment]
![screenshot_20190222-210424](https://user-images.githubusercontent.com/7106086/53241703-dd511500-36e5-11e9-8a96-7851da592dc8.jpg)
![screenshot_20190222-210400](https://user-images.githubusercontent.com/7106086/53241709-e17d3280-36e5-11e9-8053-84b03eeca6a4.jpg)

**Comment by C3C0** [comment]
Unfortunately, the only way to maintain layout is to replace that nav key with custom key from GB. This can be done dynamically depending on whether custom key in GB is enabled or not.

**Comment by JerryGoyal** [comment]
that's a useless button let's put it to use! please do the changes :)

**Comment by GorvGoyl** [comment]
that's a useless button let's put it to use! please do the changes :)

**Comment by C3C0** [comment]
Please test with this APK. Note, that logic is that OOS nav key will get replaced by custom key at the same position. This might have some side-effects, depending on how OnePlus is referencing nav key in the code. If they have it stored in a member variable instead of getting it from View every time, it should be OK. Otherwise SystemUI crashes are expected.
[GravityBox-8.5.0-WIP-3.zip](https://github.com/GravityBox/GravityBox/files/2894291/GravityBox-8.5.0-WIP-3.zip)

**Comment by C3C0** [comment]
And here is another iteration where I trick OOS into thinking that my custom key is their nav key.
In theory, it should eliminate side-effects I mentioned above if there are any.
[GravityBox-8.5.0-WIP-4.zip](https://github.com/GravityBox/GravityBox/files/2894300/GravityBox-8.5.0-WIP-4.zip)

**Comment by GorvGoyl** [comment]
the latest attached apk works fine. I badly needed this feature, Thanks a ton for supporting this :) :) :)

P.S: is there any plan to build gb for pie?

**Comment by JerryGoyal** [comment]
the latest attached apk works fine. I badly needed this feature, Thanks a ton for supporting this :) :) :)

P.S: is there any plan to build gb for pie?

**Comment by C3C0** [comment]
I am working on migration to Pie. Whether I share it with public depends on quality of EdXposed.

**Comment by C3C0** [comment]
Please, could you also test how layout looks like when "cursor control keys" are enabled and showing?

**Comment by GorvGoyl** [comment]
yup, it's working fine, extreme left and right keys are changed into cursor keys

**Comment by GorvGoyl** [comment]
just to support the development, i donated on paypal. keep up the good work @C3C0 :)

**Comment by GorvGoyl** [comment]
@C3C0 it seems the latest update currently present in xposed module is causing the bootloop when i enable the custom key and reboot the phone. GravityBox-8.5.0-WIP-3.zip is working fine
