### ISSUE TITLE
[Bug] GravityBox causing bootloop in oneplus 6 when putting the paypal transaction ID to unlock premium

### ISSUE THREAD

**Issue by GorvGoyl** [GravityBox/GravityBox#1910]
I donated to paypal and received the transaction id. I put the transaction id to unlock premium features and restarted the phone. Now the phone doesn't boot normally and stuck on bootloop. To recover from this I have to delete GB in twrp recovry mode: data/app/..gb.. 
I tested several times and can confirm the issue is there.
gb version:8.5.1

**Comment by C3C0** [comment]
First of all, thanks for supporting the project.
Please, capture a logcat during boot, if possible. I won't be able to do anything without it. Thanks in advance.

**Comment by C3C0** [comment]
Sorry to bother, but anything new on that matter?

**Comment by GorvGoyl** [comment]
@C3C0 it seems the latest update currently present in xposed module is causing the bootloop when i enable the custom key and reboot the phone. GravityBox-8.5.0-WIP-3.zip is working fine... no issues with the paypal transaction id.

**Comment by C3C0** [comment]
Oh. I thought you previously confirmed WIP-4 worked OK but it was probably a misunderstanding. Anyway, please test this one:
[GravityBox-8.5.1-WIP-2.apk.zip](https://github.com/GravityBox/GravityBox/files/2901903/GravityBox-8.5.1-WIP-2.apk.zip)

**Comment by GorvGoyl** [comment]
yes it was working fine untill i rebooted my phone :P anyway this one works fine.. tested with custom key, transaction id and rebooted phone
