### ISSUE TITLE
Gravity Box 8.5.1 bug with navigation bar

### ISSUE THREAD

**Issue by Ghisy** [GravityBox/GravityBox#1911]
I have a weird bug since the latest update: my back and multi-tasking buttons are really small! (Pixel 2 XL, Oreo 8.1).

Thanks.

**Comment by C3C0** [comment]
Please, test with this APK. Thanks.
[GravityBox-8.5.1-WIP-1.apk.zip](https://github.com/GravityBox/GravityBox/files/2899671/GravityBox-8.5.1-WIP-1.apk.zip)

**Comment by C3C0** [comment]
Handled in e6c6fa5556921cf4aee710b5862fdf42b7855409
