### ISSUE TITLE
Fingerprint Launcher doesn't work

### ISSUE THREAD

**Issue by beeshyams** [GravityBox/GravityBox#1914]
Fingerprint actions not working on any of the 5 selected slots (be it apps/shortcuts) - "No app/ action assigned" toast message pops up. Toggle enabled and rebooted. Also disabled from Installer, enabled and rebooted. Didn't help

Stock MiA1 (Android one)

Dropbox 🔗 for EdXposed logs https://www.dropbox.com/s/8lg28md759crgw4/xposed_error_20190308_232340.log?dl=0. I can't see any logs in com. Solohosu....

If you need logs using laptop, it will take a few days

Edit : Same result with GB as only module

Installer log https://www.dropbox.com/s/07bqhhg15xxkv2u/xposed_error_20190309_005557.log?dl=0

Edit 2: Surprisingly, quick tap action works for both shortcuts and apps so it's not a fingerprint issue

Edit 3: Toggling config-fingerprint-support-gestures from false to true and reboot didn't help :(

**Comment by C3C0** [comment]
Please, also provide files from /data/user_de/0/com.ceco.pie.gravitybox/shared_prefs/

**Comment by beeshyams** [comment]
Here is the link please

https://www.dropbox.com/s/axe1v77bjhelvl1/com.ceco.pie.gravitybox_preferences.xml?dl=0

**Comment by C3C0** [comment]
The file shows that you have assigned app only for one finger. Did you try all of the fingers to see if one of them is triggering defined action (component=ccc71.at/.at_main_popup) ? Note that finger indexes in GB do not need to correspond wth those in Android settings.

**Comment by beeshyams** [comment]
Yes. You are seeing only finger probably because it failed for all and I tried again after trying to fix for only one finger. Here is the log for all 5 activated. First 4 fingers are apps, fifth is shortcut and quick tap is a shortcut

https://www.dropbox.com/s/axe1v77bjhelvl1/com.ceco.pie.gravitybox_preferences.xml?dl=0

**Comment by C3C0** [comment]
Will you be able to capture 
```
adb logcat -s EdXposed-Bridge
```
in case I provide you with debug APK?

**Comment by beeshyams** [comment]
Yes. If you can send now. This is the first time I would be doing it. I suppose I need it install debug. Apk, connect to laptop and run the command - correct?

**Comment by C3C0** [comment]
Yes, you will need to get adb. It's part of Android SDK but there are some minimal installations available if you search.

**Comment by beeshyams** [comment]
I have adb setup . please share apk as I am at laptop know and may not be for a few days

**Comment by C3C0** [comment]
OK. You have to enable USB debugging in developer options on phone. When you plug phone to a laptop and you have ADB driver OK then you should be prompted about ADB authorizati
on on phone. You have to confirm it.
Here is the APK. Also make sure you have "Error logging" enabled in GravityBox About menu.
[GravityBox_Pie_9.0.0-beta-1-wip-1.apk.zip](https://github.com/GravityBox/GravityBox/files/2948538/GravityBox_Pie_9.0.0-beta-1-wip-1.apk.zip)

**Comment by beeshyams** [comment]
I had enabled error logging , set up FP linked apps / shortcuts 

```
--------- beginning of system
--------- beginning of crash
--------- beginning of main
03-09 21:57:52.176  2520  2520 I EdXposed-Bridge: GB:FingerprintLauncher: onAuthenticationError: 5 - Fingerprint operation cancelled.
03-09 21:57:52.185  2520  2520 I EdXposed-Bridge: GB:FingerprintLauncher: FingerprintHandler: listening stopped
03-09 21:57:52.567  2520  2548 I EdXposed-Bridge: ML: Screen turned off, locked apps.
03-09 21:57:52.815  2520  2520 I EdXposed-Bridge: GB:FingerprintLauncher: onUserPresentChanged: present=false
03-09 21:58:21.258  2520  2520 I EdXposed-Bridge: GB:FingerprintLauncher: onUserPresentChanged: present=true
03-09 21:58:21.773  2520  2520 I EdXposed-Bridge: GB:FingerprintLauncher: FingerprintHandler: listening started


```
IDK why it says "Screen turned off"- screen was on

**Comment by C3C0** [comment]
Ok. Let it log to a file by adding: > log.txt and do some finger actions so everything necessary gets logged. Then share the file.

**Comment by beeshyams** [comment]
Here it is- same pattern goes on . Please let me know next steps- I will see tomorrow if possible to connect to laptop
```

--------- beginning of system
--------- beginning of crash
--------- beginning of main
03-09 22:06:30.047  2520  2520 I EdXposed-Bridge: GB:FingerprintLauncher: starting activity
03-09 22:06:30.236  2520  2520 I EdXposed-Bridge: GB:FingerprintLauncher: FingerprintHandler: listening stopped
03-09 22:06:30.236  2520  2520 I EdXposed-Bridge: GB:FingerprintLauncher: Restarting listening in 1000ms
03-09 22:06:31.240  2520  2520 I EdXposed-Bridge: GB:FingerprintLauncher: FingerprintHandler: listening started
03-09 22:06:40.947  2520  2520 I EdXposed-Bridge: GB:FingerprintLauncher: starting activity
03-09 22:06:41.020  2520  2520 I EdXposed-Bridge: GB:FingerprintLauncher: FingerprintHandler: listening stopped
03-09 22:06:41.020  2520  2520 I EdXposed-Bridge: GB:FingerprintLauncher: Restarting listening in 1000ms
03-09 22:06:42.022  2520  2520 I EdXposed-Bridge: GB:FingerprintLauncher: FingerprintHandler: listening started

**Comment by C3C0** [comment]
I am missing some info like info about device when it starts and also when finger apps mappings are intialized. Please start logging  as soon as device starts booting to a file. You can attach file by simply dragging it into your comment. 
adb logcat -s EdXposed-Bridge > log.txt
Also update APK where I added some additional logging.
[GravityBox_Pie_9.0.0-beta-1-wip-2.apk.zip](https://github.com/GravityBox/GravityBox/files/2948614/GravityBox_Pie_9.0.0-beta-1-wip-2.apk.zip)

**Comment by beeshyams** [comment]
Yes...you see something more here
[log.txt](https://github.com/GravityBox/GravityBox/files/2948626/log.txt)
Signing out for now hoping you have enough inputs- will check tomorrow

**Comment by beeshyams** [comment]
My apologies- to make it clean setup , I had uninstalled the previous apk and installed the new one. In the process, missed enabling error logging in GB module. Repeated with error logging enabled
[log.txt](https://github.com/GravityBox/GravityBox/files/2948719/log.txt)

**Comment by C3C0** [comment]
Too bad. Your system doesn't provide information about finger that was used. So it is not possible to map it to configured app.

**Comment by C3C0** [comment]
I don't see this debug message in the log. https://github.com/GravityBox/GravityBox/blob/pie/GravityBox/src/main/java/com/ceco/pie/gravitybox/managers/FingerprintLauncher.java#L66 "service init"
This part is necessary for identifying which finger was used on the sensor. May be related to EdXposed compatibility with your device but not sure.

**Comment by beeshyams** [comment]
All I can say is that EdXposed has been working fine on the device (apart from known issues as it evolved) and so are the modules. XprivacyLua, Xposed Edge and GB are adjusted to both Pie and EdXposed. Two other modules are Greenify and Maxlock. But all this may not matter since the problem persists with only your module activated. So, IDK what the issue is 🙄

**Comment by C3C0** [comment]
Hard to tell. Test fact is that this part of code https://github.com/GravityBox/GravityBox/blob/pie/GravityBox/src/main/java/com/ceco/pie/gravitybox/GravityBox.java#L133 does not seem to be called at all. If it was there would 100% be "service init" message in the log .

**Comment by beeshyams** [comment]
On Oreo it did work fine. What you are Saying about system not providing is also possible, since no one else reported or maybe they didn't test? Possible for you to request one of the testers to check this feature specifically?

**Comment by C3C0** [comment]
It works on my setup. Maybe try asking in XDA forum

**Comment by C3C0** [comment]
I mean the hook that takes care of allowing systemui (where fp launcher lives) to access finger IDs upon successful fp authentication is not applied on your setup for some reason. I would see debug messages of that part but there are none .

**Comment by beeshyams** [comment]
Curse Xiaomi. This is one of the important things for me

**Comment by C3C0** [comment]
Just tested on OnePlus device in combination with EdXposed on Oreo and I am getting the same symptoms. Looks like EdXposed cannot hook method I was talking about above. Not even with "Enable boot image deoptimization" enabled which should allow hooking inlined methods. Looks like we have to wait for EdXposed to improve in this area.

**Comment by C3C0** [comment]
I managed to implement a workaround and it started to work in my case. Workaround also migrated to Pie so please test this new APK.
[GravityBox_Pie_9.0.0-beta-1-wip-3.apk.zip](https://github.com/GravityBox/GravityBox/files/2949368/GravityBox_Pie_9.0.0-beta-1-wip-3.apk.zip)

**Comment by beeshyams** [comment]
Congrats Magician..it works :)

thanks :+1:

**Comment by C3C0** [comment]
Good. Thanks for testing!
