### ISSUE TITLE
Double clock on status bar 

### ISSUE THREAD

**Issue by achozex** [GravityBox/GravityBox#1915]
Hi,

I'm having 2 clocks on status bar if I choose center clock and the stock clock position is in the right 

Using official lineage os 16 oneplus 3t

**Comment by C3C0** [comment]
Looks like Lineage added additional clock. GravityBox doesn't know it is there. I do not make adjustments in case of custom ROMs as they change often thus it is unmanageable. Disable clock feature in GB if they are in conflict with the ROM.
