### ISSUE TITLE
No parameters are shown for SystemUI in Advanced Tuning (GB EdXposed version)

### ISSUE THREAD

**Issue by KaMyKaSii** [GravityBox/GravityBox#1920]
Zenfone 4, Android 8.0 stock running Riru Core v17 and EdXposed 0.3.1.2. Attached are EdXposed log, boot log and SystemUI apk.
[LogsAndSystemUI.zip](https://github.com/GravityBox/GravityBox/files/2958262/LogsAndSystemUI.zip)

**Comment by C3C0** [comment]
Could you also provide me with framework-res.apk and other apks (if present) from /system/framework ?

**Comment by KaMyKaSii** [comment]
> Could you also provide me with framework-res.apk and other apks (if present) from /system/framework ?

Sure, the framework-res.apk is the only one
[framework-res.zip](https://github.com/GravityBox/GravityBox/files/2958303/framework-res.zip)

**Comment by C3C0** [comment]
SystemUI apk does not contain classes. They are probably as oat. I need to see classes as well.

**Comment by KaMyKaSii** [comment]
> SystemUI apk does not contain classes. They are probably as oat. I need to see classes as well.
Here
[SystemUIoat.zip](https://github.com/GravityBox/GravityBox/files/2958344/SystemUIoat.zip)

**Comment by C3C0** [comment]
OK. Thanks. "R" classes are in a different location as they are normally. Will have to account for that.

**Comment by C3C0** [comment]
Please, test with this APK and report back. Thanks.
[GravityBox_Oreo_8.5.2-edxposed-wip-1.apk.zip](https://github.com/GravityBox/GravityBox/files/2958488/GravityBox_Oreo_8.5.2-edxposed-wip-1.apk.zip)

**Comment by KaMyKaSii** [comment]
> Please, test with this APK and report back. Thanks.
> [GravityBox_Oreo_8.5.2-edxposed-wip-1.apk.zip](https://github.com/GravityBox/GravityBox/files/2958488/GravityBox_Oreo_8.5.2-edxposed-wip-1.apk.zip)

I did a dirty update and after restarting GravityBox was not working, as if it had not been activated in EdXposed. I cleaned the GravityBox data, rebooted and it worked again. And yes, now the SystemUI parameters are showing up, thank you! I also noticed that in the log there are some errors related to statusbar, I did not notice any side effects because of these errors but there are something that can be done? Or is it already expected of a modified interface (even if not so much)? Anyway, thank you!
[error.log](https://github.com/GravityBox/GravityBox/files/2958578/error.log)

**Comment by C3C0** [comment]
Errors are due to incompatibility with Asus related changes. I would need to own such device to be able to resolve them. GB not responding error is a result of glich in Xposed installer app. Solution is simple. Disable/reenable module and reboot. Thanks for testing.
