### ISSUE TITLE
Lockscreen visualizer not working

### ISSUE THREAD

**Issue by Klbgr** [GravityBox/GravityBox#1925]
It's not working on OnePlus devices on pie , but visualizer is working in navbar 
It was working on oreo
Logs : https://drive.google.com/file/d/1rxTB3kdFzJLJ5kZ-hWpEawfSmNU9_agP/view?usp=drivesdk

**Comment by C3C0** [comment]
Thanks for the log. I will need a new one made while "Error logging" is enabled in About menu of GravityBox

**Comment by Klbgr** [comment]
Done : https://drive.google.com/file/d/1YdPp1iG2hOW0sPeIPU28KZW3A86B5k7e/view?usp=drivesdk

**Comment by C3C0** [comment]
Please test with attached APK which has some additional debug logging enabled. Don't forget to play something while lock screen is showing so I can actually get relevant logging info.
[GravityBox-9.0.0-beta-3-debug-1.apk.zip](https://github.com/GravityBox/GravityBox/files/2976739/GravityBox-9.0.0-beta-3-debug-1.apk.zip)

**Comment by Klbgr** [comment]
It's working now ! Lockscreen rotation is also working now. Thank you.

Logs : https://drive.google.com/file/d/1J9rfD9v13UWzD5PHx-nBioC_0gybKqFn/view?usp=drivesdk

**Comment by C3C0** [comment]
How? I didn't make any changes except for enabling debug logging.

**Comment by Klbgr** [comment]
I don't know, I have done nothing special. I have just installed a magisk font module and cleared cache before testing this apk

**Comment by C3C0** [comment]
Might be cache related, who knows. Also note that Visualizer is disabled when device is in power saving mode.

**Comment by Klbgr** [comment]
Indeed, it's cache related. I asked a XDA user having same issue and it worked after clearing cache
