### ISSUE TITLE
CircleBattery in 8.5.3-edxposed

### ISSUE THREAD

**Issue by raven428** [GravityBox/GravityBox#1927]
Something wrong with CircleBattery in 8.5.3-edxposed also as in 8.5.2-edxposed. After device boot it's working fine (screenshot 1) some time or until I open GravityBox application. After this battery indicator stop change its color depend background color and never changing with other icons of statusbar until next boot. There is nothing interesting in [logs](https://drive.google.com/file/d/1q0qPS0G9qlXL9foe61UsHVPZS2FKKyS6). So I would like to get APK with some additional logging that could reveal what's going on.

**Comment by C3C0** [comment]
Please, try with attached APK where I migrated some adjustments from Pie branch. Share the log, please.
[GravityBox-8.5.3-edxposed-debug-1.apk.zip](https://github.com/GravityBox/GravityBox/files/2978025/GravityBox-8.5.3-edxposed-debug-1.apk.zip)

**Comment by raven428** [comment]
Looks like this version doesn't have described issue. At least, I'm not able to repeat. Anyway, I uploaded logs [here](https://drive.google.com/file/d/1pWL04cdj4zzxWFCSP6WTBJqN_LMZEaCG/view?usp=sharing). May I have same with ability to unlock? :smirk:

**Comment by C3C0** [comment]
Thanks for testing. I'll make an official release soon.

**Comment by C3C0** [comment]
Here's the new release https://github.com/GravityBox/GravityBox/releases/tag/v8.5.3.1-edxposed_o
