### ISSUE TITLE
Disable ModRinger features for samsung devices

### ISSUE THREAD

**Issue by Firefds** [GravityBox/GravityBox#1928]
Samsung has completely changed how to ringtone works.
None of the old classes exist - `com.android.server.telecom.secutils.SecAsyncRingtonePlayer`, `com.android.server.telecom.AsyncRingtonePlayer`, `com.android.server.telecom.TelecomServiceImpl` nor the methods they use.

There is no "easy" way to adapt the implementation to work with Samsung devices

**Comment by C3C0** [comment]
How sad. Thanks for the info.
