### ISSUE TITLE
[FIXED][Bug][Pie] Unplug turns on screen

### ISSUE THREAD

**Issue by gohamstergo** [GravityBox/GravityBox#1938]
On Pie, Google Pixel, GB 9 beta 5

"Unplug turns on screen" toggle does not function. Screen always turns on. Let me know if I can provide further info.

**Comment by C3C0** [comment]
What is the behavior when you override config_unplugTurnsOnScreen in Advanced tuning / Framework ?

**Comment by gohamstergo** [comment]
The option under Display wasn't synced with the override. (not sure if that matters, just pointing it out)

I set the override to "false" and rebooted, but after reboot the "current value" still says "true" and screen still turns on when plugged/unplugged.

**Comment by C3C0** [comment]
This would indicate resource replacement does not work in your case which is weird as I don't remember any other Pixel owners reporting such issue. We will have to do some debug logging so I will get back to you when I have more time.

**Comment by gohamstergo** [comment]
cool, lmk

**Comment by C3C0** [comment]
The option in Display tweaks will not be synced with Advanced tuning, which is by design. Changes in Advanced tuning automatically have higher priority than standard options that modify the same config parameters. Attached is APK with some debug logging enabled. Please, test with config_unplugTurnsOnScreen overridden in Advanced tuning and also make sure "Error logging" is enabled in About menu of GB.
Share the xposed log. You can either get one from EdXposed installer app or by using
```
adb logcat -s EdXposed-Bridge
```
[GravityBox-9.0.0-beta-5-debug-1.apk.zip](https://github.com/GravityBox/GravityBox/files/3002880/GravityBox-9.0.0-beta-5-debug-1.apk.zip)

**Comment by gohamstergo** [comment]
Steps I took for log:
Installed debug version, reboot, enable logging, config_unplugTurnsOnScreen set false, reboot, wait for phone to finish booting/settle, plug in/unplug, grab log from app:

--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 9
Android sdk: 28
Android build: PQ2A.190305.002
Fingerprint: google/sailfish/sailfish:9/PQ2A.190305.002/5240760:user/release-keys
ROM build description: sailfish-user 9 PQ2A.190305.002 5240760 release-keys
EdXposed Version: 0.3.1.5_beta-SNAPSHOT (3150)
Architecture: arm64-v8a
Device: sailfish
Manufacture: Google
Brand: google
Product: sailfish
--------- beginning of main
--------- beginning of system
--------- beginning of crash
03-25 17:01:08.467  2312  2312 I EdXposed-Bridge: Loading modules from /data/app/tw.fatminmin.xposed.minminguard-vcUnj2gIxaB2j0bIYiSZQg==/base.apk
03-25 17:01:08.598  2312  2312 I EdXposed-Bridge:   Loading class tw.fatminmin.xposed.minminguard.Main
03-25 17:01:08.661  2312  2312 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.pie.gravitybox-BZN-dBBAyhRUlqNhTSaTHg==/base.apk
03-25 17:01:08.753  2312  2312 I EdXposed-Bridge:   Loading class com.ceco.pie.gravitybox.GravityBox
03-25 17:01:08.761  2312  2417 W XSharedPreferences: getSharedPreferences
03-25 17:01:08.761  2312  2417 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
03-25 17:01:08.761  2312  2417 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
03-25 17:01:08.761  2312  2417 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
03-25 17:01:08.761  2312  2417 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
03-25 17:01:08.761  2312  2417 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
03-25 17:01:08.761  2312  2417 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
03-25 17:01:08.762  2312  2416 W XSharedPreferences: getSharedPreferences
03-25 17:01:08.762  2312  2416 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
03-25 17:01:08.762  2312  2416 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
03-25 17:01:08.762  2312  2416 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
03-25 17:01:08.762  2312  2416 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
03-25 17:01:08.762  2312  2416 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
03-25 17:01:08.762  2312  2416 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
03-25 17:01:08.769  2312  2312 I EdXposed-Bridge: GB:Hardware: sailfish
03-25 17:01:08.769  2312  2312 I EdXposed-Bridge: GB:Product: sailfish
03-25 17:01:08.769  2312  2312 I EdXposed-Bridge: GB:Device manufacturer: Google
03-25 17:01:08.769  2312  2312 I EdXposed-Bridge: GB:Device brand: google
03-25 17:01:08.769  2312  2312 I EdXposed-Bridge: GB:Device model: Pixel
03-25 17:01:08.769  2312  2312 I EdXposed-Bridge: GB:Device: sailfish
03-25 17:01:08.773  2312  2312 I EdXposed-Bridge: GB:Device type: phone
03-25 17:01:08.773  2312  2312 I EdXposed-Bridge: GB:Is MTK device: false
03-25 17:01:08.774  2312  2312 I EdXposed-Bridge: GB:Is Xperia device: false
03-25 17:01:08.774  2312  2312 I EdXposed-Bridge: GB:Is Moto XT device: false
03-25 17:01:08.774  2312  2312 I EdXposed-Bridge: GB:Is OxygenOS ROM: false
03-25 17:01:08.774  2312  2312 I EdXposed-Bridge: GB:Has telephony support: true
03-25 17:01:08.774  2312  2312 I EdXposed-Bridge: GB:Has Gemini support: false
03-25 17:01:08.774  2312  2312 I EdXposed-Bridge: GB:Android SDK: 28
03-25 17:01:08.774  2312  2312 I EdXposed-Bridge: GB:Android Release: 9
03-25 17:01:08.774  2312  2312 I EdXposed-Bridge: GB:ROM: PQ2A.190305.002
03-25 17:01:08.774  2312  2312 I EdXposed-Bridge: GB:Error logging: true
03-25 17:01:09.948  2440  2440 I EdXposed-Bridge: GB:Is AOSP forced: false
03-25 17:01:14.798  2440  2551 I EdXposed-Bridge: GB:ResourceProxy: New ResourceSpec{pkg=android, id=17956968, name='config_enableTranslucentDecor', value=true}
03-25 17:01:16.478  2313  2313 I EdXposed-Bridge: Loading modules from /data/app/tw.fatminmin.xposed.minminguard-vcUnj2gIxaB2j0bIYiSZQg==/base.apk
03-25 17:01:16.586  2765  2841 W XSharedPreferences: getSharedPreferences
03-25 17:01:16.586  2765  2841 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
03-25 17:01:16.586  2765  2841 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
03-25 17:01:16.586  2765  2841 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
03-25 17:01:16.586  2765  2841 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
03-25 17:01:16.586  2765  2841 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
03-25 17:01:16.586  2765  2841 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
03-25 17:01:16.590  2765  2840 W XSharedPreferences: getSharedPreferences
03-25 17:01:16.590  2765  2840 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
03-25 17:01:16.590  2765  2840 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
03-25 17:01:16.590  2765  2840 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
03-25 17:01:16.590  2765  2840 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
03-25 17:01:16.590  2765  2840 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
03-25 17:01:16.590  2765  2840 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
03-25 17:01:16.802  2313  2313 I EdXposed-Bridge:   Loading class tw.fatminmin.xposed.minminguard.Main
03-25 17:01:16.954  2313  2313 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.pie.gravitybox-BZN-dBBAyhRUlqNhTSaTHg==/base.apk
03-25 17:01:17.291  2313  2313 I EdXposed-Bridge:   Loading class com.ceco.pie.gravitybox.GravityBox
03-25 17:01:17.339  2313  2945 W XSharedPreferences: getSharedPreferences
03-25 17:01:17.339  2313  2945 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
03-25 17:01:17.339  2313  2945 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
03-25 17:01:17.339  2313  2945 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
03-25 17:01:17.339  2313  2945 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
03-25 17:01:17.339  2313  2945 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
03-25 17:01:17.339  2313  2945 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
03-25 17:01:17.342  2313  2946 W XSharedPreferences: getSharedPreferences
03-25 17:01:17.342  2313  2946 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
03-25 17:01:17.342  2313  2946 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
03-25 17:01:17.342  2313  2946 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
03-25 17:01:17.342  2313  2946 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
03-25 17:01:17.342  2313  2946 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
03-25 17:01:17.342  2313  2946 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
03-25 17:01:19.444  2440  2685 I EdXposed-Bridge: GB:ResourceProxy: New ResourceSpec{pkg=android, id=17957016, name='config_safe_media_volume_enabled', value=false}
03-25 17:01:24.351  2765  2765 I EdXposed-Bridge: GB:ResourceProxy: New ResourceSpec{pkg=com.android.systemui, id=2131166172, name='rounded_corner_content_padding', value=21}
`
couldnt get adb to show anything, so this is from edxposed app.

**Comment by gohamstergo** [comment]
or if you prefer, the log file itself.
[xposed_error_20190325_171347.log](https://github.com/GravityBox/GravityBox/files/3005727/xposed_error_20190325_171347.log)

**Comment by C3C0** [comment]
This is suspicious:
```
03-25 17:01:16.586  2765  2841 W XSharedPreferences: getSharedPreferences
03-25 17:01:16.586  2765  2841 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
03-25 17:01:16.586  2765  2841 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
03-25 17:01:16.586  2765  2841 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
03-25 17:01:16.586  2765  2841 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
03-25 17:01:16.586  2765  2841 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
03-25 17:01:16.586  2765  2841 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
```
Looks like Xposed framework has some issue sreading preferences.

Can you provide me with zipped file containing /data/user_de/0/com.ceco.pie.gravitybox/shared_prefs folder contents?
Also try clearing data for GravityBox and device ART cache and test whether it works after that.

**Comment by C3C0** [comment]
Also try disabling any other xposed module so we can rule out logic in GB is not overridden by other module.

**Comment by gohamstergo** [comment]
each step separated by a reboot:
1. disabled other xposed and magisk modules - no go
2. updated edxposed to 3.1.7 (just in case) - no go
3. clear cache - no go

requested zip attached
[shared_prefs.zip](https://github.com/GravityBox/GravityBox/files/3010917/shared_prefs.zip)

**Comment by C3C0** [comment]
Preferences seem OK to me. My feeling is it's about Xposed framework having some issues reading preferences within SystemUI app. I can verify that by taking a look at xposed log created with attached APK. 
[GravityBox-9.0.0-beta-6-debug-1.apk.zip](https://github.com/GravityBox/GravityBox/files/3012096/GravityBox-9.0.0-beta-6-debug-1.apk.zip)

**Comment by gohamstergo** [comment]
[xposed_all_20190327_180520.log](https://github.com/GravityBox/GravityBox/files/3015598/xposed_all_20190327_180520.log)
as youll see in the log, i left minmin guard enabled on this one since i saw no difference when i previously disabled it. let me know if i should do it again without it..

**Comment by C3C0** [comment]
It's now clear that config_unplugTurnsOnScreen is never requested by the system so overriding it doesn't do anything. Most likely because system is not using such config parameter anymore.

**Comment by C3C0** [comment]
You could test option to "Disable rounded corner padding" in Statusbar tweaks.  This basically overrides "rounded_corner_content_padding" in SystemUI category (which you can see traces of in xposed log). This option removes additional padding in the edges of screen that shifts statusbar icons from the edges.

**Comment by C3C0** [comment]
Please, can you test with this APK? I made some adjustments regarding resource replacement implementation.
[GravityBox-9.0.0-beta-6-debug-2.apk.zip](https://github.com/GravityBox/GravityBox/files/3017014/GravityBox-9.0.0-beta-6-debug-2.apk.zip)

**Comment by gohamstergo** [comment]
no joy on the unplug, unfortunately. corner rounding removal seems to work tho.

odd that xposed would have issues reading anything. woulda thought root would allow it full access to everything. hmm :\

log attached if u want it
[xposed_all_20190328_170037.log](https://github.com/GravityBox/GravityBox/files/3020360/xposed_all_20190328_170037.log)

**Comment by C3C0** [comment]
Confirmed it's 99% the one I thought it was.
```
<setting id="108177" name="op_camera_notch_ignore" value="0" package="com.android.settings" defaultValue="0" defaultSysSet="true" />
```
Thanks. I will provide you with APK for testing later.

**Comment by C3C0** [comment]
There is nothing we can do more unfortunately. This config parameter is totally ignored by your device's system.

**Comment by C3C0** [comment]
Well, in theory I could implement a different logic for "Unplug turns on screen" option in Display tweaks. This way we could check if hooking directly on a method which handles this config param works.

**Comment by C3C0** [comment]
Please, try with this APK. Use original "Unplug turns on screen" option in Display tweaks instead of overriding it in Advanced tuning.
[GravityBox-9.0.0-beta-6-debug-4.apk.zip](https://github.com/GravityBox/GravityBox/files/3021956/GravityBox-9.0.0-beta-6-debug-4.apk.zip)

**Comment by gohamstergo** [comment]
WORKS! Removed the advanced tuning setting and have the standard option unchecked and it seems to be working properly. Thanks for all your help troubleshooting. This is my favorite setting. Have no idea why Android defaults to always turning the screen on. Is that a thing most people like? Maybe it just bugs me more since the phone also auto-unlocks on my wifi and car bluetooth, so the screen doesnt shut itself off like it would if locked.

Oh well, anyways, thanks again!
[xposed_all_20190329_080403.log](https://github.com/GravityBox/GravityBox/files/3022731/xposed_all_20190329_080403.log)

**Comment by C3C0** [comment]
Great. Thanks for testing.
