### ISSUE TITLE
[Bug][Pie] Battery percentage disappearing on white apps

### ISSUE THREAD

**Issue by Whoeva** [GravityBox/GravityBox#1947]
OnePlus 6T, Android P

When notch is disabled in OnePlus settings, battery percentage from GravityBox in status bar is disappering (free space) on some white or maybe bright apps/screens of apps. For example on Chrome while address bar is white or Play Store > My apps & games.

**Comment by C3C0** [comment]
What is the behavior of status bar when "Notch is disabled". Does it show under the notch or? This looks to be OxygenOS specific which means I can hardly do anything without working with a real device.

**Comment by Whoeva** [comment]
Apps don't color notch area if hidden, it stays black.

![01 Notch showing](https://user-images.githubusercontent.com/49018895/55146979-dc2c6100-5145-11e9-800f-acd8b184161f.jpg)
![02 Notch](https://user-images.githubusercontent.com/49018895/55146993-de8ebb00-5145-11e9-93a6-cf3a11bdd7d0.jpg)
![03 Notch hidden, colored](https://user-images.githubusercontent.com/49018895/55146998-e0f11500-5145-11e9-8126-ba02b4e41b18.jpg)
![04 Notch hidden, white](https://user-images.githubusercontent.com/49018895/55147005-e3ec0580-5145-11e9-9c10-b2c45f9ed859.jpg)

**Comment by C3C0** [comment]
This sucks. Percent text is hooked on dynamic icon color changes that happen based on status bar color. OnePlus forgot to block that functionality in case of "hidden notch". If you can get me an info where in the System settings (under which settings key) is stored that "Hide notch area" option I would be able to take its value into account.

**Comment by Whoeva** [comment]
Unfortunately this exceeds my knowledge. I've tried to find something like that with Secure Settings under "Device Setting" but didn't find it.
Could you tell me what to do or is that too difficult?

**Comment by C3C0** [comment]
It should be enough if you copied out xml files located in /data/system/users/0/

**Comment by Whoeva** [comment]
Ok, I've sent it to your email.

**Comment by C3C0** [comment]
Thanks. I think I found something but not sure if it's a related setting. To confirm, can you now disable "hidden notch" and send me the files again? I would be able to compare current files with the new files  to see what got changed.

**Comment by Whoeva** [comment]
Ok, I've sent it, good luck!

**Comment by C3C0** [comment]
Confirmed it's 99% the one I thought it was.
```
<setting id="108177" name="op_camera_notch_ignore" value="0" package="com.android.settings" defaultValue="0" defaultSysSet="true" />
```
Thanks. I will provide you with APK for testing later.

**Comment by Whoeva** [comment]
Perfect!

**Comment by C3C0** [comment]
Please, test with attached APK and also attach Xposed log after testing. Ideally test both scenarios - with notch hidden and without notch hidden.
[GravityBox-9.0.0-beta-6-debug-3.apk.zip](https://github.com/GravityBox/GravityBox/files/3021790/GravityBox-9.0.0-beta-6-debug-3.apk.zip)

**Comment by Whoeva** [comment]
Thank you, it works with and without notch hidden!
No battery color issues anymore. 
I will send you the log later when I'm home, have to find out how that works first.
