### ISSUE TITLE
[BUG][CRASH][ANDROID P]. System UI crash when enabling "hide power menu on lockscreen"

### ISSUE THREAD

**Issue by V-Droid** [GravityBox/GravityBox#1950]
When I enable the option to hide the power menu on the lockscreen, when I go to the lockscreen and hold down the power buttom the system UI crashes and for a breif moment I am able to see the power menu and then everything goes back to normal.

I'm on the stock rom for the Moto G6 (Ali) running Android P 9.0.0

Below I leave you a catlog and the Xposed log for the crash, if you need anything else let me know :)

[xposed_error_20190401_000324.log](https://github.com/GravityBox/GravityBox/files/3027949/xposed_error_20190401_000324.log)
[2019-04-01-00-05-14.txt](https://github.com/GravityBox/GravityBox/files/3027951/2019-04-01-00-05-14.txt)

**Comment by C3C0** [comment]
Please enable "Error logging" in About menu of GravityBox and test with attached APK.
[GravityBox-9.0.0-beta-6-debug-5.apk.zip](https://github.com/GravityBox/GravityBox/files/3028053/GravityBox-9.0.0-beta-6-debug-5.apk.zip)

**Comment by V-Droid** [comment]
I activated "error logging" and then proceeded to download the apk that you left me, after a reboot I unlocked my device and then locked it again. I holded down the power button and there were no crashes, everything is fine. 

Something else I forgot to mention, the option to rotate the lockscreen is not working for me, what do you need so you can fix that?

**Comment by C3C0** [comment]
Lockscreen rotation is most likely broken by EdXposed not able to hook inlined methods. However, there is another way that might work:
Advanced tuning / Framework / config_enableLockScreenRotation

**Comment by V-Droid** [comment]
I gave it a try however it's still not working, either way thank you very much for your help. 

Keep up the good work 😁😁

**Comment by C3C0** [comment]
Just found out it didn't work on my setup either. I made some adjustments and config_enableLockScreenRotation now works in my case. Feel free to test if interested.
[GravityBox-9.0.0-beta-6-debug-6.apk.zip](https://github.com/GravityBox/GravityBox/files/3029007/GravityBox-9.0.0-beta-6-debug-6.apk.zip)

**Comment by V-Droid** [comment]
Awesome! I downloaded the apk you provided and lock screen rotation is working now 👌 

Thank you very much, keep up the good work 😁
