### ISSUE TITLE
[request] Disable album cover/YouTube thumbnail on lockscreen. 

### ISSUE THREAD

**Issue by devanteweary** [GravityBox/GravityBox#1951]
That's all! Thanks!

**Comment by Shaxine** [comment]
I would like this feature too.

**Comment by devanteweary** [comment]
You got me excited thinking they added this feature.

________________________________
From:   António Pereira
Sent:   June 14, 2019 3:34:56 PM
To:     GravityBox/GravityBox
CC:     devanteweary, Author
Subject:        Re: [GravityBox/GravityBox] [request] Disable album cover/YouTube thumbnail on lockscreen. (#1951)


I would like this feature too.

**Comment by Shaxine** [comment]
On my OnePlus 5T with OOS 9.0.8. It works fine the first time I access the lockscreen (I see everything except the album art), but after that my lockscreen goes blank, without clock, status bar, everything. Only shows the background image.

Disabling this option, makes everything work again.

**Comment by C3C0** [comment]
What kind of wallpaper do you use? Standard or live or custom?
I can't reproduce on OOS 9.0.2 (OP3T).

**Comment by Shaxine** [comment]
It's a normal image, and I have the standard style selected on the app.
