### ISSUE TITLE
[Android 9 Pie] Circle Battery Indicator does not respect status bar icon colors on lockscreen

### ISSUE THREAD

**Issue by ghost** [GravityBox/GravityBox#1952]
All variants of the circle battery indicator stay white on the lock screen, even though they change color properly elsewhere, and the regularly shaped indicators change color properly everywhere. 
Screenshots of the bug:

* https://i.imgur.com/LN2hbch.png
* https://i.imgur.com/eZUqqV8.png
* https://i.imgur.com/NE3yTRF.png

System information:

* **Device:** Pixel 3 XL
* **Android version:** Android 9 Pie (PQ2A.190405.003)
* **Riru version:** v17.1
* **EdXposed version:** v0.3.1.7-beta
* **Magisk version:** v19.0-3eae9494 (19001)
* **Gravity Box version:** 9.0.0-beta-6
* **Potential Conflicts:** None; using the Pixel stock ROM and the only other modules installed are DisableFlagSecure, Greenify, and NSFW Gboard, which do not modify the status bar in any way.

I found an additional small bug as well: You cannot change between the stock battery indicator and stock+percentage indicator directly, if you do not choose one of the circle indicator options between selecting the two no change to the indicator will be made.

**Comment by C3C0** [comment]
Is this while light album art is showing? I tried to set white lockscreen wallpaper and all icons are still white in lockscreen statusbar.

**Comment by ghost** [comment]
This occurs when a light enough wallpaper is set to force Android 9 Pie's light/dark mode detection (effecting lock and home screen icon colors, system overlays, quick switcher, etc) from dark to light. Here is a copy of the wallpaper I used to cause this issue, but please be aware it is **very NSFW**: `https://i.imgur.com/9W89VDX.jpg`

**Comment by C3C0** [comment]
Yes, I can reproduce now. Had to set white wp for both, home and lockscreen

**Comment by ghost** [comment]
Gotcha; thank you. Please let me know if you need any more information, testing, etc.

**Comment by ghost** [comment]
Thank you for the quick fix!
