### ISSUE TITLE
[Android 9 Pie] Setting custom lockscreen image softbricks device.

### ISSUE THREAD

**Issue by ghost** [GravityBox/GravityBox#1953]
Setting a custom lockscreen image seems to cause the lockscreen to crash; the screen stays mostly blank besides the status bar icons flashing every few seconds, Imprint does not respond to fingerprints on the scanner, etc. effectively softbricking the device until Magisk or EdXposed are disabled with their uninstaller ZIPs in recovery mode. 

Additionally, as GravityBox will automatically exit if it does not detect its framework, there is no way to disable breaking settings such as this without wiping the entire app data and resetting all settings. Not a huge deal, but it would be nice if we could adjust settings in the app even if the module is disabled in EdXposed, so buggy/broken features that disable the device can be easily disabled without losing all other settings.

System information:

* **Device:** Pixel 3 XL
* **Android version:** Android 9 Pie (PQ2A.190405.003)
* **Riru version:** v17.1
* **EdXposed version:** v0.3.1.7-beta
* **Magisk version:** v19.0-3eae9494 (19001)
* **Gravity Box version:** 9.0.0-beta-7
* **Potential Conflicts:** None; using the Pixel stock ROM and the only other modules installed are DisableFlagSecure, Greenify, and NSFW Gboard, which do not modify the status bar in any way.

**Comment by C3C0** [comment]
Cannot reproduce on my Nexus5X running Pixel Experience which is basically the same as what's running on Pixel devices. Thus logcat of crash is needed.

Also making settings available without EdXposed part loaded might seem easy but in fact it is not as many settings rely on information received from the system which is sent by EdXposed part.

**Comment by ghost** [comment]
I'm not sure if it matters, but here are the steps I can use to reproduce the error:

1. Open GravityBox>Lockscreen>Custom Image
1. Select [this image **[NSFW]**](https://i.loli.tube/uploads/big/772705def57b0663357aa3094dfc1c06.png) which is 8800x9728/33.3MB. (Could it be a resolution filesize issue, maybe?)
1. In the application selector that pops up, choose [Simple Gallery](https://github.com/SimpleMobileTools/Simple-Gallery) to crop the image. 
1. Do not make any modifications to the image whatsoever, no cropping, etc. and click the check mark. 
1. Lock the device, observe that the lock screen is no longer accessible.

**Comment by C3C0** [comment]
Event though not tested yet, it is most likely some OOM issue (out of memory) due to large size of the image. I will test later and I will probably have to do some downscaling to match device's real display resolution because using anything with higher resolution than the real one makes no sense anyway.

**Comment by C3C0** [comment]
Please test with attached APK. Thanks.
[GravityBox-9.0.0-beta-7-debug-1.apk.zip](https://github.com/GravityBox/GravityBox/files/3042258/GravityBox-9.0.0-beta-7-debug-1.apk.zip)

**Comment by C3C0** [comment]
Any news? I can confirm it works on my side. Tested also with simple gallery.
Btw, regarding simple gallery, it seems to ignore input parameters which define the required frame dimensions. It always sets the frame to the size of input image ignoring my request.
