### ISSUE TITLE
Do not check proximity sensor by incoming call for Telegram doesn't work

### ISSUE THREAD

**Issue by Senliast** [GravityBox/GravityBox#1955]
There is an option to check the proximity sensor before enabling screen and option to ignore it by incoming call. It works fine for normal calls, but doesn't work for Telegram. Is there a way to fix it?

Pixel 2, unmodified original Android Pie ROM with root / Magisk, EdXposed.

**Comment by C3C0** [comment]
This feature is for native telephony only thus won't work with 3rd party apps and their VoIP solutions as I can't detect whether there is 3rd party app call or not.
