### ISSUE TITLE
[Bug?] "Factory data reset" text in Reboot to Recovery Option

### ISSUE THREAD

**Issue by ghost** [GravityBox/GravityBox#1957]
The title of the "Restarting..." prompt when using the Advanced Reboot Menu's reboot to recovery option shows "Factory Data Reset", resulting in quite a shock. However, actual functionality is perfect and data is not reset. Additionally, the "Restarting..." UI is different between all advanced reboot options; Reboot shows an overlay with "Restarting..." text in the middle, recovery shows a centered white Restarting... prompt, and bootloader does not have an indicator.

I apologize if this is an inherent limitation with regards to EdXposed resource hooks; please close this issue if that is the case.

System information:

* **Device:** Pixel 3 XL
* **Android version:** Android 9 Pie (PQ2A.190405.003)
* **Riru version:** v17.1
* **EdXposed version:** v0.3.1.7-beta
* **Magisk version:** v19.0-82ea9db9 (19003)
* **Gravity Box version:** 9.0.0-beta-7
* **Potential Conflicts:** None; using the Pixel stock ROM and the only other modules installed are DisableFlagSecure, Greenify, and NSFW Gboard, which do not modify the status bar in any way.

**Comment by C3C0** [comment]
Fixed in 4cb2f3122dc427a6500f11ea9fac2672f753d82d

**Comment by ghost** [comment]
Thank you for the quick fix!
