### ISSUE TITLE
increasing ring not work

### ISSUE THREAD

**Issue by ivaf** [GravityBox/GravityBox#1958]
Hello!
The increasing ring of the call does not work for me. Settings made. On similar smartphones function works. I think about the problem with my device. Could you help me find out what's wrong?
GB version: GravityBox+[O]-v8.5.3.1-edxposed_build_8531
[error.log](https://github.com/GravityBox/GravityBox/files/3077310/error.log)

**Comment by C3C0** [comment]
No related errors in the log. Did you try receiving a phone call before exporting the log? Also, is there any reason to use Sandhook version of EdXposed which is not even available for general use, yet?

**Comment by ivaf** [comment]
Yes, I made the call first and then copied the log.
Sendhook is used to pass a SafetyNet check.
But the increase volume ring did not work for me and on the usual Xposed. I probably did something wrong with my device during the firmware. Because the ring volume increase works on the same device with the same firmware.
This means that my question is not for you. Thanks for your time. I close the issue.
