### ISSUE TITLE
[Feature Request] Double the height of the status bar to increase possible number of status bar notification icons for phones with notches

### ISSUE THREAD

**Issue by yipchow** [GravityBox/GravityBox#1959]
I would like to humbly suggest something for GravityBox that 4 of my friends with phones with notches said they would absolutely love. Only being able to see 4 or less status bar notification icons is a serious problem with Pie, and especially with phones with notches and Pie. Many people have apps that show you the temperature in the status bar, as well as Keep/Wunderlist reminders, Youtube notifications, etc. If you have 3 reminders in Wunderlist, forget it; you can no longer see the temperature or that you have a new YouTube notification which is ridiculous. A lot of people on Reddit and other forums are extremely angry about Google doing this. 

If there a way in GravityBox to double the height of the status bar, it would resolve all these problems. There would be a second line available for notifications, with way more room since it would not be cut off by the notch. I think even people with phones WITHOUT a notch would love this because they could effectively have 15+ status bar notifications without having a dot icon cutting them off.  Even BEFORE Pie's limitation of 4, many people WITHOUT notches would have their notifications cut off by a "..." if it got to be too many for the width of the status bar. 

Anyway I hope you consider this tweak for GravityBox. What Google is doing with Pie is making their phones more and more like Apple and it's driving a lot of people crazy, so this would be a huge thing if it is possible to accomplish. Thank you for everything you do, and for reading.

**Comment by C3C0** [comment]
Hardly possible. Status bar layout is too complicated and I cannot imagine how such a complicated extension could be done using Xposed.

**Comment by yipchow** [comment]
> Hardly possible. Status bar layout is too complicated and I cannot imagine how such a complicated extension could be done using Xposed.

Is just allowing more than 4 status bar notifications possible on phones like the non-XL Pixels at least?

**Comment by C3C0** [comment]
Already discussed at XDA. https://forum.xda-developers.com/showpost.php?p=79312960&postcount=500
Currently, the only solution I can see would be to disable max icon restriction altogether. If you are interested to test I can provide you with a test APK with max icon restriction removed to check how it will behave. What device/ROM are you using?

**Comment by yipchow** [comment]
Yes I would love to test it! I am using a 2016 Pixel 1 (non-XL) with the stock Pie ROM.

**Comment by yipchow** [comment]
Let me know how I obtain it :)

**Comment by C3C0** [comment]
Please test behavior of notification icons with this test build. Also provide Xposed log after testing. Thanks.
[GravityBox-Pie-9.0.0-beta-8-wip1.apk.zip](https://github.com/GravityBox/GravityBox/files/3111444/GravityBox-Pie-9.0.0-beta-8-wip1.apk.zip)

**Comment by yipchow** [comment]
It works!! I love you!!!!

I am on a Google Pixel 1. Is there any info you need from me that will help you?? 

You have no idea how much this means to me and so many Pie users!!

**Comment by C3C0** [comment]
All for now. New option has already been added and will be available in the next version. Still trying to solve some anomalies some other user is experiencing on Nokia phone.
