### ISSUE TITLE
[Bug][Pie] Broken bottom-right lockscreen action & more music volume steps

### ISSUE THREAD

**Issue by Eamo5** [GravityBox/GravityBox#1961]
Continuation of discussion from [post #519](https://forum.xda-developers.com/showpost.php?p=79347266&postcount=519) & [post #522](https://forum.xda-developers.com/showpost.php?p=79352853&postcount=522) from the XDA thread.

In response to [post #522](https://forum.xda-developers.com/showpost.php?p=79352853&postcount=522) 

1. Thank you for providing insight on the issue :) If there's anything else I can do on my end to assist you, please let me know!

2. ro.config.media_vol_steps appears to be absent from /system/build.prop on my Pixel 2 XL on the latest April security patch.

**Comment by C3C0** [comment]
Attached is a test APK where:
1) should be potentially fixed
2) should output some debug log messages in the xposed log, so please share the log after testing "More volume steps" feature.
[GravityBox-9.0.0-beta-7-wip-2.apk.zip](https://github.com/GravityBox/GravityBox/files/3089320/GravityBox-9.0.0-beta-7-wip-2.apk.zip)

**Comment by Eamo5** [comment]
@C3C0 

1. Both the left and right lockscreen action aren't visible anymore. 

2. Logs are attached. Hopefully should help sort the issue for both

[xposed_all_20190417_220244.log](https://github.com/GravityBox/GravityBox/files/3089469/xposed_all_20190417_220244.log)
[xposed_error_20190417_220221.log](https://github.com/GravityBox/GravityBox/files/3089471/xposed_error_20190417_220221.log)

**Comment by C3C0** [comment]
```
04-17 22:00:53.706  1262  1262 I EdXposed-Bridge: GB:ModAudio: MAX_STREAM_VOLUME for music stream set to 10
```
I just tested the same value (10) on my setup and it seems to be working - media stream has 10 volume steps. Not sure why it doesn't work in your case as the log shows expected behavior.

**Comment by Eamo5** [comment]
@C3C0 strange, it's definitely still using at least 20 volume steps. Could a logcat be of some use here?

**Comment by C3C0** [comment]
If it's not 15 by default (which is Android's default) there maybe must be something else that is overriding it. (E.g. the reason why I asked for presence of ro.config.media_vol_steps is because in case it was present, the feature in GravityBox would be ignored)

**Comment by C3C0** [comment]
Now please run with this APK where I added additional log message to output value of MAX volume after audio service is constructed. 
The values in messages "MAX_STREAM_VOLUME for music stream set to" and "MAX_STREAM_VOLUME for music stream after construction" must match. If they don't something is overriding the value previously set by GravityBox.
[GravityBox-9.0.0-beta-7-wip-3.apk.zip](https://github.com/GravityBox/GravityBox/files/3089626/GravityBox-9.0.0-beta-7-wip-3.apk.zip)

**Comment by Eamo5** [comment]
@C3C0 I've just verified that running in core only mode on stock Pixel 2 XL software, there are 25 volume steps.

```
04-17 22:59:41.836  1252  1252 I EdXposed-Bridge: GB:ModAudio: MAX_STREAM_VOLUME for music stream set to 10
04-17 22:59:41.856  1252  1252 I EdXposed-Bridge: GB:ModAudio: AudioService constructed. Broadcast receiver registered
04-17 22:59:41.856  1252  1252 I EdXposed-Bridge: GB:ModAudio: Default mSafeMediaVolumeIndex set to 150
04-17 22:59:41.856  1252  1252 I EdXposed-Bridge: GB:ModAudio: MAX_STREAM_VOLUME for music stream after construction: 25
```

... Well shit! Logs + logcat attached
[logcat.txt](https://github.com/GravityBox/GravityBox/files/3089710/logcat.txt)
[xposed_all_20190417_230234.log](https://github.com/GravityBox/GravityBox/files/3089712/xposed_all_20190417_230234.log)
[xposed_error_20190417_230238.log](https://github.com/GravityBox/GravityBox/files/3089713/xposed_error_20190417_230238.log)

**Comment by C3C0** [comment]
It's clear now. Please wait for another APK iteration I'll provide soon.

**Comment by C3C0** [comment]
What about this one? I had to hook on a different method but at first sight it looks like it can get inlined by ART optimizer, but maybe not. Worth a try.
[GravityBox-9.0.0-beta-7-wip-4.apk.zip](https://github.com/GravityBox/GravityBox/files/3089873/GravityBox-9.0.0-beta-7-wip-4.apk.zip)

**Comment by Eamo5** [comment]
It works! That's one issue solved :)

**Comment by C3C0** [comment]
OK. Thanks for testing and patience.

**Comment by Eamo5** [comment]
Thanks for your fast responses and fantastic support! Whenever a new APK is ready for the locksceen actions, let me know :) Thanks again!

**Comment by C3C0** [comment]
Wait, I though 1) is fixed, isn't it?

**Comment by Eamo5** [comment]
Nope. In fact it's more broken than it was previously because the left-bottom action doesn't work either now.

> 1. Both the left and right lockscreen action aren't visible anymore.

**Comment by C3C0** [comment]
I thought you wanted to hide them both that's why I thought it was fixed. Anyway, have to go and will get back to it tomorrow.

**Comment by Eamo5** [comment]
No worries, I'll keep my eyes peeled for a new build. To clarify, the issue is the actions not functioning or showing icons. Thanks for your help!

**Comment by C3C0** [comment]
What was the opriginal behavior? Left key worked but right didn't? Also, do you even get stock camera key in case GravityBox is off (or related features are disabled or left default)

**Comment by Eamo5** [comment]
The original behaviour in the XDA release was the left shortcut working perfectly and the right shortcut not showing an icon or functioning when being swiped.

Every build of GravityBox since the first build you sent me has had neither shortcut working at all now.

In core only mode (stock), there aren't any shortcuts on the lockscreen in the latest software.

**Comment by C3C0** [comment]
That might be an issue. GravityBox only replaces existing shortcut. So if there is none natively, there is nothing to replace.

**Comment by C3C0** [comment]
Please test with this one and share the xposed log.
[GravityBox-9.0.0-beta-7-wip-5.apk.zip](https://github.com/GravityBox/GravityBox/files/3094246/GravityBox-9.0.0-beta-7-wip-5.apk.zip)

**Comment by Eamo5** [comment]
Well that build seems to have fixed it! I've attached logs anyway just in case they're of any value to you. Thanks for your excellent support! Happy to close the issue now?

[xposed_all_20190418_215326.log](https://github.com/GravityBox/GravityBox/files/3094269/xposed_all_20190418_215326.log)
[xposed_error_20190418_215312.log](https://github.com/GravityBox/GravityBox/files/3094270/xposed_error_20190418_215312.log)

**Comment by C3C0** [comment]
OK. Did you also try all the combinations? Like hiding, switching back to "default" ?

**Comment by Eamo5** [comment]
Yep I can confirm, all is working perfectly now with both left and right actions :)

**Comment by C3C0** [comment]
Great. Thanks.
