### ISSUE TITLE
[Feature Request] Block QS on lockscreen

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [GravityBox/GravityBox#1963]
Could you implement this: https://github.com/char101/xposed-qslock ?

Thanks a lot.

**Comment by C3C0** [comment]
GravityBox already had its unique qs tile protection functionality. You can protect tiles on per-tile basis in the "Statusbar QuickSettings tiles" where second checkbox next to each tile is used to mark tile as protected. Protected tiles won't be active while device is locked.
