### ISSUE TITLE
Changing lockscreen wallpaper changes ambient display wallpaper

### ISSUE THREAD

**Issue by st40611** [GravityBox/GravityBox#1970]
On a Pixel 3 (blueline), setting a custom wallpaper for lockscreen ends up changing the background for Ambient Display too. It is a neat "feature" (never knew of an option to change the background of ambient display), but is there a way to de-couple the two settings?

**Comment by C3C0** [comment]
Interesting. Shouldn't ambient screen be black? Can I see the screenshot?

**Comment by st40611** [comment]
Unfortunately pressing the screenshot shortcuts ends up fully waking up the phone, so I just took pictures of the device: https://photos.app.goo.gl/1k8kwpeZyhhTVdNu7

You can see one of them is in ambient display mode (only the notification icon in the middle), while the second one is the regular lockecreen. If I change the settings to default in gravitybox, it goes back to being black.

**Comment by C3C0** [comment]
It says "Album is empty"
On Nexus5X running Pixel Experience ROM it's black as expected with custom image for wallpaper set. Maybe I'm missing some additional setting?
![IMG_20190429_084220](https://user-images.githubusercontent.com/1543473/56879928-147fd180-6a5b-11e9-8a84-e3744cb27d07.jpg)

**Comment by st40611** [comment]
Ah, I may have found the problem. This issue only occurs if I have a live wallpaper set. If I have a regular wallpaper set for both lockscreen and homescreen, and then let GB's lockscreen settings take place after I lock it, then it behaves normally: a) black Ambient Display b) Proper Last Screen/Custom blurred lockscreen wallpaper c) my original home screen wallpaper.

EDIT: Sorry about the earlier link, deleted the images off my Photos account and forgot. Here's an imgur link: https://imgur.com/a/KMiJexS

**Comment by C3C0** [comment]
OK. Thanks. Can you try with this version and eventually provide the Xposed log generated by it?
[GravityBox-Pie-9.0.0-beta-9-debug2.apk.zip](https://github.com/GravityBox/GravityBox/files/3126243/GravityBox-Pie-9.0.0-beta-9-debug2.apk.zip)

**Comment by st40611** [comment]
Sure, just installed and I see that it's now working as intended even with live wallpapers!

--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 9
Android sdk: 28
Android build: PQ2A.190405.003
Fingerprint: google/blueline/blueline:9/PQ2A.190405.003/5310204:user/release-keys
ROM build description: blueline-user 9 PQ2A.190405.003 5310204 release-keys
EdXposed Version: 0.3.1.7_beta (3170)
Architecture: arm64-v8a
Device: blueline
Manufacture: Google
Brand: google
Product: blueline
--------- beginning of main
--------- beginning of system
04-29 00:17:21.701   812   812 I EdXposed-Bridge: Loading modules from /data/app/com.jozein.xedge-b6tFzHJHddGYf10zBaQZag==/base.apk
04-29 00:17:21.728   812   812 I EdXposed-Bridge:   Loading class com.jozein.xedge.xposed.HookMain
04-29 00:17:21.730   812   812 I EdXposed-Bridge: [XEdge] Xposed edge 5.4.2, activated by ed xposed. 
04-29 00:17:21.733   812   812 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.pie.gravitybox-rmymyk0ILcY0G_pdjT6tNg==/base.apk
04-29 00:17:21.809   812   812 I EdXposed-Bridge:   Loading class com.ceco.pie.gravitybox.GravityBox
04-29 00:17:21.813   812  1230 W XSharedPreferences: getSharedPreferences
04-29 00:17:21.813   812  1230 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
04-29 00:17:21.813   812  1230 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
04-29 00:17:21.813   812  1230 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
04-29 00:17:21.813   812  1230 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
04-29 00:17:21.813   812  1230 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
04-29 00:17:21.813   812  1230 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
04-29 00:17:21.814   812   812 I EdXposed-Bridge: GB:Hardware: blueline
04-29 00:17:21.814   812   812 I EdXposed-Bridge: GB:Product: blueline
04-29 00:17:21.814   812   812 I EdXposed-Bridge: GB:Device manufacturer: Google
04-29 00:17:21.814   812   812 I EdXposed-Bridge: GB:Device brand: google
04-29 00:17:21.814   812   812 I EdXposed-Bridge: GB:Device model: Pixel 3
04-29 00:17:21.814   812   812 I EdXposed-Bridge: GB:Device: blueline
04-29 00:17:21.816   812   812 I EdXposed-Bridge: GB:Device type: phone
04-29 00:17:21.816   812   812 I EdXposed-Bridge: GB:Is MTK device: false
04-29 00:17:21.816   812   812 I EdXposed-Bridge: GB:Is Xperia device: false
04-29 00:17:21.816   812   812 I EdXposed-Bridge: GB:Is Moto XT device: false
04-29 00:17:21.816   812   812 I EdXposed-Bridge: GB:Is OxygenOS ROM: false
04-29 00:17:21.818   812   812 I EdXposed-Bridge: GB:Has telephony support: true
04-29 00:17:21.818   812   812 I EdXposed-Bridge: GB:Has Gemini support: false
04-29 00:17:21.818   812   812 I EdXposed-Bridge: GB:Android SDK: 28
04-29 00:17:21.818   812   812 I EdXposed-Bridge: GB:Android Release: 9
04-29 00:17:21.818   812   812 I EdXposed-Bridge: GB:ROM: PQ2A.190405.003
04-29 00:17:21.818   812   812 I EdXposed-Bridge: GB:Error logging: false
04-29 00:17:22.418  1251  1251 I EdXposed-Bridge: GB:Is AOSP forced: false
04-29 00:17:23.765  1251  1251 I EdXposed-Bridge: [XEdge] System hooked
04-29 00:17:25.322  1251  1324 I EdXposed-Bridge: [XEdge] Screen size: 1080, 2160
04-29 00:17:26.538   814   814 I EdXposed-Bridge: Loading modules from /data/app/com.jozein.xedge-b6tFzHJHddGYf10zBaQZag==/base.apk
04-29 00:17:26.560  1744  1768 W XSharedPreferences: getSharedPreferences
04-29 00:17:26.560  1744  1768 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
04-29 00:17:26.560  1744  1768 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
04-29 00:17:26.560  1744  1768 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
04-29 00:17:26.560  1744  1768 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
04-29 00:17:26.560  1744  1768 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
04-29 00:17:26.560  1744  1768 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
04-29 00:17:26.585   814   814 I EdXposed-Bridge:   Loading class com.jozein.xedge.xposed.HookMain
04-29 00:17:26.588   814   814 I EdXposed-Bridge: [XEdge] Xposed edge 5.4.2, activated by ed xposed. 
04-29 00:17:26.596   814   814 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.pie.gravitybox-rmymyk0ILcY0G_pdjT6tNg==/base.apk
04-29 00:17:26.689   814   814 I EdXposed-Bridge:   Loading class com.ceco.pie.gravitybox.GravityBox
04-29 00:17:26.695   814  1786 W XSharedPreferences: getSharedPreferences
04-29 00:17:26.695   814  1786 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
04-29 00:17:26.695   814  1786 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
04-29 00:17:26.695   814  1786 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
04-29 00:17:26.695   814  1786 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
04-29 00:17:26.695   814  1786 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
04-29 00:17:26.695   814  1786 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
04-29 00:17:27.563  1251  1323 I EdXposed-Bridge: [XEdge] Display info{ initial size(1080, 2160), forced size(1080, 2160), initial density=440, scaled density=440 }
04-29 00:17:27.573  1251  1323 I EdXposed-Bridge: [XEdge] Module initialed.
--------- beginning of crash
04-29 00:17:39.261  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:17:39.285  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:17:39.841  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:17:39.991  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:17:40.020  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:13.429  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:13.778  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:13.862  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:17.190  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:17.211  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:17.256  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:17.292  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:19.681  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:19.705  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:19.760  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:19.788  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:29.022  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:29.193  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:29.224  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:33.568  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:40.109  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:40.272  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:41.567  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:41.587  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:41.627  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive
04-29 00:18:41.651  1744  1744 I EdXposed-Bridge: GB:ModLockscreen: updateMediaMetaData: device not interactive

**Comment by C3C0** [comment]
Thanks for testing. So I assume that transition from ambient to normal also works as intended? Custom wallpaper shows when normal lockscreen shows after ambient one?

**Comment by st40611** [comment]
The transition is sort of interesting depending on the live wallpaper used. On the Pixel 3, there's a couple of live wallpapers that show a slight "mark" on the ambient display (see: https://www.reddit.com/r/GooglePixel/comments/9iq2ik/download_the_pixel_3_live_wallpapers_right_here/e6lnvob/). For those, there will be a transition animation in the normal case when you go to the normal lockscreen. With GravityBox mod, I end up getting this (assuming my last screen is my home screen):
Live Wallpaper AOD -> fade transition into lock screen -> lock screen (with custom wallpaper) -> unlocks -> plays Live wallpaper AOD-into-full transition animation -> live wallpaper on launcher

With other live wallpaper:
Black -> fade transition into lock screen -> lock screen (with custom wallpaper) -> unlocks -> live wallpaper on launcher.
