### ISSUE TITLE
[Bug] Cannot disable navigation bar with Pie beta 9

### ISSUE THREAD

**Issue by ghost** [GravityBox/GravityBox#1971]
I use Fluid Navigation Gestures on my device, so I use GravityBox to disable the navbar. This functionality works in beta 8 but is broken in beta 9; toggling it on or off does nothing and it remains on.

System information:

* **Device:** Pixel 3 XL
* **Android version:** Android 9 Pie (PQ2A.190405.003)
* **Riru version:** v18.0
* **EdXposed version:** v0.3.1.7-beta
* **Magisk version:**  v19.0-54d1207f (19005)
* **Gravity Box version:** 9.0.0-beta-9

* **Potential Conflicts:** None; using the Pixel stock ROM and the only other modules installed are DisableFlagSecure, Greenify, and NSFW Gboard, which do not modify the status bar in any way.

**Comment by C3C0** [comment]
Strange. There weren't any changed between 8 and 9 that could affect navbar in that way. How do you disable it? By unchecking "Enable navigation bar" in Navbar tweaks or some other way? I tested in on my devices and it worked as expected in beta 9. Didn't you do some build.prop modifications lately?

**Comment by ghost** [comment]
That is strange. I disable it by opening Navigation bar tweaks>Master switch>Reboot>untick "Enable navigation bar">Reboot. This works as expected on beta8, but does nothing on beta9. I have not modified my build.prop (nor do I use MagiskHide Props Config or any modules of that nature).

**Comment by C3C0** [comment]
Please run this version which has some debug logging enabled and then share the Xposed log. Thanks.
[GravityBox-Pie-9.0.0-beta-9-debug1.apk.zip](https://github.com/GravityBox/GravityBox/files/3126082/GravityBox-Pie-9.0.0-beta-9-debug1.apk.zip)

**Comment by ghost** [comment]
Sorry for the late reply. Here are my Xposed logs. 
* [xposed_error_20190501_174549.log](https://github.com/GravityBox/GravityBox/files/3136108/xposed_error_20190501_174549.log)
* [xposed_all_20190501_174616.log](https://github.com/GravityBox/GravityBox/files/3136110/xposed_all_20190501_174616.log)

**Comment by C3C0** [comment]
Looks like config_showNavigationBar parameter is not getting overridden and even it is not called at all for some reason. Are you sure it wasn't removed from your ROM by some update?
Can you try if you see that parameter in Advanced tuning / Framework section? If yes, can you try overriding it there?

**Comment by ghost** [comment]
I'm using the stock Pixel 3 XL firmware/ROM. I do have that config item in Advanced Tuning. It shows false in beta8 when the GravityBox option is enabled, but reverts to true after upgrading to beta9 and rebooting. Overriding it manually has no effect, it stays true with "Overridden value: false (reboot required)" showing even after multiple reboots.

**Comment by C3C0** [comment]
A mystery to me. Please, run attached version and share the log after booting.
[GravityBox-Pie-9.0.0-beta-9-debug4.apk.zip](https://github.com/GravityBox/GravityBox/files/3141787/GravityBox-Pie-9.0.0-beta-9-debug4.apk.zip)

**Comment by ghost** [comment]
* [xposed_all_20190504_183954.log](https://github.com/GravityBox/GravityBox/files/3144911/xposed_all_20190504_183954.log)
* [xposed_error_20190504_184001.log](https://github.com/GravityBox/GravityBox/files/3144912/xposed_error_20190504_184001.log)

**Comment by C3C0** [comment]
Using RRO? If so, can you try disabling it?

**Comment by ghost** [comment]
RRO? Is that the Sony theming engine that was merged into AOSP some time ago? If so, no, I am not using it. These are the only modifications I've done to my device:

* [Screenshot_20190505-104944](https://user-images.githubusercontent.com/25443872/57195698-9cfee600-6f23-11e9-980c-a31f35b623e7.png)
* [Screenshot_20190505-104932](https://user-images.githubusercontent.com/25443872/57195699-9cfee600-6f23-11e9-8b25-4682bcd147c2.png)

**Comment by C3C0** [comment]
Strange. I am seeing unexpected package names for Android resources. E.g.
```
05-04 18:39:04.258 1375 1375 I EdXposed-Bridge: GB:ResourceProxy: getOrCreateResourceSpec: pkg=android.auto_generated_rro__; name=config_showNavigationBar; value=true
```
"android.auto_generated_rro__" should normally "android" that's why I asked about RRO. There definitely must be something that changes that standard naming. Anyway, tomorrow I will adjust code to account for that kind of modified name and let you test.

**Comment by C3C0** [comment]
Please, test with this version and provide xposed log after testing. Thanks in advance.
[GravityBox-Pie-9.0.0-beta-9-debug5.apk.zip](https://github.com/GravityBox/GravityBox/files/3147275/GravityBox-Pie-9.0.0-beta-9-debug5.apk.zip)

**Comment by ghost** [comment]
This version successfully hides the navbar. Here are my Xposed logs: 

* [xposed_all_20190506_054542.log](https://github.com/GravityBox/GravityBox/files/3147390/xposed_all_20190506_054542.log)
* [xposed_error_20190506_054538.log](https://github.com/GravityBox/GravityBox/files/3147391/xposed_error_20190506_054538.log)

---- 

Additionally, is it possible that new naming scheme is the default in later Pie updates? I don't believe I have anything installed that utilizes RRO in any way:

* AdAway 
* andOTP 
* Cash App 
* Chrome Canary 
* Copy Toast 
* CutTheCord (Discord mod)
* Dark Sky 
* Deliveries 
* DisableFlagSecure 
* Discover 
* Docs 
* Duolingo 
* Edge Sense Plus 
* EdXposed Installer 
* Enpass 
* F-Droid 
* Find My Device 
* Firefox Nightly 
* FiSwitch 
* Fluid NG 
* Gallery 
* Genius 
* Google News 
* Google Opinion Rewards 
* Google Pay 
* GravityBox [P] 
* GravityBox Unlocker 
* Greenify 
* Greenify (Donation Package) 
* Hulu 
* Keep Notes 
* Lens Cap 
* LibreTorrent 
* List My Apps 
* LiveBoot 
* Lyft 
* Magisk Manager 
* MicroG - YouTube Vanced 
* minimgur 
* Muzei 
* MX Player Pro 
* Notification Log 
* Nova Launcher 
* Nova Launcher Prime 
* NSFW Gboard 
* oandbackup 
* Outlook 
* Prime Video 
* ProtonMail 
* Revolution IRC 
* Riru 
* SE FTP Server 
* SecScanQR 
* Simple 
* Snapseed 
* Solid Explorer 
* Spotify 
* Sync Pro 
* Tachiyomi 
* Tachiyomi: E-Hentai 
* Tachiyomi: Hentai2Read 
* Tachiyomi: NHentai 
* Thank You 
* Translate 
* Twidere 
* U by BB&T 
* VLC 
* Voice 
* WireGuard 
* Your Phone Companion 
* YouTube Vanced

**Comment by C3C0** [comment]
Good news. Thanks for testing.
Regarding RRO, I found this so I recommend reading and maybe trying documented commands to check how it behaves on your device. https://www.xda-developers.com/android-oreo-command-line-themes/

**Comment by C3C0** [comment]
Please, can you test with APK posted in another issue: https://github.com/GravityBox/GravityBox/issues/1977#issuecomment-490879549 ?
I would like to have confirmed that version still works with your case. Thanks in advance.

**Comment by ghost** [comment]
Hello,

The build in that comment still works; the navigation bar is successfully hidden.

**Comment by C3C0** [comment]
Thanks for quick reply.
