### ISSUE TITLE
Bug (double missed call)

### ISSUE THREAD

**Issue by Dru7979** [GravityBox/GravityBox#1973]
When I use GravityBox on Oreo (Oneplus 3T OOS or custom 8.1) and I use other phone app (True Phone) then I have double notification of missed call. When I disable GravityBox then notification of missed call is OK (one from Telecom.apk). When I enable GravityBox then I have double notification of missed call (two from Telecom.apk).

**Comment by C3C0** [comment]
Please, can you test with this debug version and then post Xposed log exported after missed call situation?
[GravityBox-8.5.3-debug1.apk.zip](https://github.com/GravityBox/GravityBox/files/3137282/GravityBox-8.5.3-debug1.apk.zip)

**Comment by Dru7979** [comment]
It doesn't help.

**Comment by C3C0** [comment]
I know. There weren't any changes. I just enabled some logging as I need to have more info before doing anything. So please get those logs as I requested. Thanks.

**Comment by Dru7979** [comment]
It doesn't help.

czw., 2 maj 2019, 10:47 użytkownik C3C0 <notifications@github.com> napisał:

**Comment by Dru7979** [comment]
Where I find these logs?

czw., 2 maj 2019, 13:39 użytkownik C3C0 <notifications@github.com> napisał:

**Comment by C3C0** [comment]
I made the related feature optional (off by default) so it will be OK in the next version of GravityBox.
