### ISSUE TITLE
[BUG] The WhatsApp icon on the lock screen shows double the number of messages.

### ISSUE THREAD

**Issue by vantela** [GravityBox/GravityBox#1991]
The WhatsApp icon on the lock screen shows double the number of messages.
But if the notification from WhatsApp is only about an open client from a computer - the current shows one message. And as I see it should not show at all - this is not a message.

Phone: Samsung Galaxy Note 8
Version of GravitiBox 9.0.0-beta-11

**Comment by C3C0** [comment]
Badges show number of notifications not messages. They don't and cannot know anything about app context thus it is not possible to distinguish between types of notifications.

**Comment by vantela** [comment]
Maybe for WhatsApp add the option "divide the number of notifications by 2 rounded up, in order to get the number of messages in most cases."
Otherwise, it turns out to be very annoying - it shows the dial 10, and exactly 5 messages.

**Comment by C3C0** [comment]
I am sorry but feature is about how many notifications currently exist for an app not about how many notifications of particular type.
