### ISSUE TITLE
Ring & Notification unlink

### ISSUE THREAD

**Issue by vendelieu** [GravityBox/GravityBox#1993]
It doesn't work on Oneplus 5, don't know about others. 
you can set this option to unlink, but it doesn't affects.
Doesn't make additional new notification volume panel(make no sense yeah? how i can set different values if i see just ring volume) and more than if i turn up "expand volume panel" and set different values it still linked to each other

**Comment by vendelieu** [comment]
android 9
oxygen 9.0.5

riru 19
edexposed 0.4.1.2 (yahfa)
gravitybox 9.1.0

**Comment by C3C0** [comment]
- Enable "Error logging" in GravityBox and reboot
- Test the Link volume feature and then export Xposed error log and post it here.
- Optionally provide /system/framework/framework-res.apk + /system/priv-app/OPSystemUI

**Comment by vendelieu** [comment]
Cannot read log /data/user_de/0/com.solohsu.android.edxp.manager/log/error.log (No such file or directory)

(log dir is empty)

**Comment by C3C0** [comment]
Another alternative is to use ADB to capture log. Messages logged by EdXposed and modules can be get by running: `adb logcat -s EdXposed-Bridge`
