### ISSUE TITLE
[Feature Request] QuickApp Tile Icon Size Correction

### ISSUE THREAD

**Issue by creeve4** [GravityBox/GravityBox#2003]
The icon size for the QuickApp Tiles is noticeably smaller than other QS Tiles. Where can I find the code that is used to scale or set the icon size?
![Screenshot_20190625-221136](https://user-images.githubusercontent.com/1910130/60150643-bfc8b080-9796-11e9-9cc5-ba2cfb4b9a62.png)

**Comment by C3C0** [comment]
Scaling of the icons is performed by QS panel itself. In case of app icon it always depends on how it was designed by app dev. Some app icons have larger padding from the edges some don't. Those with larger paddings will then appear smaller.

**Comment by creeve4** [comment]
Thanks for the explanation.
