### ISSUE TITLE
[Feature request] Disable Android P rotation suggestion

### ISSUE THREAD

**Issue by VarunAgw** [GravityBox/GravityBox#2004]
Similar to #1897.

I am on Android P, and I absolutely hate this feature (since it get accidentally pressed all the time). Is it possible to add a small toggle to disable it altogether?

**Comment by biyahpk** [comment]
Found an alternative solution .

`adb shell settings put secure show_rotation_suggestions 0`

**Comment by VarunAgw** [comment]
Found an alternative solution .

`adb shell settings put secure show_rotation_suggestions 0`
