### ISSUE TITLE
Regarding Overriding Vibrations 

### ISSUE THREAD

**Issue by dr-kaisar** [GravityBox/GravityBox#2011]
After overriding vibrations for the notification of an app, when I try Preview option in the per-app settings of GravityBox, it sometimes creates vibration and sometimes doesn't. But the overridden vibration works for the notification. 

Is it a bug?

I am a Samsung S8 Plus (8.0.0) user.

**Comment by C3C0** [comment]
I guess it also depends on priority level of particular notification. Different notifications can have different priorities. System won't perform vibration for those that are of low priority. Try looking at system's notification settings for given apps how their notification channels are set up.

**Comment by dr-kaisar** [comment]
I have tried setting the priority of the notifications to Urgent/Highest but no luck for me.
