### ISSUE TITLE
OOS 10 (Android Q) Navigation Bar Tweak Bug

### ISSUE THREAD

**Issue by christantoan** [GravityBox/GravityBox#2019]
I'm using OnePlus 7 Pro

After activating the Master Switch on the Navigation bar tweaks page and restarting, the option to switch navigation bar or gesture in Settings app is gone and changed as if it doesn't support gesture navigation. As a result, if I activate the master switch and restarting while I'm using gesture navigation, I can't activate/switch to navigation bar from gesture (at least from Settings app)

**Comment by C3C0** [comment]
Strange. I am using the same setup, I have navbar tweaks enabled (as I am using standard navbar) and I can still switch between navbar/gesture in OOS Settings without issues. I am not running additional mods. Maybe share a screenshot of how your navbar tweaks are configured so I can try to replicate.

**Comment by christantoan** [comment]
An update first: I did further experiment with the options and found that enabling the "Enable navigation bar" option in the Navigation bar tweaks page and restarting restored my Settings app. So I guess case closed? I'm not sure if this the intended behavior.

This was my previous situation:

Yes, of course. In addition to screenshots, should I also upload a log file? I'm not sure which one to share because this is not exactly an error per se.

Here's my settings before I enabled the master switch and restarted my device:
![Screenshot_20190930-092655](https://user-images.githubusercontent.com/7300310/65858234-ba669d80-e365-11e9-815e-294d8ea32c45.png)
![Screenshot_20190930-092711](https://user-images.githubusercontent.com/7300310/65858236-ba669d80-e365-11e9-9ef7-7e5aa6ba4777.png)
![Screenshot_20190930-092736](https://user-images.githubusercontent.com/7300310/65858235-ba669d80-e365-11e9-9db1-0bce500ca6c8.png)

Here's my Settings app looks like after I restarted:
![Screenshot_20190930-093108](https://user-images.githubusercontent.com/7300310/65858333-f13cb380-e365-11e9-9415-aea715a88bf3.png)

**Comment by C3C0** [comment]
Disabling "Enable navigation bar" is for disabling navbar completely and is checked by default on devices which have navbar by default. Should be used only if you want to get rid of navbar completely, although behavior on OOS might be different due to their extensions.
