### ISSUE TITLE
OxygenOS 10.0.1.GM21BA (Android Q) - QuickSettings Tile Protection Doesn’t Work

### ISSUE THREAD

**Issue by christantoan** [GravityBox/GravityBox#2024]
Not sure if it was because of the beta4 update but I remember the tiles protection when screen is locked has worked before. Other tiles settings are working normally
I have tried to retoggle the switches with saving in-between with no avail.

![](https://i.imgur.com/EqDa2JG.png)

Thank you.

**Comment by C3C0** [comment]
Make sure device is truly locked (indicated by closed padlock in lock screen). I have the same setup and protection works.

**Comment by christantoan** [comment]
Thank you. I tried your suggestion but it still didn't work but after a reboot it does.
