### ISSUE TITLE
GB doesn't work properly on OP7 (not pro)

### ISSUE THREAD

**Issue by beeshyams** [GravityBox/GravityBox#2027]
**Configuration**

* Indian version (GM1901, 10.0.1 GM57AA)
* Beta 4 GB version.
* EdXposed installer 4.5.1 . Version 2.2.4 used by you creates a lot of lag on the device.
* YAHFA version from [post 30](https://forum.xda-developers.com/showpost.php?p=80392829&postcount=30) and Riru 19.5
* Magisk 20 stable (latest).

**Problems**

* Device lags one hell of a lot.I have only 3 Xposed modules running - GB, XPrivacy Lua and Maxlock. If I disable GB, it is fine (little lag is there but that's OK). 
* Notification icons don't show on the left side. However, if I use None Display Cutout magisk module (by MlgmXyysd), and set the cut out options to that in developer settings, I can see  notification icons.
* Trusted WiFi screen is blank, can't select anything because nothing is displayed.
These are problems noticed with what I use (FP launcher is fine). There may be more but I haven't explored because the device lags so much that *I have kept GB disabled*.

**Logs**
* Logcat at boot
`adb logcat -s EdXposed-Bridge>log2.txt`
[log2.txt](https://github.com/GravityBox/GravityBox/files/3751549/log2.txt)

* Installer module logs
[error.log](https://github.com/GravityBox/GravityBox/files/3751552/error.log)

**Comment by C3C0** [comment]
I don't have reports from other users about lag so there must be something special about your setup. There are no errors related to GravityBox module. Errors come from maxlock module. Things to try:
- disable all modules but GravityBox to see if something changes
- disable Resource hooking support in Edxposed manager app

Regarding notification icons. No reports from other users either. The only options that can affect this part of status bar area is "Max notification icons" in status bar tweaks. And also when you use center clock. So try to disable those if you have them enabled. If there's no difference in behavior there must be something else going on.

**Comment by C3C0** [comment]
Regarding Trusted WiFi. Make sure you did not deny Location permission from GravityBox app. It is needed to read WiFi scan results since Android 10.

**Comment by beeshyams** [comment]
Thanks for a quick revert.

* Resource hooking support is disabled (never enabled it) in Edxposed manager app.
* With only GB enabled 
  * <s>**Trusted WiFi screen is blank, can't select anything because nothing is displayed**</s>
  * Notification Icon (one) shows up on left with clock on left with day and dd/mm , so I guess there is no more place because if I shift clock to right , I can see more icons (Max notification icons disabled). I am fine with this. :
* I can't say about lags , it seems fine after reboot but would like to keep this pending in observation.
* Permission for WiFi is given as "Allow only while using the app". Other option is deny. 
Edit: That is because by habit I always turn off location globally till now. Once enabled , it is fine, I can see networks and select :)

Thanks a lot, only issue remaining is that of lags- once I am sure it is fine , I will close or revert here

Slightly OT but **request** you to suggest the YAHFA version to be used as Edxposed gets upgraded so that problems are minimised . A good place would be the OP

**Comment by C3C0** [comment]
Ok. Thanks for info. Regarding which EdXposed to use. I am rather recommending to use what seems to work best according to user experience. As the fact is both behave differently on different systems. Also for your reference, there's a fresh official release of EdXposed published minutes ago. But requires custom build of Magisk until support for custom selinux policies is added to official Magisk.

**Comment by C3C0** [comment]
One more thing related to Resource hooking support. By default it's enabled (checkbox unchecked). So if you didn't disable it explicitly, you have it enabled.

**Comment by beeshyams** [comment]
I get your point regarding EdXposed version but at least for One Plus I guess it hope it should work across all devices. Just to highlight the diverse variations, in the latest version 4.5.1 of installer, regarding resource hooks, it's the opposite. It's an experimental feature and disabled by default. I would've added a screenshot but can't figure how from the mobile. Here's a link to it
https://my.pcloud.com/publink/show?code=XZh734kZx4LwUMVwhbj3Oumbrjfmp8AaEFzk

**Comment by C3C0** [comment]
Ah, I see and it makes sense it's disabled by default. Never used manager before so didn't know. But I will be probably switching as the installer I am currently using is no longer being maintained. But it always worked so I didn't have a need to bother with it.

**Comment by C3C0** [comment]
Now when I'm looking at the screenshot you have resource hooks ENABLED. You have to switch it ON to Disable resource hooks, just like the option says.

**Comment by beeshyams** [comment]
A big advantage is it tells you updates to itself /Riru/YAHFA /Sandhook and let's you download them directly.

Ughh about the resource hooks... Brain comatose.. Let me see again

**Comment by beeshyams** [comment]
Thanks. Lags have reduced except for the occasional freeze of apps, which is fine given the entire beta setup at play. I am closing this and hope I needn't have to open again :). BTW, another small suggestion, why not error logging in module enabled by default? It may help in making sure errors are recorded (with a reboot option to disable).

**Comment by beeshyams** [comment]
@C3C0 

Few other minor things that aren't working , I thought I would document here. Not important for me (except the FP quick tap disable) ,  happened to test and thought it would be good to document in one place since logs are readily available. 

* Charging animation / none doesn't work

* Charging color doesn't work

* Quick unlock doesn't seem to override OnePlus settings , in the sense there is a small lag which wasn't there with other devices (noticed this on Pie) also

* FP launcher quick tap action to be disabled as discussed

**Comment by beeshyams** [comment]
@C3C0

It is perfectly fine now barring an occasional freeze of some app, which is easily remedied by killing it (added a custom nav bar button from GB for that!) & minor points mentioned above. 

. I owe you an apology sincerely for blaming your app while the culprit was another module. And BTW, going forward, if I see an error will test with that module only and report to that developer, just as you advise in OP.

Thanks for your continued support for this project 😊🙏

**Comment by C3C0** [comment]
- charging animation/color of what? percent text?
- Quick unlock in GB should be used only in case stock ROM doesn't already have such feature

**Comment by beeshyams** [comment]
@C3C0 I thought charging animation and color was applicable to battery as I recall from KitKat (?) and was testing that.
Yes quick unlock is perhaps best left to stock but your implementation is zippy and nice

**Comment by beeshyams** [comment]
@C3C0 Thanks sent !
If you can please look into battery animation at your convenience. No hurry

**Comment by C3C0** [comment]
Thanks for supporting the project (I removed PayPal ID from your previous post).
Charging animation is within Battery percent text settings and thus it applies to battery percent text only. GravityBox never provided animations for stock battery icons. Circular styles have animation by default.

**Comment by beeshyams** [comment]
@C3C0 Thanks for the clarification !
