### ISSUE TITLE
[Bug] System UI crashes 

### ISSUE THREAD

**Issue by mahdinouri75** [GravityBox/GravityBox#2033]
Hello. when I activate Gravity Box module, my system UI crashes multiple times & I can't even pass the lock screen. I hope you can fix it. Tnx
I have Redmi Note 4 (Mido) running Android 10.

**Comment by C3C0** [comment]
I need to see a broader context. Can you do a full logcat, not only EdXposed related stack traces?

**Comment by mahdinouri75** [comment]
> I need to see a broader context. Can you do a full logcat, not only EdXposed related stack traces?



[logcat.txt](https://github.com/GravityBox/GravityBox/files/3801427/logcat.txt)

**Comment by C3C0** [comment]
Thanks but there is no systemui crash in that log. I can see a lot of resource replacement related debug messages, though. This feature is experimental on Q and should be disabled if not needed. Resource hooking support can be disabled in EdXposed Manager app.

**Comment by mahdinouri75** [comment]
> Thanks but there is no systemui crash in that log. I can see a lot of resource replacement related debug messages, though. This feature is experimental on Q and should be disabled if not needed. Resource hooking support can be disabled in EdXposed Manager app.

I disabled resource hooking but still same result. Also, I found several new fatal errors in logcat after disabling it. For example, this one is related to system UI.
F ndroid.systemu: runtime.cc:630]   at com.android.systemui.statusbar.policy.Clock.updateClock(Clock.java:427)

[New Logcat.txt](https://github.com/GravityBox/GravityBox/files/3801718/New.Logcat.txt)

**Comment by C3C0** [comment]
Those fatal crashes are at ART level which is lower than module and indicate issue/incompatibility of EdXposed and the system. All other crashes such as DeadSystemException are direct consequence of crash in ART. Maybe try asking at XDA users using the same device/system which EdXposed version works best for them.
