### ISSUE TITLE
modules.list not found

### ISSUE THREAD

**Issue by JC1RB** [GravityBox/GravityBox#2035]
OnePlus 6t running OOS 10, Android 10
Riru Core v19.5
EdXposed YAHVA v 0.4.6.0_beta(4471)

No magisk hide or edXposed black/whitelist

Trying to run GB Q beta 5
I have checked and the file is there, and not corrupt. This is also happening with other GB betas.

Log below:

beginning of crash
11-06 20:14:07.181   747   747 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/com.solohsu.android.edxp.manager/conf/modules.list was not found

**Comment by C3C0** [comment]
There's something wrong with your EdXposed setup. Not related to GravityBox.
