### ISSUE TITLE
Blocking tiles on secured lockscreen doesnt work

### ISSUE THREAD

**Issue by Senliast** [GravityBox/GravityBox#2040]
I have Android 10, Evolution X ROM and GravityBox Q. The feature to disable tiles
on secured lockscreen doesnt work, just nothing happens if i select tiles i wish
to block. Any chance to fix it?

**Comment by C3C0** [comment]
Noticed that as well after updating OnePlus 7Pro to OOS10.0.3. Will be looking into it.
