### ISSUE TITLE
GravityBox system framework not responding. Exiting.

### ISSUE THREAD

**Issue by marticztn** [GravityBox/GravityBox#2043]
**Phone**: OnePlus 7 Pro
**OS**: Oxygen OS OP7Pro_O2_BETA_7 (Android Q)
**Framework**: EdXposed Framework v90.0 - v0.4.6.0_beta (4471) (SandHook)
**Other**: Magisk installed, version 20.1 (20100)
**GravityBox version**: 10.0.0-beta-6

**Comment by C3C0** [comment]
Make sure to use custom magisk version as EdXposed 0.4.6.0 requires some special changes which are not part of official magisk yet.
- Open Magisk, Settings , choose update channel "Custom" and enter http://edxp.meowcat.org/repo/version.json
- update magisk
- install EdXposed 4481 (I am running Sandhook on my OP7pro and it's stable)

**Comment by marticztn** [comment]
Followed all your steps and it works perfectly now, really appreciated it!
