### ISSUE TITLE
[Android P] Lockscreen mods somehow crashes system-ui

### ISSUE THREAD

**Issue by Olit2000** [GravityBox/GravityBox#2044]
After my System-UI crashed once again, I looked into logcat to see if find some cause. Thats what I found:
[adbF.log](https://github.com/GravityBox/GravityBox/files/4013989/adbF.log)
Somehow the PINView can't be hooked correctly. Note that I use Pattern unlock.

at line 131 I found GB-Lockscreen-init, so I thought It might be related
[here](https://github.com/GravityBox/GravityBox/blob/fbe9b9d7f2e660812913cf324342d12b69097318/GravityBox/src/main/java/com/ceco/pie/gravitybox/ModLockscreen.java#L342) is the code the stacktrace is referring

I use GB 9.1.3 on an Samsung Galaxy S5 running LineageOS 16.0

**Comment by Olit2000** [comment]
Is there some way to tell whether this isn't a bug in EdXposed?

**Comment by C3C0** [comment]
ART (Android runtime) crashes in libart.so are EdXposed related and can't be fixed at module level.

**Comment by Olit2000** [comment]
I created an issue at EdXposed [here](https://github.com/ElderDrivers/EdXposed/issues/432)

**Comment by mate-in-1** [comment]
My LG V30 with Stock Pie (VS996 30C) and Magisk 20.2 / EdXposed Sandhook 0.4.5.1 (or above) with Gravitybox 9.1.3 restarts randomly also, and I cannot figure out the culprit either. For the record, I use Fingerprint unlock but the restart doesn't seem to coincide with the unlock -- sometimes when I'm on a call or the phone is idle.

What is the best way to capture the log at the time of the crash? Logcat reader and others I have tried don't seem to save the log at the time of crash. I have tried installing Log Catcher but am not sure if that is what I need.

**Comment by C3C0** [comment]
Use ADB command line on a PC. ADB is part of Android SDK but there are also lightweight packages you can find with Google. Also search for how  to use ADB to capture logs and save them to a file.

**Comment by mate-in-1** [comment]
The reboots happen randomly (sometimes days in between) so I assume that means I need to leave my phone connected to my PC/ADB all the time to capture the crash logs? 

Is there no other way? Thanks!

**Comment by Olit2000** [comment]
Depends on how severe the crash is.
If the screen goes black and after some time the lockscreen reappears, you can use `adb logcat -d *:E > C:\somefile`.
If the bootanimation reappears (like after a soft reboot) and you're promted to enter your pin after reboot (fingerprint not working yet) that should still work.
If the phone reboots completely (first showing the LG logo then bootanimation then enter your sim pin) you cant use the above command. You need to leave your phone connected to my PC/ADB (`adb logcat *:E > C:\somefile`) all the time. If you're lucky the error is printed to logcat before the phone reboots. The command terminates automatically when your phone reboots, so the logs dont get overwritten

**Comment by mate-in-1** [comment]
Appreciate the write-up, thanks, and I will give that a shot next time I have a crash.

**Comment by civiliann** [comment]
安卓9.0 GravityBoxp (P)Can't modify status bar color？O have

**Comment by Olit2000** [comment]
Has been fixed
