### ISSUE TITLE
Secured QS on lockscreen sometimes will not be grayed out

### ISSUE THREAD

**Issue by Senliast** [GravityBox/GravityBox#2050]
The feature to block certain QS on secured lockscreen generally works, but sometimes - not, the tiles still active after lock. Could you look into it?
Android 10, EdXposed Yahfa, Magisk 20.3, GravityBox beta 6.

**Comment by C3C0** [comment]
Make sure device is not unlocked by trust manager policy. (Trusted bluetooth, on body detection, Trusted WiFi (GravityBox feature)). QS protection applies only to fully locked state.

**Comment by Senliast** [comment]
Nope, it isn't.

P.S. ah I checked just now, they are actually locked, I.e I can't switch them state or expand them, but they are not greyed out.

P.P.S. now I found out that the tiles are also sometimes switchable on lockscreen(

**Comment by C3C0** [comment]
Not sure what to to about it. The logic depends on standard API that tells whether device is currently locked or not. When tiles are not locked it means that API told module that device is not locked.

**Comment by Senliast** [comment]
Ok. Yeah then no matter, it's may be EdXposed 10 problem or so on. I am planning to clean reinstall my phone, may be it will be solved then. 
May be the problem is on my phone. Just ignore this issue. Thank you for your effort.
