### ISSUE TITLE
[BUG] OOS 9.0.11 Led in ultimate notification control

### ISSUE THREAD

**Issue by Choukajohn** [GravityBox/GravityBox#2059]
Hello,

I'm running OOS 9.0.11 on OnePlus5T, with Magisk 20.4, RIRU Core 19.7, EdXposed 0.4.6.1 and GravityBox P 9.1.3.

In ultimate notification control section in both default and per-app settings, override led mode doesn't work.
No matter which values I'm using for Led color and Led on or off duration, it doesn't change anything.
LED still blink in white at the same frequency.

**Comment by C3C0** [comment]
LED colors are strongly hardware dependent. Even when you set color from the software side, hardware will do its own approximation in the end. Some device can handle true RGB some not. From my past experience with OnePlus devices, basic colors should work. Use "corners" of the palette when choosing color. Try some basic colors first like #ff0000, #00ff00, #0000ff

**Comment by Choukajohn** [comment]
Hello and thanks for your answer.
For the color you're right it seems to work with "corners" colors.
But for the on or off duration, it doesn't work even with the edxposed last version.

**Comment by C3C0** [comment]
It's a led driver limitation. I cannot do anything about it at module level.

**Comment by Choukajohn** [comment]
OK thanks for your help!
