### ISSUE TITLE
Status bar clock causing errors in log with every second

### ISSUE THREAD

**Issue by usamaiqbal1177** [GravityBox/GravityBox#2060]
Hello @C3C0 GravityBox Q working fine on Cygnus rom which is CAF based. But when I open mat log it is showing error with every second passing! Please have a look at it, it might be draining battery also. 
[logs-2020-04-01-22-29-04.zip](https://github.com/GravityBox/GravityBox/files/4416711/logs-2020-04-01-22-29-04.zip)

**Comment by C3C0** [comment]
It's just a warning showing during status bar container layout refresh which happens only while screen is on so don't worry about the battery - it won't affect it at all. Question if it's GravityBox related.
Do you have Status Bar / Max notification icons feature enabled? If yes, try to disable it and check whether those warnings are gone.

Btw, I couldn't find any errors related to Clock as title of this issue report says.

**Comment by usamaiqbal1177** [comment]
There were not actual malfunction that cause the clock or anything to misbehave. It worked absolutely fine as I said... I removed that rom because it had other errors also. My friend is using that rom, I'll ask him to follow up with your suggestion of turning off max notification with GravityBox. Thanks for looking into it
