### ISSUE TITLE
Data traffic monitor not showing on mobile data network

### ISSUE THREAD

**Issue by andronoob** [GravityBox/GravityBox#2062]
Similar to #1890 

ROM: LineageOS 17.1 official 20200402

Device: Lenovo ZUK Z2 Plus

EdXposed SandHook v0.4.6.2 (4530) Canary

GravityBox [Q] 10.0.0-beta-6

**Comment by usamaiqbal1177** [comment]
It doesn't show traffic in any rom at all with mobile data. 😔

**Comment by andronoob** [comment]
I see. It was caused by Data Saver mode. It should be related to [ConnectivityManager#getActiveNetworkInfo()](https://developer.android.com/reference/android/net/ConnectivityManager#getActiveNetworkInfo())

**Comment by andronoob** [comment]
@C3C0 Please fix this.

**Comment by andronoob** [comment]
I feel anxious that the captive portal detection could be inaccurate (typically due to GFW). There could also be other interferences like VPN connections. Also, there could be an ethernet connection...

**Comment by andronoob** [comment]
In my opinion, the traffic monitor should not detect whether the Internet is reachable - it's totally reasonable for a user to connect to LAN only.

**Comment by C3C0** [comment]
Feature tests if ANY type of network is available. Looks like API does not provide that info when data saver is on. Regarding how data is counted:
If /proc/net/xt_qtaguid/iface_stat_fmt file exists, values are parsed from this file for all interfaces except for loopback and tunneling interfaces.
If file does not exist, [TrafficStats API](https://developer.android.com/reference/android/net/TrafficStats?hl=en) is used.

**Comment by usamaiqbal1177** [comment]
@C3C0 can u plz also add the support for the new traffic meter indicator. It's now included in so many roms. Currently it doesn't support and gives error mentioned in issue #2047 

> 
![Screenshot_20200521-043252_Google_Play_Store](https://user-images.githubusercontent.com/58624914/82571231-1784bd00-9b9c-11ea-9e63-e002b4651901.png)

**Comment by usamaiqbal1177** [comment]
@C3C0 can u plz also add the support for the new traffic meter indicator. It's now included in so many roms. Currently it doesn't support and gives error mentioned in issue #2047 

 
![FOTO_20200521_195352](https://user-images.githubusercontent.com/58624914/82571736-d4771980-9b9c-11ea-8297-f09110bf6ff4.jpg)

**Comment by andronoob** [comment]
I'm not quite sure, but it seems that the traffic through shadowsocks-android (which utilizes android VPN API to redirect Internet traffic to a socks5 proxy listening at 127.0.0.1) is counted multiple times?
