### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by lespea** [GravityBox/GravityBox#2078]
Just curious if there are any plans to support Android 11 or most likely not?  Definitely understand if isn't going to happen... just wanted to plan for updating.

**Comment by C3C0** [comment]
Hi. Thanks for you interest. All depends whether I'll be able to get a device with Android 11 and enough time for development. Currently I am in a situation that made me put my all  free time Android activities on a side track.

**Comment by lespea** [comment]
Sounds good, thanks for the update :). Really appreciate you maintaining this for so long in the first place, it makes stock Android bearable!
