### ISSUE TITLE
Quick Settings on lock screen

### ISSUE THREAD

**Issue by gugucarv** [GravityBox/GravityBox#2080]
good night. Locking quick settings on the lock screen is not working. even activating the lock is still allowed to activate and disable any quick settings on the lock screen. It was possible to block the shutdown menu .. gravity box installed on moto one deen stock rom 10 retbr

**Comment by C3C0** [comment]
Note that this applies only when lock screen is secured and device locked (e.g. you have to enter pin to unlock). If it's such case and it is not working it's most likely some rom specific incompatibility.

**Comment by gugucarv** [comment]
Good Morning. after installing the latest available version, the problem was resolved. Thank you
