### ISSUE TITLE
Clock becomes `hh:mm` instead of `hh:mm:ss` at 00 seconds

### ISSUE THREAD

**Issue by bilogic** [GravityBox/GravityBox#2084]
Hi,

I'm using GravityBox [Q] Android 10 with `Show seconds` checked under `Clock settings`.
Whenever the seconds reaches 0, the Clock shows `hh:mm` instead of `hh:mm:ss`.

Able to fix? Thank you.

**Comment by C3C0** [comment]
Cannot reproduce such behavior on OnePlus 7T nor on Pixel 3A.

**Comment by bilogic** [comment]
It is on my samsung A50. How can I provide more info?

**Comment by LoganDark** [comment]
[Looks fine to me...](https://puu.sh/GL8uP/58eb25c771.mp4)

**Comment by bilogic** [comment]
Here's my videos, 

https://imgur.com/a/rGyD2T9 - 10.0.0-beta-7
https://imgur.com/a/xQCPbsd - 10.0.1

**Comment by bilogic** [comment]
need more info?

**Comment by C3C0** [comment]
Samsung OS is not officially supported. I cannot provide adjustments for devices I don't own. I am sorry.

**Comment by alou-S** [comment]
Same issue on my Samsung M01, Seems to be a thing with OneUI.

**Comment by LoganDark** [comment]
> Same issue on my Samsung M01, Seems to be a thing with OneUI.

@alou-S See @C3C0's comment above:

> Samsung OS is not officially supported. I cannot provide adjustments for devices I don't own. I am sorry.

**Comment by techIndia-hacker** [comment]
Use firefds. search GitHub

**Comment by bilogic** [comment]
> Use firefds. search GitHub

@techIndia-hacker thanks! firefds works!
