### ISSUE TITLE
Not request for root rights 

### ISSUE THREAD

**Issue by meibassam** [GravityBox/GravityBox#2085]
I have Xiaomi mi9t Android 10 rooted with magisk 21 but unfortunately Grivaty box the only app not asking for root righst to apply the changes I did in, any thing doing in grivaty box is useless because as I said in magisk " superuser" list there is no gravity box 
![IMG_20201113_091921](https://user-images.githubusercontent.com/32242190/99035759-5fa3fb80-2591-11eb-90e5-3d7886e7599f.jpg)

**Comment by usamaiqbal1177** [comment]
Gravitybox is an EdXposed module. It doesn't require su permissions!

**Comment by meibassam** [comment]
So why not apply any changes in UI I did it in Grivaty box?

**Comment by usamaiqbal1177** [comment]
> So why not apply any changes in UI I did it in Grivaty box?

If you've enabled app list in EdXposed manager, make sure to whitelist android system and systemUI

**Comment by meibassam** [comment]
Yes it's enabled, but how could I check for whitelist and system UI? 
I couldn't find it 
![IMG_20201113_191700](https://user-images.githubusercontent.com/32242190/99094550-05348a80-25e5-11eb-8680-9a8d5424162b.jpg)
![IMG_20201113_191643](https://user-images.githubusercontent.com/32242190/99094575-0cf42f00-25e5-11eb-98d0-094b41c25666.jpg)

**Comment by usamaiqbal1177** [comment]
> Yes it's enabled, but how could I check for whitelist and system UI?
> I couldn't find it
> ![IMG_20201113_191700](https://user-images.githubusercontent.com/32242190/99094550-05348a80-25e5-11eb-8680-9a8d5424162b.jpg)
> ![IMG_20201113_191643](https://user-images.githubusercontent.com/32242190/99094575-0cf42f00-25e5-11eb-98d0-094b41c25666.jpg)

Go to applications tabs in manager. Enable/disable apps that needs to be hooked by EdXposed

**Comment by meibassam** [comment]
Already activated, still nothing happened :( 
![IMG_20201113_200613](https://user-images.githubusercontent.com/32242190/99099669-d372f200-25eb-11eb-9ddf-9c193d969ca7.jpg)

**Comment by usamaiqbal1177** [comment]
> Already activated, still nothing happened :(
> ![IMG_20201113_200613](https://user-images.githubusercontent.com/32242190/99099669-d372f200-25eb-11eb-9ddf-9c193d969ca7.jpg)

You didn't enable system UI

**Comment by meibassam** [comment]
> > Already activated, still nothing happened :(
> > ![IMG_20201113_200613](https://user-images.githubusercontent.com/32242190/99099669-d372f200-25eb-11eb-9ddf-9c193d969ca7.jpg)
> 
> You didn't enable system UI

Yes correct, just now enabled it and restart the phone, but still nothing worked
![IMG_20201113_202807](https://user-images.githubusercontent.com/32242190/99102302-f2bf4e80-25ee-11eb-94b4-db64556d7c22.jpg)
 work

**Comment by usamaiqbal1177** [comment]
Wait, is that MIUI? I don't think gb works well with MIUI. Use CustoMIUIzer for MIUI

**Comment by meibassam** [comment]
> Wait, is that MIUI? I don't think gb works well with MIUI. Use CustoMIUIzer for MIUI

Oooh man .. You are right 😢
I download "CustoMIUIzer" It's working probably but has not a lot of options like gravitybox such change battery icon and show date in status bar and add more options to power menu :( 

BTW gravitybox was working fine with MIUI 10

**Comment by usamaiqbal1177** [comment]
> > Wait, is that MIUI? I don't think gb works well with MIUI. Use CustoMIUIzer for MIUI
> 
> Oooh man .. You are right 😢
> I download "CustoMIUIzer" It's working probably but has not a lot of options like gravitybox such change battery icon and show date in status bar and add more options to power menu :(
> 
> BTW gravitybox was working fine with MIUI 10

Move to AOSP roms 💯 much better than MIUI

**Comment by meibassam** [comment]
I took a look it's amazing
I'm going to try it soon 

Thx bro you r the best 👍💯

**Comment by meibassam** [comment]
Do you know any app to change status bar like battery and clock?

**Comment by usamaiqbal1177** [comment]
> Do you know any app to change status bar like battery and clock?

Only gravitybox can do it. Use it on aosp roms

**Comment by usamaiqbal1177** [comment]
Mark this issue as resolved
