### ISSUE TITLE
Data traffic monitor shows wrong bandwidth when connected to vpn

### ISSUE THREAD

**Issue by techIndia-hacker** [GravityBox/GravityBox#2087]
So, I always keep a vpn active for privacy reasons to minimise Google trackers etc. But when connected to vpn, performing a ookla speedtest shows that its 16MB/s but ur bandwidth meter shows 48MB/s. It happens obviously because of the vpn connectivity but I know it can be fixed too.

Device:- Oneplus 7 pro
Android 10

**Comment by techIndia-hacker** [comment]
@C3C0  Please look into this

**Comment by Mikanoshi** [comment]
It's not a module's problem, default traffic meter also shows incorrect values.
Problem is with Android's TrafficStats API, it counts total number of rx/tx bytes on all interfaces, WLAN and VPN add additional interface each, on my device value is doubled when using VPN. This issue is even mentioned in Android's source code:
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/net/TrafficStats.java#675
It recommends using NetworkStatsManager, but it only supports getting data of a particular network type. I tried this:
```
NetworkStatsManager networkStatsManager = (NetworkStatsManager)act.getSystemService(Context.NETWORK_STATS_SERVICE);
NetworkStats.Bucket bucket = networkStatsManager.querySummaryForDevice(ConnectivityManager.TYPE_VPN, "", 0, System.currentTimeMillis());
```
and it returns null bucket, so no idea :)

**Comment by C3C0** [comment]
@Mikanoshi 
Yeah, this is an old issue or "feature" of traffic stats api. Therefore I have an alternate method which might not work on all devices / Android varieties as it tries to read the stats directly from /proc sysfs
https://github.com/GravityBox/GravityBox/blob/q/GravityBox/src/main/java/com/ceco/q/gravitybox/TrafficMeterAbstract.java#L370

In case it fails it falls back to traffic stats

**Comment by techIndia-hacker** [comment]
But still gravitybox shows wrong bandwidth reading when connected to adguard. I don't know about other vpns though.
But here is an app which I use and it's readings are almost perfect. Would like to request @C3C0 to imitate the logic used in the app. If a user app can do it, gravitybox has su privileges.

APP LINK
https://play.google.com/store/apps/details?id=com.evozi.network

**Comment by techIndia-hacker** [comment]
U tell me if fails or not. U have the same device man.

I didn't see any file called sysfs in /proc in my phone

**Comment by Mikanoshi** [comment]
> Yeah, this is an old issue or "feature" of traffic stats api. Therefore I have an alternate method which might not work on all devices / Android varieties as it tries to read the stats directly from /proc sysfs

What's the difference? These are the contents of this file on my device:
```
ppp0 184209995 195987 190014765 236097 169375896 184431 14806835 11452 27264 104 189369102 232820 645566 3276 97 1
wlan0 198325436 205011 190722216 232914 1991458 2545 4118241 4092 192215737 198374 631716 2511 286769 1150 189803731 229253
rmnet_data0 1246 16 1264 17 0 0 165 3 1081 13 0 0 131 2 1133 15
dummy0 23541 133 52542 341 0 0 23541 133 0 0 0 0 47082 266 5460 75
lo 6330 82 6330 82 0 0 4450 42 1880 40 0 0 4450 42 1880 40
```
Counting everything except lo will still count wlan+ppp and result would be double the speed.
ppp* must be excluded too then.

**Comment by techIndia-hacker** [comment]
Yeah just keep wlan0 and data0 for 4g/5g i guess

**Comment by Mikanoshi** [comment]
I get rmnet_data0 and rmnet_data1 when mobile internet is enabled. H+ or whatever.

**Comment by techIndia-hacker** [comment]
Ok @C3C0 please do something regarding this in nxt update

**Comment by Mikanoshi** [comment]
@techIndia-hacker
Can you post contents of this file on your device when VPN is active?
Use adb shell or terminal to run this command:
`cat /proc/net/xt_qtaguid/iface_stat_fmt`

**Comment by techIndia-hacker** [comment]
No such file or directory

**Comment by Mikanoshi** [comment]
What do you have then? File list from /proc/net/?

**Comment by techIndia-hacker** [comment]
![Screenshot_20201207-204954](https://user-images.githubusercontent.com/58086339/101369132-f3859080-38cd-11eb-9eea-26c6984d8ecc.jpg)

**Comment by Mikanoshi** [comment]
Well, shit :) There might be another way, TrafficStats uses NetworkStatsService class to get its data, that class also has definition for exposed native method that gets data about particular network interface, not all of them, getting VPN one and substructing it from total might work. But you have your values tripled, this means there are 2 unnecessary interfaces that are being counted. Show the result of `ifconfig` command under root with VPN active.

**Comment by techIndia-hacker** [comment]
![Screenshot_20201207-210856](https://user-images.githubusercontent.com/58086339/101371223-81fb1180-38d0-11eb-82cf-dc8976c6e47c.jpg)

**Comment by Mikanoshi** [comment]
Yeah, both loopback and tunnnel...

**Comment by techIndia-hacker** [comment]
I got it it's triple in case of adguard because unlike normal vpns the inflow and outflow of data happens simultaneous through 2 different virtual interfaces. + The wlan0 bandwidth is added too. So 2+1=3

**Comment by Mikanoshi** [comment]
Another place to get rx/tx stats is in /sys/class/net/:
```
cat /sys/class/net/wlan0/statistics/tx_bytes
cat /sys/class/net/wlan0/statistics/rx_bytes
```

**Comment by techIndia-hacker** [comment]
Yeah this one has 11 million 450 thousand something as output

**Comment by Mikanoshi** [comment]
@C3C0 Check this out, seems to be working just fine even from regular app, should be compatible with more devices as getTxBytes/getRxBytes are in all versions of TrafficStats:
```
Method getTxBytes = TrafficStats.class.getDeclaredMethod("getTxBytes", String.class);
Method getRxBytes = TrafficStats.class.getDeclaredMethod("getRxBytes", String.class);
for (Enumeration<NetworkInterface> list = NetworkInterface.getNetworkInterfaces(); list.hasMoreElements();) {
	NetworkInterface iface = list.nextElement();
	if (iface.isUp() && !iface.isVirtual() && !iface.isLoopback() && !iface.isPointToPoint() && !"".equals(iface.getName()))
	Log.e("miuizer", iface.getName() + ": " + getTxBytes.invoke(null, iface.getName()) + ", " + getRxBytes.invoke(null, iface.getName()));
}
```

**Comment by C3C0** [comment]
I'm sorry but I don't have time to look into it these days due to more important things that life brings to take care of. Thanks for your understanding.

**Comment by techIndia-hacker** [comment]
In that case we need a new developer who is willing to continue @C3C0 work. Gravitybox needs an emergency update due to changes in riru core and also this data monitor.

@Mikanoshi why don't u take this up personally. U too have the capability

**Comment by Mikanoshi** [comment]
Currently I write mods for MIUI ROMs only, because I only have 1 device (even though my module works on Android 7-10, even 11 with some issues, but I write mods blindly for older versions). Stock Android sucks and I will never use it :D
There is no EMERGENCY BTW, new EdXposed is still canary, I won't even try it until the release, many things there can change.
App list mode support has no fast solution anyway.

**Comment by techIndia-hacker** [comment]
No, can u update gravitybox to support the new riru core and while doing so
u can add this bandwidth meter code too?

**Comment by Mikanoshi** [comment]
I'm already running a code above in my module, works good, values are the same with or without VPN, will include it in the next release :)

You can change 29 to 27 here:
https://github.com/GravityBox/GravityBox/blob/q/GravityBox/build.gradle#L8
minSdkVersion too if Android Studio insists, and recompile GravityBox, it should work on any riru/EdXposed then, but on 0.5+ it will still run like crap, but at least some mods will work.

**Comment by C3C0** [comment]
@Mikanoshi 
Looks like I am not able to call NetworkInterface.getNetworkInterfaces() from SystemUI. Getting null list.
Permissions should be fine (INTERNET, ACCESS_NETWORK_STATE)

**Comment by techIndia-hacker** [comment]
Probably location permission needed

**Comment by C3C0** [comment]
I doubt. Location permission already there. Otherwise I wouldn't be able to provide GPS related QS tiles.
Trying some diferent approach now.

**Comment by techIndia-hacker** [comment]
If everything fails su privileges can be exercised

**Comment by C3C0** [comment]
@techIndia-hacker 
Please test with attached APK if you can. It has debug logging for traffic meter turned on so it would be good if you then shared the module log from EdXposed manager.

[GravityBox_Q_10.0.1_debug.apk.zip](https://github.com/GravityBox/GravityBox/files/5743024/GravityBox_Q_10.0.1_debug.apk.zip)

**Comment by techIndia-hacker** [comment]
Ok no issue. I will try to send logs

**Comment by Mikanoshi** [comment]
SystemUI on MIUI doesn't even have INTERNET permission in manifest.

**Comment by C3C0** [comment]
Not needed. Solved it in a different way.

**Comment by techIndia-hacker** [comment]
Yeah, the bandwidth meter is more or less correct with minor deviation from ookla values. But I will do more tests this week and report back. 

Please allow custom positioning of the bandwidth meter because the icon is getting too close to the am/pm text of the clock on the left if left position is selected.(i can do it if u allow me to)

Another thing is disconnection to the internet didn't hide the icon if hide inactivity is off

**Comment by techIndia-hacker** [comment]
Ok the upload bandwidth is not measured in simple style probably. In simple style download and upload bandwidth should be added up and shown. May be it's a bug @C3C0  please comment

**Comment by C3C0** [comment]
@techIndia-hacker Simple style shows download traffic only. It's by design.

**Comment by techIndia-hacker** [comment]
Can the simple style be modified to show the summation of upload and download please @C3C0  or else it will be just the omni style with download selected only. 

Or else please add download+upload option in omni style.

The oxygen of data meter is designed to show download+upload added up but it doesn't work with the vpn.
