### ISSUE TITLE
Gravitybox not working anymore

### ISSUE THREAD

**Issue by techIndia-hacker** [GravityBox/GravityBox#2089]
Device:- 1+ 7T 
EdXposed v0.5.0.6 b4576
Oxygen Os 10.3.7

Gravitybox used to work fine but not any more after recent system and edxposed updates. I have navigation bar mod and certain lockscreen mods turned on. They aren't working anymore. But gravitybox doesn't throw up any error of any kind

**Comment by brian6932** [comment]
It's incompatible with EdXposed Canary atm. The annoying thing is that Riru 21.3 is the last version that actually works with EdXposed 0.4.6, so you'd have to be both on an outdated version of Riru and an outdated version of EdXposed to use GravityBox, there isn't even a pre-release to use with EdXposed Canary either.

**Comment by C3C0** [comment]
They changed selinux settings preventing modules from reading preferences during boot. I don't know why.

**Comment by brian6932** [comment]
Yea I noticed that most Xposed Modules weren't working, like is this supposed to be a bug or intentional?

**Comment by C3C0** [comment]
https://github.com/ElderDrivers/EdXposed/commit/84822379184bfdcd830fff997265ac410e200e66#commitcomment-44827982

**Comment by techIndia-hacker** [comment]
After latest EdXposed update 0.5.0.6_4589 yafa, gravitybox system framework don't even get initialised 😕. But I have other modules working as usual. @C3C0 please do something

**Comment by Mikanoshi** [comment]
What other modules have hundreds of mods? Well, mine for MIUI does, and it works like crap on 0.5+. EdXposed devs are fighting Google's safety net checks and it makes our work a lot harder. Even if we update modules to support new version it will introduce a lot of additional code being executed each time any app launches.

**Comment by HanabishiRecca** [comment]
0.5 released now. That's sad.

**Comment by Mikanoshi** [comment]
> 0.5 released now. That's sad.

The fact that 0.5 is released? Yeah, that's sad, 0.4 was working perfectly for those who don't need Safety Net.

**Comment by HanabishiRecca** [comment]
> The fact that 0.5 is released? Yeah, that's sad, 0.4 was working perfectly for those who don't need Safety Net.

Exactly. I don't even have google s**t on my phone.

**Comment by C3C0** [comment]
c274d49f9453e9aef3b7b4871227d4ef98683eee

**Comment by Mikanoshi** [comment]
Without shared prefs migration? :) Also did you just change the way all hooks are applied in initZygote?
https://github.com/GravityBox/GravityBox/blob/c274d49f9453e9aef3b7b4871227d4ef98683eee/GravityBox/src/main/java/com/ceco/q/gravitybox/GravityBox.java#L94
Previously they were for system_server only, I thought you had no system-wide framework hooks.

**Comment by C3C0** [comment]
@Mikanoshi This is just an initial phase to get things working. My resource replacement implementation didn't work if I had it for system server only. I will have to invest more time in submodules that are initiates in zygote.

Regarding preferences, I just updated my current implementation. I use reflection to get actual path of where preferences are stored. This also works with my existing backup/restore implementation.
But I also use other non-xml settings like images within "files" folder. Those need to be readable by foreign processes so I am working on relocating them to the same folder where shared prefs XMLs are stored.

**Comment by Mikanoshi** [comment]
I'm amazed that GravityBox was working at all earlier with target sdk 29. It activates an additional SELinux rule that prevents apps from reading data of other apps, so even app list mode in EdXposed 0.4 should break all the mods that rely on reading shared prefs.

> My resource replacement implementation didn't work if I had it for system server only

Any hook that applies to framework class and is intended to modify all apps is not working if you apply it for system_service only.
But if you remove this check it will apply all the initZygote hooks to each process in the system upon creation. I have about 30 mods like that, 1-3-5 hooks each, including resource hooks inside Resources class. Every hook introduces delay, now launch of every app is delayed by 1.5-2 seconds...

> I use reflection to get actual path of where preferences are stored.

Yes, it will use the new path as soon as user updates the module, but prefs from old one won't be migrated, right?
Users will have to restore backup manually.

**Comment by C3C0** [comment]
@Mikanoshi 
Yeah, that's what I did - allowed init for all zyogtes, not only system server one. So far not registering any slowdowns.

Regarding settings. My backup/restore functionality will allow to restore backup that was done prior to upgrading to new EdXposed. Backup folder structure stays the same. It is only target structure that is going to be different during restore.

**Comment by Mikanoshi** [comment]
But will your backup/restore allow to backup from old settings and restore to new ones? Otherwise user must have backup ready before updating.

**Comment by C3C0** [comment]
Yeah. Anyone that has any backup will be able to use it with the new version regardless what EdXposed he is running.
Just tested it and seems to work fine.
858367f43e9e345e181711ead769bc62427b73ca

Regarding reading preferences for SDK 29 you mentioned earlier. This was possible thanks to sepolicy rule that was removed
`attradd { system_app platform_app } mlstrustedsubject`
It's the rule I was questioning in here if you remember https://github.com/ElderDrivers/EdXposed/commit/84822379184bfdcd830fff997265ac410e200e66#commitcomment-44827982

**Comment by Mikanoshi** [comment]
> Anyone that has any backup will be able to use it with the new version regardless what EdXposed he is running.

What if user has no backup and then updates the module to the version that reads from and writes to new shared prefs?

> This was possible thanks to sepolicy rule

This only applies to system/platform apps, no? I was talking about SDK>27 SELinux rule that prevents any app from reading any world readable file owned by other app:
https://developer.android.com/about/versions/pie/android-9.0-changes-28#per-app-selinux

**Comment by C3C0** [comment]
> What if user has no backup and then updates the module to the version that reads from and writes to new shared prefs?

There's going to be a warning in the changelog. Users without backup will lose configuration of course. There is no other way.
In theory there could be a mechanism for automatic copy of preferences depending on actual path of preference folder. But not sure if I want to invest time in this.

> This only applies to system/platform apps, no? I was talking about SDK>27 SELinux rule that prevents any app from reading any world readable file owned by other app:
> https://developer.android.com/about/versions/pie/android-9.0-changes-28#per-app-selinux

Right. I basically need access from framework and SystemUI for 99% of the functionality.
There are couple of those initZygote submodules that most likely can cause problems.

**Comment by Mikanoshi** [comment]
Yes, that's what I was talking about, automatic migration. Check some migration pref in new xml, if it's not set load old xml and import all prefs from it to new xml, then set migration pref to true.

**Comment by C3C0** [comment]
Actually, you don't even need a flag if we are talking about one-way migration. You just find out that your prefs folder is no longer within app data but within /data/misc and copy all prefs from app data to /data/misc, deleting original prefs after copy and then rebooting.

**Comment by Mikanoshi** [comment]
How do you know that you haven't done that already? :)

**Comment by C3C0** [comment]
By deleting original files :)

**Comment by Mikanoshi** [comment]
And if user downgrades EdXposed and then returns to latest version it will create new prefs and then replace current with empty ones :D

**Comment by C3C0** [comment]
Yes, there are probably couple of marginal scenarios that can play their role. Another one is when EdXposed is disabled - module will create new prefs file under standard location. So yes, going with some flag is more bulletproof.

**Comment by Mikanoshi** [comment]
> So far not registering any slowdowns.

Looks like hooks are optimized a lot better in new version, same code that took 1500ms in 0.4 now takes 150-400ms, still it's a delay only from my module and it's already significant, I can feel apps are slower to launch.

> deleting original prefs

BTW clearing module data removes old prefs, not new ones :) They need to fix that.

**Comment by HanabishiRecca** [comment]
Tried Ed 0.5.1.3 with GB 10.1. Sadly preferences does not restore after reboot.

**Comment by Mikanoshi** [comment]
@C3C0 Are you using `getSharedPreferences(prefsName, Context.MODE_WORLD_READABLE)` or `getPreferenceManager().setSharedPreferencesMode(Context.MODE_WORLD_READABLE)` (not sure if second was even modified by EdXposed)?
Shared prefs xml in /data/misc/ is not world readable by default, so I still have to use Context.MODE_WORLD_READABLE, otherwise some processes fail to load it. Fixing permissions is also an option, but this seems to be working fine.

**Comment by C3C0** [comment]
@Mikanoshi I don't need to since I manage permissions automatically in my WorldReadablePrefs implementation.

**Comment by Mikanoshi** [comment]
Yes, I do that too for old prefs, but they added MODE_WORLD_READABLE in 0.5.x.x, should be better than fixing perms every time file changes :)

**Comment by C3C0** [comment]
I understand your point. The thing is I wanted to use what was done already and I found it more suitable due to maintaining backwards compatibility with v0.4. Didn't want to have too much "if newer framework then do this" conditions in the code.

**Comment by C3C0** [comment]
@HanabishiRecca did you create GravityBox backup before upgrading EdXposed? There's no automatic preference migration. Manual backup/restore must be used

**Comment by HanabishiRecca** [comment]
@C3C0 no, I'm setting it manually. And settings are in the right state inside GB. After the reboot I should toggle off and on prefs to make them work again.

**Comment by Mikanoshi** [comment]
This actually works
```
try {
	return context.getSharedPreferences(prefsName, Context.MODE_WORLD_READABLE);
} catch (Throwable t) {
	return context.getSharedPreferences(prefsName, Context.MODE_PRIVATE);
}
```
Applies permissions when you change preferences. This one does nothing:
`getPreferenceManager().setSharedPreferencesMode(Context.MODE_WORLD_READABLE)`
I guess fixing them manually is more reliable.

**Comment by C3C0** [comment]
@HanabishiRecca can you list contents of /data/misc/edxp_xxxxxxxxxxxx/0/prefs/com.ceco.q.gravitybox including file attributes?

Also make sure you're using either the latest EdXposed v0.5.1.3 or stable v0.4 with suitable riru version (v21 for v0.4 or v23 for v0.5.1.3)

**Comment by HanabishiRecca** [comment]
```
-rw-rw-r-- 1 u0_a95 u0_a95 16299 2020-12-27 18:18 com.ceco.q.gravitybox_preferences.xml
-rw-rw---- 1 u0_a95 u0_a95   113 2020-12-27 16:30 dummy.xml
-rw-rw-r-- 1 u0_a95 u0_a95   158 2020-12-27 16:32 ledcontrol.xml
-rw-rw-r-- 1 u0_a95 u0_a95   166 2020-12-27 16:32 quiet_hours.xml
-rw-rw-r-- 1 u0_a95 u0_a95   168 2020-12-27 16:35 tuner.xml
```
![mm](https://user-images.githubusercontent.com/13597663/103173251-81c0b700-487b-11eb-9598-17422e0a072a.png)

**Comment by C3C0** [comment]
Permissions and attributes seem to be fine. There still might be something about compatibility between your device and EdXposed. Please share also the logs from EdXposed manager

**Comment by HanabishiRecca** [comment]
> Please share also the logs from EdXposed manager

There is nothing noticeable. Only info messages like
```
I EdXposed-Bridge: Loading modules from /data/app/com.ceco.q.gravitybox-vf7OWbiY_fmuf9xNHRZ4rw==/base.apk
I EdXposed-Bridge:   Loading class com.ceco.q.gravitybox.GravityBox
```
I've also enabled error logging in GB, but there are no errors in the log.

**Comment by HanabishiRecca** [comment]
With enabled verbose logging:
```
I EdXposed-Bridge: Loading modules from /data/app/com.ceco.q.gravitybox-vf7OWbiY_fmuf9xNHRZ4rw==/base.apk
I EdXposed-Bridge:   Loading class com.ceco.q.gravitybox.GravityBox
I EdXposed-Bridge: GB:Hardware: qcom
I EdXposed-Bridge: GB:Product: H4113
I EdXposed-Bridge: GB:Device manufacturer: Sony
I EdXposed-Bridge: GB:Device brand: Sony
I EdXposed-Bridge: GB:Device model: H4113
I EdXposed-Bridge: GB:Device: H4113
I EdXposed-Bridge: GB:Device type: phone
I EdXposed-Bridge: GB:Is MTK device: false
I EdXposed-Bridge: GB:Is Xperia device: true
I EdXposed-Bridge: GB:Is Moto XT device: false
I EdXposed-Bridge: GB:Is OxygenOS ROM: false
I EdXposed-Bridge: GB:Has telephony support: true
I EdXposed-Bridge: GB:Has Gemini support: false
I EdXposed-Bridge: GB:Android SDK: 29
I EdXposed-Bridge: GB:Android Release: 10
I EdXposed-Bridge: GB:ROM: lineage_pioneer-userdebug 10 QQ3A.200805.001 fd7fbf57a8
I EdXposed-Bridge: GB:Preferences: /data/data/com.ceco.q.gravitybox/shared_prefs
I EdXposed-Bridge: GB:Error logging: false
```

Btw `GB:Error logging: false` is lie.

![gl](https://user-images.githubusercontent.com/13597663/103175384-76758780-488b-11eb-818c-8b5db0d777d1.png)

Seems like this is also because GB just doesn't respect it's own settings after reboot.

Device info:
```
Manufacturer: Sony
Brand: Sony
Device: H4113
Product: pioneer
Model: H4113
Fingerprint: Sony/H3113/H3113:8.0.0/50.1.A.4.76/2209478692:user/release-keys
ROM description: H3113-user 8.0.0 50.1.A.4.76 2209478692 release-keys
Architecture: arm64-v8a
Android build: QQ3A.200805.001
Android version: 10
Android sdk: 29
EdXposed version: v0.5.1.3_4646-master (SandHook)
EdXposed api: 93
Riru version: v23.1 (51)
Riru api: 10
Magisk: 20.4 (20400)
```

**Comment by C3C0** [comment]
Definitely EdXposed incompatibility. From the log `I EdXposed-Bridge: GB:Preferences: /data/data/com.ceco.q.gravitybox/shared_prefs`
This is not correct. EdXposed should redirect preferences to point to /data/misc but it is apparently failing to do so. Try to report as an issue within EdXposed repository.

**Comment by C3C0** [comment]
@HanabishiRecca just noticed you're using EdXposed 4646. Use the latest canary instead (4653)

**Comment by HanabishiRecca** [comment]
Yay, canary version solved the issue. Stable releases are so stable 🙃

**Comment by Mikanoshi** [comment]
I've made a prefs migration, seems to be working:
https://code.highspec.ru/Mikanoshi/CustoMIUIzer/src/branch/master/app/src/main/java/name/mikanoshi/customiuizer/utils/Helpers.java#L1432
Only you need to do it when app is no longer writing anything to prefs, e.g. in activity's onDestroy, or it will be replaced back.
Load prefs after that using Context.MODE_MULTI_PROCESS flag which forces them to be read from file and then put a migration pref.

**Comment by HanabishiRecca** [comment]
After the latest Ed update (4655) GB doesn't work again. For now it doesn't start at all (shows framework not responding).
But according to logs module is loaded. And seems like previously configured tweaks remain partially applied.

**Comment by C3C0** [comment]
Most likely configuration directory changed after you performed update. EdXposed uses random directory name so if you uninstall EdXposed and install new version, environment is different. Disabling and enabling module in EdXposed manager should help although you will still have to restore GravityBox preferences in case you have them backed up.

**Comment by HanabishiRecca** [comment]
Already tried to reinstall the module - doesn't help.

**Comment by C3C0** [comment]
Not sure then. I've seen on XDA people are successfully running GravityBox with EdXposed build 4655.

**Comment by techIndia-hacker** [comment]
Give me the apk, Will test it and let you know.

**Comment by C3C0** [comment]
Just did direct update of EdXposed by installing 4655 over enabled 4653. Everything seems to be fine.

**Comment by C3C0** [comment]
@techIndia-hacker the latest apk is in the releases section (version 10.1.0 under tag v10.1.0_q)

**Comment by techIndia-hacker** [comment]
Should i install the latest riru core for testing that?

**Comment by C3C0** [comment]
EdXposed v0.5.1.x requires riru 23.1

**Comment by techIndia-hacker** [comment]
Ok @C3C0  and can u please check the data monitor comments there, i had a request

**Comment by techIndia-hacker** [comment]
Previously u said that we need to backup the settings at gravitybox and restore in the new version the Canary one right? But the backup button is greyed out man...  @C3C0 comment please

**Comment by HanabishiRecca** [comment]
Strangely but after full data wipe and reinstallation firmware from scratch GB works again 😅

**Comment by Sorodon** [comment]
Apparently I'm experiencing the same Problem since I've updated to Android 10 (Q) yesterday. Did a full factory reset, installed Magisk (v21.4), then EdXposed (v0.5.1.4_4655-YAHFA), then GravityBox[Q] (v10.0.1).
Had SandHook installed at first, thought that was causing the problem though switching to YAHFA didn't help.
My Logs look just like the ones from @HanabishiRecca :

> 
> 
> With enabled verbose logging:
> 
> ```
> I EdXposed-Bridge: Loading modules from /data/app/com.ceco.q.gravitybox-vf7OWbiY_fmuf9xNHRZ4rw==/base.apk
> I EdXposed-Bridge:   Loading class com.ceco.q.gravitybox.GravityBox
> I EdXposed-Bridge: GB:Hardware: qcom
> I EdXposed-Bridge: GB:Product: H4113
> I EdXposed-Bridge: GB:Device manufacturer: Sony
> I EdXposed-Bridge: GB:Device brand: Sony
> I EdXposed-Bridge: GB:Device model: H4113
> I EdXposed-Bridge: GB:Device: H4113
> I EdXposed-Bridge: GB:Device type: phone
> I EdXposed-Bridge: GB:Is MTK device: false
> I EdXposed-Bridge: GB:Is Xperia device: true
> I EdXposed-Bridge: GB:Is Moto XT device: false
> I EdXposed-Bridge: GB:Is OxygenOS ROM: false
> I EdXposed-Bridge: GB:Has telephony support: true
> I EdXposed-Bridge: GB:Has Gemini support: false
> I EdXposed-Bridge: GB:Android SDK: 29
> I EdXposed-Bridge: GB:Android Release: 10
> I EdXposed-Bridge: GB:ROM: lineage_pioneer-userdebug 10 QQ3A.200805.001 fd7fbf57a8
> I EdXposed-Bridge: GB:Preferences: /data/data/com.ceco.q.gravitybox/shared_prefs
> I EdXposed-Bridge: GB:Error logging: false
> ```
> 
> Btw `GB:Error logging: false` is lie.
> 
> ![gl](https://user-images.githubusercontent.com/13597663/103175384-76758780-488b-11eb-818c-8b5db0d777d1.png)
> 
> Seems like this is also because GB just doesn't respect it's own settings after reboot.
> 
> Device info:
> 
> ```
> Manufacturer: Sony
> Brand: Sony
> Device: H4113
> Product: pioneer
> Model: H4113
> Fingerprint: Sony/H3113/H3113:8.0.0/50.1.A.4.76/2209478692:user/release-keys
> ROM description: H3113-user 8.0.0 50.1.A.4.76 2209478692 release-keys
> Architecture: arm64-v8a
> Android build: QQ3A.200805.001
> Android version: 10
> Android sdk: 29
> EdXposed version: v0.5.1.3_4646-master (SandHook)
> EdXposed api: 93
> Riru version: v23.1 (51)
> Riru api: 10
> Magisk: 20.4 (20400)
> ```

(Though different Phone and versions).

Does that mean I really have to FactoryReset again like @HanabishiRecca did?

**Comment by C3C0** [comment]
Use version 10.1.0 from here: https://github.com/GravityBox/GravityBox/releases/tag/v10.1.0_q
I cannot update it on Xposed Repository as it's currently broken due to changes of XDA Developers pages.

**Comment by Sorodon** [comment]
Working perfectly fine now! Thanks a lot!
That means no automatic updates, right?

**Comment by Mikanoshi** [comment]
Repo is dead, but module can hook Manager to add custom repo:
https://github.com/ElderDrivers/EdXposedManager/issues/166
That's the only way for now until new repo is made.

**Comment by C3C0** [comment]
@Mikanoshi 
Interesting. Anyway for now I added links to github release page in xposed repo module description.

**Comment by Mikanoshi** [comment]
Description updates are not visible in Manager too, so users who never open website are totally unaware of the updates.
I'm still getting majority of bug reports from version released 2 months ago.

**Comment by C3C0** [comment]
Oh, you're right it's not visible.
