### ISSUE TITLE
[Android 11] Recents key Options Don't Work

### ISSUE THREAD

**Issue by Snuupy** [GravityBox/GravityBox#2090]
Long-press and Double-tap actions do not work on the Recents key. Configuration does work on back key. Did not test home key.

Device: Pixel 4a
Version: Android 11
Gravitybox version: 11.0.0-beta-1

**Comment by C3C0** [comment]
Navbar tweaks have to be enabled for it to work.

**Comment by ecompton59** [comment]
and gravity box is working on 11 with OnePlus 8t thanks for all the work i lost xda thread or id have responded there and he probably has something messing with selinux or wrong xposed setup

**Comment by Snuupy** [comment]
Thank you! That fixed it.
