### ISSUE TITLE
[Android 11] Statusbar brightness control scaling

### ISSUE THREAD

**Issue by reyqn** [GravityBox/GravityBox#2093]
I just noticed that in statusbar tweaks, the brightness control does work, but the scaling seems off.
For example if I swipe right all the way, I'll get max brightness, but if I swipe left all the way, I still have something like 20% brightness (on other versions I had 0%).

I'm using a pixel 3a.

**Comment by usamaiqbal1177** [comment]
It doesn't work at all for me for some reason

**Comment by mesvam** [comment]
> For example if I swipe right all the way, I'll get max brightness, but if I swipe left all the way, I still have something like 20% brightness (on other versions I had 0%).

I have the same issue on OnePlus 7Pro, OxygenOS 11. Swiping from left to right, from 0%-10% of the width, I get max brightness. Then from 10%-100%, brightness goes from minimum to maximum as expected.

**Comment by mesvam** [comment]
The new release 11.0.3 works for me now. Thanks!
