### ISSUE TITLE
Status bar corrupt? 

### ISSUE THREAD

**Issue by deepakgupta82** [GravityBox/GravityBox#2100]
As soon as I unlock my phone, all my status bar icon seem to go to far right. It looks fine on lock screen. 
I think the issue appeared after I was tinkering with status bar settings. I madr some changes is battery style, number of qs tiles per row etx. 
When I disable Gravitybox, I get default icons back. 

![Screenshot_20210123-035239](https://user-images.githubusercontent.com/48987936/105555170-d0ecf100-5d2e-11eb-9897-997c6a46bf07.jpg)
![Screenshot_20210123-035223](https://user-images.githubusercontent.com/48987936/105555175-d34f4b00-5d2e-11eb-9b42-3103267b4993.jpg)

**Comment by C3C0** [comment]
Try disabling "Max notification icons" option in status bar tweaks in case you have it enabled.

**Comment by deepakgupta82** [comment]
Thanks a lot. It worked
