### ISSUE TITLE
Missing Brightness Slider option in Android P and Android Q

### ISSUE THREAD

**Issue by alou-S** [GravityBox/GravityBox#2101]
There was an option to adjust the minimum brightness of the default brightness slider in the status bar in the Android O version of Gravity Box. This option is missing in the Android P and Android Q version.

**Comment by C3C0** [comment]
Brightness tweaks were abandoned due to changes since Android O.
However, you can still tweak some brightness related parameters using Advanced tuning.

**Comment by alou-S** [comment]
Thanks for the reply
