### ISSUE TITLE
Need Help Regarding Make Preference Readable

### ISSUE THREAD

**Issue by Android1500** [GravityBox/GravityBox#2108]
Sir I am facing a issue can you explain me how deal with Support for SDK 24 above as we knw we can't access preferences file coz of MODE_PRIVATE preference ? What you did for makes preference file readable and suggestion i appreciate if you Could help

**Comment by C3C0** [comment]
https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences

**Comment by Android1500** [comment]
> https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences

Yah Sir i tried its working but what about if user don't install edxposed and  if they use Rovo Offical xposed then it will not work i wanna make module compatible for Offically xposed too

**Comment by C3C0** [comment]
I have also another alternative - my own SharedPreferences implementation that takes advantage of FileObserver that monitors changes on physical preference files. When file access attributes are modified by the system, I revert them back to desired state.
https://github.com/GravityBox/GravityBox/blob/r/GravityBox/src/main/java/com/ceco/r/gravitybox/WorldReadablePrefs.java

**Comment by Android1500** [comment]
`
@SuppressLint("SetWorldReadable")
     public static void worldReadable(Context context) {
        File file = new File(context.getApplicationInfo().dataDir);
        File file2 = new File(context.getApplicationInfo().dataDir, "shared_prefs");
        if (file.exists()) {
            file.setExecutable(true, false);
            file.setReadable(true, false);
            if (file2.exists()) {
                file2.setExecutable(true, false);
                file2.setReadable(true, false);
                File file3 = new File(file2, "user_prefs.xml");
                if (file3.exists()) {
                    file3.setReadable(true, false);
                    file3.setExecutable(true,false);


                } }
        }
    }
`

I tried this method onPause() but still its not read preference xml i am making a xposed module which change parameters like imei, android id, etc which read their values from preference.xml but i cant read preference so thats why its show default vale

`public void onPause() {
        super.onPause();
        if (Build.VERSION.SDK_INT >= 23){
            Helper.worldReadable(this);

        }


    }`

**Comment by C3C0** [comment]
Your problem may be different. Although your preference file may be world readable it doesn't mean it is accessible from outside due to SELinux restrictions which is another layer of security. You can verify by switching selinux to permissive mode using adb shell. If you can read preferences then then it's Selinux. (Therefore EdXposed or LSPosed are recommended on higher Android versions).
You should also inspect attributes of preference file via adb shell after onResume to see whether it actually works as you expect.

**Comment by Android1500** [comment]
> switching selinux to permissive mode

Thanx Sir for your reply i just checked which you are suggested and  i tried  to change selinux to permissive mode and now its works!!! so now i got cause of issue so now any solution for this or any way that  value can change even without changing Selinux permission? and please mercy on me if i ask something wrong coz i m new in programming

**Comment by C3C0** [comment]
Fix is to use newer technology such as EdXposed or LSPosed. This can't be fixed in original xposed unless you run selinux permissive. Alternative could be to use https://github.com/apsun/RemotePreferences instead of XsharedPreferences but I have no experience with it.

**Comment by Android1500** [comment]
> Fix is to use newer technology such as EdXposed or LSPosed. This can't be fixed in original xposed unless you run selinux permissive. Alternative could be to use https://github.com/apsun/RemotePreferences instead of XsharedPreferences but I have no experience with it.

Sorry for late rply i fixed it by change Target Sdk 23 coz if  make target sdk 23 then we can use Mode_Worldreadable and easily read preference i knw its not good workaround but its work in my situation Thanks for inform me about selinux things
