### ISSUE TITLE
Status bar clock

### ISSUE THREAD

**Issue by aaref1234** [GravityBox/GravityBox#2109]
Hi .

When you activate any of the clock options and when the device is restarted, there is no change to the status bar. 

Galaxy Note 9 (One UI 2.5)
Android 10

**Comment by Bigdeath** [comment]
Same Problem on S21 Ultra. Clock tweaks doesnt work.
Android 11, OneUI 3.1

**Comment by WiiExpertise** [comment]
Same issue on Moto G Fast on Android 11.
