### ISSUE TITLE
Oos 11;Automatic brightness in qs not available while using status bar swipe brightness feature. 

### ISSUE THREAD

**Issue by s1ddhants1** [GravityBox/GravityBox#2120]
Oneplus 7 pro running oos stable 11.0.1.1
Bug:
As stated in the title,Automatic brightness in qs not available while using status bar swipe feature.The status bar is visible as a long bar covering the automatic brightness button as shown below ⬇️
![Screenshot_20210630-220527](https://user-images.githubusercontent.com/86736295/123998906-90855380-d9ef-11eb-861f-0fb76d8a504c.jpg)
The auto brightness button is visible when adjusting the brightness but is not usable as shown below ⬇️
![Screenshot_20210630-220541](https://user-images.githubusercontent.com/86736295/123998980-a6931400-d9ef-11eb-8692-739bb0d3fd1c.jpg)

**Comment by C3C0** [comment]
Enable "Show brightness icon" in Statusbar  / Quick settings management.
