### ISSUE TITLE
Feature request: Cursor control keys on gestural navbar

### ISSUE THREAD

**Issue by mingaldrichgan** [GravityBox/GravityBox#2121]
Hi, I noticed that the cursor control keys were intentionally removed from the gestural navbar in commit https://github.com/GravityBox/GravityBox/commit/d1a22be72a223b9752d95cb363f3f6aec61e8676. Would you consider either re-enabling that or adding an option for it? I'm sure I'm not the only one who uses gesture navigations but would like fine-grained cursor control when typing. I'm personally sticking with your initial pre-release build because of this.

Thank you for your consideration!

**Comment by C3C0** [comment]
The problem is that even if control keys were visible they were not touchable in gestural mode since there is a restriction applied on touchable area of navbar in fully gestural mode. This is at least on Pixel devices. Currently trying to adjust touchable area to include cursor control keys.
